// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2001: ChapterData = {
  id: 2001,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Фатиха»", en: "Duas from Surah al-Fatihah" },
  duas: [
    {
      id: "2001-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/1.mp3?v=e101b6c8",
      title: { ru: "Мольба о прямом пути", en: "A prayer for the straight path" },
      narration: { ru: "Открывающая сура — сама по себе мольба; читается в каждом ракате намаза", en: "The opening surah is itself a supplication; recited in every unit of the prayer" },
      fullTranslation: { ru: "Тебе одному мы поклоняемся и у Тебя одного просим помощи. Веди нас прямым путём — путём тех, кого Ты одарил милостью, а не тех, на кого пал гнев, и не заблудших.", en: "You alone we worship, and You alone we ask for help. Guide us along the straight path — the path of those You have blessed, not of those who earned Your anger, nor of those who went astray." },
      note: { ru: "Когда читают: в каждом ракате обязательной и добровольной молитвы; при болезни (в хадисах названа «исцеляющей»); в начале любого дела.", en: "When to recite: in every unit of the obligatory and voluntary prayer; in illness (the hadith call it a cure); at the start of any undertaking." },
      source: { ru: "Коран, 1:5–7", en: "Quran 1:5–7" },
      ref: { sura: 1, ayahFrom: 5, ayahTo: 7 },
      sync: [
        { text: "إِيَّاكَ", trans: { ru: "Тебе одному", en: "You alone" }, start: 0.42, end: 1.44 },
        { text: "نَعْبُدُ", trans: { ru: "мы поклоняемся", en: "we worship" }, start: 1.44, end: 2.48 },
        { text: "وَإِيَّاكَ", trans: { ru: "и у Тебя одного", en: "and You alone" }, start: 2.48, end: 3.99 },
        { text: "نَسْتَعِينُ", trans: { ru: "мы просим помощи", en: "we ask for help" }, start: 3.99, end: 5.54 },
        { text: "۝ ٥", trans: { ru: "аят 5", en: "ayah 5" }, start: 6.67, end: 7.59, isVerseEnd: true },
        { text: "اهْدِنَا", trans: { ru: "веди нас", en: "guide us" }, start: 6.67, end: 7.59 },
        { text: "الصِّرَاطَ", trans: { ru: "путём", en: "to the path" }, start: 7.59, end: 8.33 },
        { text: "الْمُسْتَقِيمَ", trans: { ru: "прямым", en: "the straight" }, start: 8.44, end: 9.47 },
        { text: "۝ ٦", trans: { ru: "аят 6", en: "ayah 6" }, start: 11.42, end: 12.61, isVerseEnd: true },
        { text: "صِرَاطَ", trans: { ru: "путём", en: "the path" }, start: 11.42, end: 12.61 },
        { text: "الَّذِينَ", trans: { ru: "тех, кого", en: "of those whom" }, start: 12.61, end: 13.53 },
        { text: "أَنْعَمْتَ", trans: { ru: "Ты одарил милостью", en: "You have blessed" }, start: 13.53, end: 14.5 },
        { text: "عَلَيْهِمْ", trans: { ru: "их", en: "upon them" }, start: 14.5, end: 15.51 },
        { text: "غَيْرِ", trans: { ru: "не тех", en: "not of" }, start: 16.19, end: 17.65 },
        { text: "الْمَغْضُوبِ", trans: { ru: "на кого пал гнев", en: "those who earned wrath" }, start: 17.65, end: 18.76 },
        { text: "عَلَيْهِمْ", trans: { ru: "на них", en: "upon them" }, start: 18.76, end: 19.82 },
        { text: "وَلَا", trans: { ru: "и не", en: "and not" }, start: 19.82, end: 20.33 },
        { text: "الضَّالِّينَ", trans: { ru: "заблудших", en: "of those who go astray" }, start: 20.33, end: 25.2 },
      ],
    },
  ],
};
