// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2004: ChapterData = {
  id: 2004,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ан-Ниса»", en: "Duas from Surah an-Nisa" },
  duas: [
    {
      id: "2004-27",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/27.mp3",
      title: { ru: "О покровителе и помощнике для угнетённых", en: "For a protector and a helper for the oppressed" },
      narration: { ru: "Мольба слабых и притесняемых", en: "The supplication of the weak and the persecuted" },
      fullTranslation: { ru: "Господь наш, выведи нас из этого селения, жители которого несправедливы. Даруй нам от Себя покровителя и даруй нам от Себя помощника.", en: "Our Lord, bring us out of this town whose people are unjust. Grant us from Yourself a protector, and grant us from Yourself a helper." },
      note: { ru: "Когда читают: в притеснении; при вынужденном переезде, бегстве, изгнании; когда некому заступиться.", en: "When to recite: under oppression; in a forced move, flight or exile; when there is no one to stand up for you." },
      source: { ru: "Коран, 4:75", en: "Quran 4:75" },
      ref: { sura: 4, ayahFrom: 75 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.18, end: 1.24 },
        { text: "أَخْرِجْنَا", trans: { ru: "выведи нас", en: "bring us out" }, start: 1.24, end: 3.48 },
        { text: "مِنْ", trans: { ru: "из", en: "of" }, start: 3.48, end: 4.2 },
        { text: "هَٰذِهِ", trans: { ru: "этого", en: "this" }, start: 4.2, end: 5.44 },
        { text: "الْقَرْيَةِ", trans: { ru: "селения", en: "town" }, start: 5.44, end: 6.86 },
        { text: "الظَّالِمِ", trans: { ru: "несправедливы", en: "are unjust" }, start: 6.86, end: 8.12 },
        { text: "أَهْلُهَا", trans: { ru: "жители которого", en: "whose people" }, start: 8.12, end: 9.42 },
        { text: "وَاجْعَل", trans: { ru: "и даруй", en: "and grant" }, start: 10.08, end: 11.68 },
        { text: "لَّنَا", trans: { ru: "нам", en: "us" }, start: 11.68, end: 12.74 },
        { text: "مِن", trans: { ru: "от", en: "from" }, start: 12.74, end: 13.08 },
        { text: "لَّدُنكَ", trans: { ru: "Себя", en: "Yourself" }, start: 13.08, end: 15.02 },
        { text: "وَلِيًّا", trans: { ru: "покровителя", en: "a protector" }, start: 15.02, end: 16.28 },
        { text: "وَاجْعَل", trans: { ru: "и даруй", en: "and grant" }, start: 16.28, end: 18.04 },
        { text: "لَّنَا", trans: { ru: "нам", en: "us" }, start: 18.04, end: 19.06 },
        { text: "مِن", trans: { ru: "от", en: "from" }, start: 19.06, end: 19.44 },
        { text: "لَّدُنكَ", trans: { ru: "Себя", en: "Yourself" }, start: 19.44, end: 21.38 },
        { text: "نَصِيرًا", trans: { ru: "помощника", en: "a helper" }, start: 21.38, end: 22.76 },
      ],
    },
  ],
};
