// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2004: ChapterData = {
  id: 2004,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ан-Ниса»", en: "Duas from Surah an-Nisa" },
  duas: [
    {
      id: "2004-27",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/27.mp3?v=68ec666d",
      title: { ru: "О покровителе и помощнике для угнетённых", en: "For a protector and a helper for the oppressed" },
      narration: { ru: "Мольба слабых и притесняемых", en: "The supplication of the weak and the persecuted" },
      fullTranslation: { ru: "Господь наш, выведи нас из этого селения, жители которого несправедливы. Даруй нам от Себя покровителя и даруй нам от Себя помощника.", en: "Our Lord, bring us out of this town whose people are unjust. Grant us from Yourself a protector, and grant us from Yourself a helper." },
      note: { ru: "Когда читают: в притеснении; при вынужденном переезде, бегстве, изгнании; когда некому заступиться.", en: "When to recite: under oppression; in a forced move, flight or exile; when there is no one to stand up for you." },
      source: { ru: "Коран, 4:75", en: "Quran 4:75" },
      ref: { sura: 4, ayahFrom: 75 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.27, end: 1.3 },
        { text: "أَخْرِجْنَا", trans: { ru: "выведи нас", en: "bring us out" }, start: 2.56, end: 3.93 },
        { text: "مِنْ", trans: { ru: "из", en: "of" }, start: 4.39, end: 4.73 },
        { text: "هَٰذِهِ", trans: { ru: "этого", en: "this" }, start: 5.07, end: 5.87 },
        { text: "الْقَرْيَةِ", trans: { ru: "селения", en: "town" }, start: 6.01, end: 6.87 },
        { text: "الظَّالِمِ", trans: { ru: "несправедливы", en: "are unjust" }, start: 7.4, end: 8.57 },
        { text: "أَهْلُهَا", trans: { ru: "жители которого", en: "whose people" }, start: 8.89, end: 9.74 },
        { text: "وَاجْعَل", trans: { ru: "и даруй", en: "and grant" }, start: 11.06, end: 11.89 },
        { text: "لَّنَا", trans: { ru: "нам", en: "us" }, start: 12.2, end: 12.52 },
        { text: "مِن", trans: { ru: "от", en: "from" }, start: 13.03, end: 13.24 },
        { text: "لَّدُنكَ", trans: { ru: "Себя", en: "Yourself" }, start: 13.55, end: 15.22 },
        { text: "وَلِيًّا", trans: { ru: "покровителя", en: "a protector" }, start: 15.53, end: 16.46 },
        { text: "وَاجْعَل", trans: { ru: "и даруй", en: "and grant" }, start: 17.61, end: 18.44 },
        { text: "لَّنَا", trans: { ru: "нам", en: "us" }, start: 18.75, end: 19.17 },
        { text: "مِن", trans: { ru: "от", en: "from" }, start: 19.69, end: 19.89 },
        { text: "لَّدُنكَ", trans: { ru: "Себя", en: "Yourself" }, start: 20.21, end: 21.87 },
        { text: "نَصِيرًا", trans: { ru: "помощника", en: "a helper" }, start: 22.08, end: 23.12 },
      ],
    },
  ],
};
