// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2006: ChapterData = {
  id: 2006,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Ан‘ам»", en: "Duas from Surah al-An'am" },
  duas: [
    {
      id: "2006-31",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/31.mp3?v=bf7995d0",
      title: { ru: "Обращение лица к Творцу", en: "Turning one's face to the Creator" },
      narration: { ru: "Ибрахим (мир ему) после отвержения идолов", en: "Ibrahim (peace be upon him) after rejecting the idols" },
      fullTranslation: { ru: "Я обратил своё лицо к Тому, Кто сотворил небеса и землю, будучи ханифом, и я не из многобожников.", en: "I have turned my face to Him who created the heavens and the earth, inclining to the truth, and I am not among those who associate partners with Him." },
      note: { ru: "Когда читают: входит в дуа «истифтах» — открывающую мольбу намаза.", en: "When to recite: part of the istiftah — the opening supplication of the prayer." },
      source: { ru: "Коран, 6:79", en: "Quran 6:79" },
      ref: { sura: 6, ayahFrom: 79 },
      sync: [
        { text: "إِنِّي", trans: { ru: "поистине, я", en: "indeed I" }, start: 0.79, end: 1.96 },
        { text: "وَجَّهْتُ", trans: { ru: "обратил", en: "have turned" }, start: 1.96, end: 3.59 },
        { text: "وَجْهِيَ", trans: { ru: "своё лицо", en: "my face" }, start: 3.71, end: 4.66 },
        { text: "لِلَّذِي", trans: { ru: "к Тому, Кто", en: "to Him who" }, start: 4.66, end: 6.07 },
        { text: "فَطَرَ", trans: { ru: "сотворил", en: "created" }, start: 6.18, end: 6.87 },
        { text: "السَّمَاوَاتِ", trans: { ru: "небеса", en: "the heavens" }, start: 6.87, end: 8.8 },
        { text: "وَالْأَرْضَ", trans: { ru: "и землю", en: "and the earth" }, start: 8.8, end: 9.98 },
        { text: "حَنِيفًا", trans: { ru: "будучи ханифом", en: "inclining to the truth" }, start: 9.98, end: 11.23 },
        { text: "وَمَا", trans: { ru: "и не", en: "and not" }, start: 11.23, end: 12.21 },
        { text: "أَنَا", trans: { ru: "я", en: "am I" }, start: 12.21, end: 13.52 },
        { text: "مِنَ", trans: { ru: "из", en: "among" }, start: 13.52, end: 13.99 },
        { text: "الْمُشْرِكِينَ", trans: { ru: "многобожников", en: "those who associate partners" }, start: 13.99, end: 16.49 },
      ],
    },
    {
      id: "2006-32",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/32.mp3?v=99cfa2a9",
      title: { ru: "Посвящение всей жизни", en: "Dedicating one's whole life" },
      fullTranslation: { ru: "Воистину, моя молитва и моё жертвоприношение, моя жизнь и моя смерть принадлежат Аллаху, Господу миров. Нет у Него сотоварищей. Это мне велено, и я — первый из покорившихся.", en: "Truly my prayer and my sacrifice, my living and my dying belong to Allah, Lord of the worlds. He has no partner. This I have been commanded, and I am the first of those who submit." },
      note: { ru: "Когда читают: в дуа истифтах; при жертвоприношении; как ежедневное обновление намерения.", en: "When to recite: in the istiftah; at a sacrifice; as a daily renewal of intention." },
      source: { ru: "Коран, 6:162–163", en: "Quran 6:162–163" },
      ref: { sura: 6, ayahFrom: 162, ayahTo: 163 },
      sync: [
        { text: "إِنَّ", trans: { ru: "поистине", en: "truly" }, start: 0.46, end: 0.75 },
        { text: "صَلَاتِي", trans: { ru: "моя молитва", en: "my prayer" }, start: 0.75, end: 2.65 },
        { text: "وَنُسُكِي", trans: { ru: "и моё жертвоприношение", en: "and my sacrifice" }, start: 2.65, end: 3.97 },
        { text: "وَمَحْيَايَ", trans: { ru: "и моя жизнь", en: "and my living" }, start: 3.97, end: 5.55 },
        { text: "وَمَمَاتِي", trans: { ru: "и моя смерть", en: "and my dying" }, start: 5.55, end: 6.91 },
        { text: "لِلَّهِ", trans: { ru: "принадлежат Аллаху", en: "are for Allah" }, start: 6.91, end: 8.21 },
        { text: "رَبِّ", trans: { ru: "Господу", en: "Lord of" }, start: 8.21, end: 9.1 },
        { text: "الْعَالَمِينَ", trans: { ru: "миров", en: "the worlds" }, start: 9.1, end: 10.6 },
        { text: "۝ ١٦٢", trans: { ru: "аят 162", en: "ayah 162" }, start: 12.44, end: 13.11, isVerseEnd: true },
        { text: "لَا", trans: { ru: "нет", en: "no" }, start: 12.44, end: 13.11 },
        { text: "شَرِيكَ", trans: { ru: "сотоварища", en: "partner" }, start: 13.11, end: 13.62 },
        { text: "لَهُ", trans: { ru: "у Него", en: "has He" }, start: 13.7, end: 14.12 },
        { text: "وَبِذَٰلِكَ", trans: { ru: "и этим", en: "and this" }, start: 15.86, end: 16.88 },
        { text: "أُمِرْتُ", trans: { ru: "мне велено", en: "I have been commanded" }, start: 16.96, end: 17.68 },
        { text: "وَأَنَا", trans: { ru: "и я", en: "and I am" }, start: 17.8, end: 18.55 },
        { text: "أَوَّلُ", trans: { ru: "первый из", en: "the first of" }, start: 18.66, end: 19.41 },
        { text: "الْمُسْلِمِينَ", trans: { ru: "покорившихся", en: "those who submit" }, start: 19.41, end: 21.22 },
      ],
    },
  ],
};
