// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2008: ChapterData = {
  id: 2008,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ат-Тауба»", en: "Duas from Surah at-Tawbah" },
  duas: [
    {
      id: "2008-42",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/42.mp3?v=8a3be81a",
      title: { ru: "«Достаточно мне Аллаха»", en: "\"Allah is sufficient for me\"" },
      narration: { ru: "Слова, которым Аллах научил Пророка ﷺ", en: "The words Allah taught His Prophet ﷺ" },
      fullTranslation: { ru: "Достаточно мне Аллаха, нет божества, кроме Него. На Него я уповаю, и Он — Господь великого Трона.", en: "Allah is sufficient for me; there is no god but He. Upon Him I rely, and He is the Lord of the Mighty Throne." },
      note: { ru: "Когда читают: по сунне — семь раз утром и семь раз вечером; когда отвернулись люди; при тревоге о будущем.", en: "When to recite: by the Sunnah, seven times in the morning and seven in the evening; when people have turned away; in anxiety about the future." },
      source: { ru: "Коран, 9:129", en: "Quran 9:129" },
      ref: { sura: 9, ayahFrom: 129 },
      sync: [
        { text: "حَسْبِيَ", trans: { ru: "достаточно мне", en: "sufficient for me" }, start: 0.3, end: 0.92 },
        { text: "اللَّهُ", trans: { ru: "Аллаха", en: "is Allah" }, start: 1.44, end: 1.74 },
        { text: "لَا", trans: { ru: "нет", en: "there is no" }, start: 2.26, end: 2.38 },
        { text: "إِلَٰهَ", trans: { ru: "божества", en: "god" }, start: 3.81, end: 4.53 },
        { text: "إِلَّا", trans: { ru: "кроме", en: "except" }, start: 4.63, end: 5.25 },
        { text: "هُوَ", trans: { ru: "Него", en: "Him" }, start: 5.56, end: 5.87 },
        { text: "عَلَيْهِ", trans: { ru: "на Него", en: "upon Him" }, start: 8.05, end: 9.3 },
        { text: "تَوَكَّلْتُ", trans: { ru: "я уповаю", en: "I rely" }, start: 9.55, end: 9.85 },
        { text: "وَهُوَ", trans: { ru: "и Он", en: "and He" }, start: 11.66, end: 12.19 },
        { text: "رَبُّ", trans: { ru: "Господь", en: "is the Lord of" }, start: 12.4, end: 12.82 },
        { text: "الْعَرْشِ", trans: { ru: "Трона", en: "the Throne" }, start: 13.03, end: 13.66 },
        { text: "الْعَظِيمِ", trans: { ru: "великого", en: "the Mighty" }, start: 13.97, end: 14.91 },
      ],
    },
  ],
};
