// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2016: ChapterData = {
  id: 2016,
  collection: 'quran',
  title: { ru: "Дуа из суры «Та Ха» (20)", en: "Duas from Surah Ta Ha (20)" },
  description: { ru: "3 мольбы из суры «Та Ха» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "3 supplications from Surah Ta Ha — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2016-64",
      title: { ru: "Дуа Мусы перед трудным разговором", en: "Musa's supplication before a hard conversation" },
      narration: { ru: "Муса (мир ему) перед фараоном", en: "Musa (peace be upon him) before Pharaoh" },
      fullTranslation: { ru: "Господи, раскрой мою грудь, облегчи моё дело, развяжи узел на моём языке, чтобы они поняли мою речь.", en: "My Lord, expand my breast, ease my task, and untie the knot from my tongue, so that they may understand my speech." },
      note: { ru: "Когда читают: перед выступлением, экзаменом, переговорами, трудным разговором; при страхе публичной речи; при заикании и волнении. Одна из самых практичных дуа Корана.", en: "When to recite: before a talk, an examination, negotiations, a difficult conversation; in fear of public speaking; with a stammer or nerves. One of the most practical supplications in the Qur'an." },
      source: { ru: "Коран, 20:25–28", en: "Quran 20:25–28" },
      ref: { sura: 20, ayahFrom: 25, ayahTo: 28 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "اشْرَحْ", trans: { ru: "раскрой", en: "expand" }, start: 0, end: 0 },
        { text: "لِي", trans: { ru: "мне", en: "for me" }, start: 0, end: 0 },
        { text: "صَدْرِي", trans: { ru: "мою грудь", en: "my breast" }, start: 0, end: 0 },
        { text: "۝ ٢٥", trans: { ru: "аят 25", en: "ayah 25" }, start: 0, end: 0, isVerseEnd: true },
        { text: "وَيَسِّرْ", trans: { ru: "и облегчи", en: "and ease" }, start: 0, end: 0 },
        { text: "لِي", trans: { ru: "мне", en: "for me" }, start: 0, end: 0 },
        { text: "أَمْرِي", trans: { ru: "моё дело", en: "my task" }, start: 0, end: 0 },
        { text: "۝ ٢٦", trans: { ru: "аят 26", en: "ayah 26" }, start: 0, end: 0, isVerseEnd: true },
        { text: "وَاحْلُلْ", trans: { ru: "и развяжи", en: "and untie" }, start: 0, end: 0 },
        { text: "عُقْدَةً", trans: { ru: "узел", en: "the knot" }, start: 0, end: 0 },
        { text: "مِّن", trans: { ru: "на", en: "from" }, start: 0, end: 0 },
        { text: "لِّسَانِي", trans: { ru: "моём языке", en: "my tongue" }, start: 0, end: 0 },
        { text: "۝ ٢٧", trans: { ru: "аят 27", en: "ayah 27" }, start: 0, end: 0, isVerseEnd: true },
        { text: "يَفْقَهُوا", trans: { ru: "чтобы они поняли", en: "that they may understand" }, start: 0, end: 0 },
        { text: "قَوْلِي", trans: { ru: "мою речь", en: "my speech" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2016-65",
      title: { ru: "О страхе перед несправедливым", en: "On fear of an unjust man" },
      narration: { ru: "Муса и Харун (мир им)", en: "Musa and Harun (peace be upon them)" },
      fullTranslation: { ru: "Господь наш, мы боимся, что он поспешит навредить нам или преступит границы.", en: "Our Lord, we fear that he will hasten to harm us or that he will transgress." },
      source: { ru: "Коран, 20:45–46", en: "Quran 20:45–46" },
      ref: { sura: 20, ayahFrom: 45, ayahTo: 46 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0, end: 0 },
        { text: "إِنَّنَا", trans: { ru: "поистине, мы", en: "indeed we" }, start: 0, end: 0 },
        { text: "نَخَافُ", trans: { ru: "боимся", en: "fear" }, start: 0, end: 0 },
        { text: "أَن", trans: { ru: "что", en: "that" }, start: 0, end: 0 },
        { text: "يَفْرُطَ", trans: { ru: "он поспешит навредить", en: "he will hasten to harm" }, start: 0, end: 0 },
        { text: "عَلَيْنَا", trans: { ru: "нам", en: "us" }, start: 0, end: 0 },
        { text: "أَوْ", trans: { ru: "или", en: "or" }, start: 0, end: 0 },
        { text: "أَن", trans: { ru: "что", en: "that" }, start: 0, end: 0 },
        { text: "يَطْغَىٰ", trans: { ru: "преступит границы", en: "he will transgress" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2016-66",
      title: { ru: "О приумножении знания", en: "For an increase in knowledge" },
      narration: { ru: "Единственная в Коране мольба о прибавлении", en: "The only supplication in the Qur'an asking for an increase" },
      fullTranslation: { ru: "Господи, приумножь мои знания!", en: "My Lord, increase me in knowledge!" },
      note: { ru: "Когда читают: перед учёбой, чтением, работой над сложной задачей; ежедневно.", en: "When to recite: before study, reading, work on a hard problem; every day." },
      source: { ru: "Коран, 20:114", en: "Quran 20:114" },
      ref: { sura: 20, ayahFrom: 114 },
      sync: [
        { text: "رَّبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "زِدْنِي", trans: { ru: "приумножь мне", en: "increase me" }, start: 0, end: 0 },
        { text: "عِلْمًا", trans: { ru: "знание", en: "in knowledge" }, start: 0, end: 0 },
      ],
    },
  ],
};
