// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2019: ChapterData = {
  id: 2019,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Фуркан»", en: "Duas from Surah al-Furqan" },
  duas: [
    {
      id: "2019-78",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/78.mp3?v=150db501",
      title: { ru: "Об избавлении от мучений Ада", en: "For deliverance from the punishment of Hell" },
      narration: { ru: "Мольба «рабов Милостивого»", en: "The supplication of the servants of the Most Merciful" },
      fullTranslation: { ru: "Господь наш, отврати от нас мучения Геенны, ведь мучения там — неотступны. Как скверно это местопребывание и обитель!", en: "Our Lord, turn away from us the punishment of Hell, for its punishment is relentless. Evil indeed it is as a settlement and a dwelling." },
      source: { ru: "Коран, 25:65–66", en: "Quran 25:65–66" },
      ref: { sura: 25, ayahFrom: 65, ayahTo: 66 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.28, end: 1.01 },
        { text: "اصْرِفْ", trans: { ru: "отврати", en: "turn away" }, start: 1.01, end: 1.43 },
        { text: "عَنَّا", trans: { ru: "от нас", en: "from us" }, start: 1.43, end: 2.3 },
        { text: "عَذَابَ", trans: { ru: "мучения", en: "the punishment of" }, start: 2.3, end: 3.62 },
        { text: "جَهَنَّمَ", trans: { ru: "Геенны", en: "Hell" }, start: 3.62, end: 4.49 },
        { text: "إِنَّ", trans: { ru: "поистине", en: "truly" }, start: 5.33, end: 5.5 },
        { text: "عَذَابَهَا", trans: { ru: "мучения её", en: "its punishment" }, start: 5.5, end: 6.7 },
        { text: "كَانَ", trans: { ru: "есть", en: "is" }, start: 6.7, end: 7.21 },
        { text: "غَرَامًا", trans: { ru: "неотступны", en: "relentless" }, start: 7.33, end: 8.71 },
        { text: "۝ ٦٥", trans: { ru: "аят 65", en: "ayah 65" }, start: 9.7, end: 10.53, isVerseEnd: true },
        { text: "إِنَّهَا", trans: { ru: "поистине, она", en: "truly it" }, start: 9.7, end: 10.53 },
        { text: "سَاءَتْ", trans: { ru: "скверна", en: "is evil" }, start: 10.53, end: 12.16 },
        { text: "مُسْتَقَرًّا", trans: { ru: "как местопребывание", en: "as a settlement" }, start: 12.31, end: 12.9 },
        { text: "وَمُقَامًا", trans: { ru: "и обитель", en: "and a dwelling" }, start: 13, end: 14.41 },
      ],
    },
    {
      id: "2019-79",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/79.mp3?v=787bc174",
      title: { ru: "О семье — «отраде очей»", en: "For a family — \"the comfort of the eyes\"" },
      narration: { ru: "Главная семейная дуа Корана", en: "The chief family supplication of the Qur'an" },
      fullTranslation: { ru: "Господь наш, даруй нам в наших супругах и потомках отраду очей и сделай нас образцом для богобоязненных.", en: "Our Lord, grant us in our spouses and offspring the comfort of our eyes, and make us an example for the God-fearing." },
      note: { ru: "Когда читают: о браке, супруге, детях; при желании создать семью; о согласии в доме.", en: "When to recite: for marriage, a spouse, children; when hoping to start a family; for peace in the home." },
      source: { ru: "Коран, 25:74", en: "Quran 25:74" },
      ref: { sura: 25, ayahFrom: 74 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.31, end: 1.26 },
        { text: "هَبْ", trans: { ru: "даруй", en: "grant" }, start: 1.26, end: 1.86 },
        { text: "لَنَا", trans: { ru: "нам", en: "us" }, start: 1.86, end: 2.46 },
        { text: "مِنْ", trans: { ru: "в", en: "in" }, start: 2.46, end: 2.99 },
        { text: "أَزْوَاجِنَا", trans: { ru: "наших супругах", en: "our spouses" }, start: 2.99, end: 4.62 },
        { text: "وَذُرِّيَّاتِنَا", trans: { ru: "и потомках", en: "and offspring" }, start: 4.62, end: 7.01 },
        { text: "قُرَّةَ", trans: { ru: "отраду", en: "the comfort" }, start: 7.15, end: 7.99 },
        { text: "أَعْيُنٍ", trans: { ru: "очей", en: "of our eyes" }, start: 8.04, end: 8.73 },
        { text: "وَاجْعَلْنَا", trans: { ru: "и сделай нас", en: "and make us" }, start: 8.73, end: 10.2 },
        { text: "لِلْمُتَّقِينَ", trans: { ru: "для богобоязненных", en: "for the God-fearing" }, start: 10.2, end: 11.71 },
        { text: "إِمَامًا", trans: { ru: "образцом", en: "an example" }, start: 12.28, end: 14.22 },
      ],
    },
  ],
};
