// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2021: ChapterData = {
  id: 2021,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ан-Намль» (27)", en: "Duas from Surah an-Naml (27)" },
  description: { ru: "2 мольбы из суры «Ан-Намль» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "2 supplications from Surah an-Naml — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2021-83",
      title: { ru: "Дуа Сулеймана о благодарности", en: "Sulayman's supplication of gratitude" },
      narration: { ru: "Сулейман (мир ему), услышав муравья", en: "Sulayman (peace be upon him), on hearing the ant" },
      fullTranslation: { ru: "Господи, внуши мне благодарность за милость, которую Ты оказал мне и моим родителям, и побуди меня совершать праведные дела, которыми Ты доволен. Введи меня по Своей милости в число Своих праведных рабов.", en: "My Lord, enable me to be grateful for the favour You bestowed on me and on my parents, and to do righteous deeds that please You. And admit me by Your mercy among Your righteous servants." },
      note: { ru: "Когда читают: при получении блага — успеха, дохода, выздоровления; чтобы благодарность не забылась.", en: "When to recite: on receiving a blessing — success, income, recovery; so that gratitude is not forgotten." },
      source: { ru: "Коран, 27:19", en: "Quran 27:19" },
      ref: { sura: 27, ayahFrom: 19 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "أَوْزِعْنِي", trans: { ru: "внуши мне", en: "enable me" }, start: 0, end: 0 },
        { text: "أَنْ", trans: { ru: "чтобы", en: "to" }, start: 0, end: 0 },
        { text: "أَشْكُرَ", trans: { ru: "я благодарил", en: "be grateful for" }, start: 0, end: 0 },
        { text: "نِعْمَتَكَ", trans: { ru: "за Твою милость", en: "Your favour" }, start: 0, end: 0 },
        { text: "الَّتِي", trans: { ru: "которую", en: "which" }, start: 0, end: 0 },
        { text: "أَنْعَمْتَ", trans: { ru: "Ты оказал", en: "You have bestowed" }, start: 0, end: 0 },
        { text: "عَلَيَّ", trans: { ru: "мне", en: "on me" }, start: 0, end: 0 },
        { text: "وَعَلَىٰ", trans: { ru: "и", en: "and on" }, start: 0, end: 0 },
        { text: "وَالِدَيَّ", trans: { ru: "моим родителям", en: "my parents" }, start: 0, end: 0 },
        { text: "وَأَنْ", trans: { ru: "и чтобы", en: "and to" }, start: 0, end: 0 },
        { text: "أَعْمَلَ", trans: { ru: "я совершал", en: "do" }, start: 0, end: 0 },
        { text: "صَالِحًا", trans: { ru: "праведное", en: "righteousness" }, start: 0, end: 0 },
        { text: "تَرْضَاهُ", trans: { ru: "которым Ты доволен", en: "that pleases You" }, start: 0, end: 0 },
        { text: "وَأَدْخِلْنِي", trans: { ru: "и введи меня", en: "and admit me" }, start: 0, end: 0 },
        { text: "بِرَحْمَتِكَ", trans: { ru: "по Своей милости", en: "by Your mercy" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "в число", en: "among" }, start: 0, end: 0 },
        { text: "عِبَادِكَ", trans: { ru: "Твоих рабов", en: "Your servants" }, start: 0, end: 0 },
        { text: "الصَّالِحِينَ", trans: { ru: "праведных", en: "the righteous" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2021-84",
      title: { ru: "Покаяние Билькис", en: "The repentance of Bilqis" },
      narration: { ru: "Царица Савская", en: "The Queen of Sheba" },
      fullTranslation: { ru: "Господи, я была несправедлива к себе, и я покорилась вместе с Сулейманом Аллаху, Господу миров.", en: "My Lord, I have wronged myself, and I submit with Sulayman to Allah, Lord of the worlds." },
      source: { ru: "Коран, 27:44", en: "Quran 27:44" },
      ref: { sura: 27, ayahFrom: 44 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "إِنِّي", trans: { ru: "поистине, я", en: "indeed I" }, start: 0, end: 0 },
        { text: "ظَلَمْتُ", trans: { ru: "поступила несправедливо", en: "have wronged" }, start: 0, end: 0 },
        { text: "نَفْسِي", trans: { ru: "с собою", en: "myself" }, start: 0, end: 0 },
        { text: "وَأَسْلَمْتُ", trans: { ru: "и я покорилась", en: "and I submit" }, start: 0, end: 0 },
        { text: "مَعَ", trans: { ru: "вместе с", en: "with" }, start: 0, end: 0 },
        { text: "سُلَيْمَانَ", trans: { ru: "Сулейманом", en: "Sulayman" }, start: 0, end: 0 },
        { text: "لِلَّهِ", trans: { ru: "Аллаху", en: "to Allah" }, start: 0, end: 0 },
        { text: "رَبِّ", trans: { ru: "Господу", en: "Lord of" }, start: 0, end: 0 },
        { text: "الْعَالَمِينَ", trans: { ru: "миров", en: "the worlds" }, start: 0, end: 0 },
      ],
    },
  ],
};
