// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2022: ChapterData = {
  id: 2022,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Касас» (28)", en: "Duas from Surah al-Qasas (28)" },
  description: { ru: "4 мольбы из суры «Аль-Касас» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "4 supplications from Surah al-Qasas — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2022-85",
      title: { ru: "Дуа Мусы после ошибки", en: "Musa's supplication after a mistake" },
      narration: { ru: "Муса (мир ему), нечаянно убив человека", en: "Musa (peace be upon him), having killed a man unintentionally" },
      fullTranslation: { ru: "Господи, я поступил несправедливо по отношению к себе. Прости же меня!", en: "My Lord, I have wronged myself. So forgive me!" },
      note: { ru: "Когда читают: сразу после совершённого проступка. Коран отмечает: Аллах простил его тотчас.", en: "When to recite: immediately after a wrong you have done. The Qur'an notes that Allah forgave him at once." },
      source: { ru: "Коран, 28:16", en: "Quran 28:16" },
      ref: { sura: 28, ayahFrom: 16 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "إِنِّي", trans: { ru: "поистине, я", en: "indeed I" }, start: 0, end: 0 },
        { text: "ظَلَمْتُ", trans: { ru: "поступил несправедливо", en: "have wronged" }, start: 0, end: 0 },
        { text: "نَفْسِي", trans: { ru: "с собою", en: "myself" }, start: 0, end: 0 },
        { text: "فَاغْفِرْ", trans: { ru: "прости же", en: "so forgive" }, start: 0, end: 0 },
        { text: "لِي", trans: { ru: "меня", en: "me" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2022-86",
      title: { ru: "Обет не помогать преступникам", en: "A vow never to aid the criminal" },
      narration: { ru: "Муса (мир ему)", en: "Musa (peace be upon him)" },
      fullTranslation: { ru: "Господи, за то, что Ты облагодетельствовал меня, я никогда не буду пособником преступников.", en: "My Lord, for the favour You have shown me, I will never be a supporter of the criminals." },
      note: { ru: "Когда читают: когда предлагают участие в нечестном деле.", en: "When to recite: when offered a part in a dishonest affair." },
      source: { ru: "Коран, 28:17", en: "Quran 28:17" },
      ref: { sura: 28, ayahFrom: 17 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "بِمَا", trans: { ru: "за то, что", en: "for what" }, start: 0, end: 0 },
        { text: "أَنْعَمْتَ", trans: { ru: "Ты облагодетельствовал", en: "You have favoured" }, start: 0, end: 0 },
        { text: "عَلَيَّ", trans: { ru: "меня", en: "me" }, start: 0, end: 0 },
        { text: "فَلَنْ", trans: { ru: "никогда не", en: "never will" }, start: 0, end: 0 },
        { text: "أَكُونَ", trans: { ru: "буду я", en: "I be" }, start: 0, end: 0 },
        { text: "ظَهِيرًا", trans: { ru: "пособником", en: "a supporter" }, start: 0, end: 0 },
        { text: "لِّلْمُجْرِمِينَ", trans: { ru: "преступникам", en: "of the criminals" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2022-87",
      title: { ru: "О спасении от несправедливых", en: "For deliverance from the unjust" },
      narration: { ru: "Муса (мир ему), покидая Египет", en: "Musa (peace be upon him) leaving Egypt" },
      fullTranslation: { ru: "Господи, спаси меня от людей несправедливых!", en: "My Lord, save me from the wrongdoing people!" },
      note: { ru: "Когда читают: при преследовании, угрозе, бегстве.", en: "When to recite: under pursuit, under threat, in flight." },
      source: { ru: "Коран, 28:21", en: "Quran 28:21" },
      ref: { sura: 28, ayahFrom: 21 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "نَجِّنِي", trans: { ru: "спаси меня", en: "save me" }, start: 0, end: 0 },
        { text: "مِنَ", trans: { ru: "от", en: "from" }, start: 0, end: 0 },
        { text: "الْقَوْمِ", trans: { ru: "народа", en: "the people" }, start: 0, end: 0 },
        { text: "الظَّالِمِينَ", trans: { ru: "несправедливого", en: "who are wrongdoers" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2022-88",
      title: { ru: "Дуа нищего и бездомного", en: "The supplication of the destitute and the homeless" },
      narration: { ru: "Муса (мир ему) в Мадьяне — без денег, дома и защиты", en: "Musa (peace be upon him) in Madyan — with no money, no home and no protection" },
      fullTranslation: { ru: "Господи, воистину, я нуждаюсь в любом благе, которое Ты ниспошлёшь мне.", en: "My Lord, truly I am in need of whatever good You send down to me." },
      note: { ru: "Когда читают: при бедности, безработице, отсутствии жилья, полной неопределённости. Ответом на эту мольбу стали кров, работа и брак.", en: "When to recite: in poverty, unemployment, homelessness, complete uncertainty. The answer to this supplication was shelter, work and marriage." },
      source: { ru: "Коран, 28:24", en: "Quran 28:24" },
      ref: { sura: 28, ayahFrom: 24 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "إِنِّي", trans: { ru: "поистине, я", en: "indeed I am" }, start: 0, end: 0 },
        { text: "لِمَا", trans: { ru: "в том, что", en: "of whatever" }, start: 0, end: 0 },
        { text: "أَنزَلْتَ", trans: { ru: "Ты ниспошлёшь", en: "You send down" }, start: 0, end: 0 },
        { text: "إِلَيَّ", trans: { ru: "мне", en: "to me" }, start: 0, end: 0 },
        { text: "مِنْ", trans: { ru: "из", en: "of" }, start: 0, end: 0 },
        { text: "خَيْرٍ", trans: { ru: "блага", en: "good" }, start: 0, end: 0 },
        { text: "فَقِيرٌ", trans: { ru: "нуждаюсь", en: "in need" }, start: 0, end: 0 },
      ],
    },
  ],
};
