// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2023: ChapterData = {
  id: 2023,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Анкабут»", en: "Duas from Surah al-'Ankabut" },
  duas: [
    {
      id: "2023-89",
      title: { ru: "О помощи против нечестивцев", en: "For help against the corrupt" },
      narration: { ru: "Лут (мир ему)", en: "Lut (peace be upon him)" },
      fullTranslation: { ru: "Господи, помоги мне против народа нечестивого!", en: "My Lord, help me against the corrupting people!" },
      source: { ru: "Коран, 29:30", en: "Quran 29:30" },
      ref: { sura: 29, ayahFrom: 30 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "انصُرْنِي", trans: { ru: "помоги мне", en: "help me" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "против", en: "against" }, start: 0, end: 0 },
        { text: "الْقَوْمِ", trans: { ru: "народа", en: "the people" }, start: 0, end: 0 },
        { text: "الْمُفْسِدِينَ", trans: { ru: "нечестивого", en: "who are corrupt" }, start: 0, end: 0 },
      ],
    },
  ],
};
