// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2024: ChapterData = {
  id: 2024,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ас-Саффат»", en: "Duas from Surah as-Saffat" },
  duas: [
    {
      id: "2024-90",
      title: { ru: "О праведном ребёнке", en: "For a righteous child" },
      narration: { ru: "Ибрахим (мир ему)", en: "Ibrahim (peace be upon him)" },
      fullTranslation: { ru: "Господи, даруй мне праведного потомка!", en: "My Lord, grant me a righteous child!" },
      note: { ru: "Когда читают: о ребёнке; краткая и точная формулировка — просят не просто ребёнка, а праведного.", en: "When to recite: for a child; short and exact — the request is not for a child as such but for a righteous one." },
      source: { ru: "Коран, 37:100", en: "Quran 37:100" },
      ref: { sura: 37, ayahFrom: 100 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "هَبْ", trans: { ru: "даруй", en: "grant" }, start: 0, end: 0 },
        { text: "لِي", trans: { ru: "мне", en: "me" }, start: 0, end: 0 },
        { text: "مِنَ", trans: { ru: "из числа", en: "from among" }, start: 0, end: 0 },
        { text: "الصَّالِحِينَ", trans: { ru: "праведных", en: "the righteous" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2024-91",
      title: { ru: "Завершающее прославление", en: "The closing glorification" },
      fullTranslation: { ru: "Пречист твой Господь, Господь могущества, и далёк от того, что Ему приписывают. Мир посланникам! Хвала Аллаху, Господу миров!", en: "Glory be to your Lord, the Lord of Might, above what they ascribe. Peace be upon the messengers! And praise be to Allah, Lord of the worlds!" },
      note: { ru: "Когда читают: по сунне — завершение собрания и завершение дуа.", en: "When to recite: by the Sunnah, the close of a gathering and the close of a supplication." },
      source: { ru: "Коран, 37:180–182", en: "Quran 37:180–182" },
      ref: { sura: 37, ayahFrom: 180, ayahTo: 182 },
      sync: [
        { text: "سُبْحَانَ", trans: { ru: "пречист", en: "glory be to" }, start: 0, end: 0 },
        { text: "رَبِّكَ", trans: { ru: "твой Господь", en: "your Lord" }, start: 0, end: 0 },
        { text: "رَبِّ", trans: { ru: "Господь", en: "the Lord of" }, start: 0, end: 0 },
        { text: "الْعِزَّةِ", trans: { ru: "могущества", en: "Might" }, start: 0, end: 0 },
        { text: "عَمَّا", trans: { ru: "от того, что", en: "above what" }, start: 0, end: 0 },
        { text: "يَصِفُونَ", trans: { ru: "они приписывают", en: "they ascribe" }, start: 0, end: 0 },
        { text: "۝ ١٨٠", trans: { ru: "аят 180", en: "ayah 180" }, start: 0, end: 0, isVerseEnd: true },
        { text: "وَسَلَامٌ", trans: { ru: "и мир", en: "and peace" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "над", en: "be upon" }, start: 0, end: 0 },
        { text: "الْمُرْسَلِينَ", trans: { ru: "посланниками", en: "the messengers" }, start: 0, end: 0 },
        { text: "۝ ١٨١", trans: { ru: "аят 181", en: "ayah 181" }, start: 0, end: 0, isVerseEnd: true },
        { text: "وَالْحَمْدُ", trans: { ru: "и хвала", en: "and praise be" }, start: 0, end: 0 },
        { text: "لِلَّهِ", trans: { ru: "Аллаху", en: "to Allah" }, start: 0, end: 0 },
        { text: "رَبِّ", trans: { ru: "Господу", en: "Lord of" }, start: 0, end: 0 },
        { text: "الْعَالَمِينَ", trans: { ru: "миров", en: "the worlds" }, start: 0, end: 0 },
      ],
    },
  ],
};
