// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2025: ChapterData = {
  id: 2025,
  collection: 'quran',
  title: { ru: "Дуа из суры «Сад»", en: "Duas from Surah Sad" },
  duas: [
    {
      id: "2025-92",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/92.mp3",
      title: { ru: "Дуа Сулеймана о власти", en: "Sulayman's supplication for sovereignty" },
      narration: { ru: "Сулейман (мир ему)", en: "Sulayman (peace be upon him)" },
      fullTranslation: { ru: "Господи, прости меня и даруй мне власть, которая не будет подобать никому после меня. Воистину, Ты — Дарующий.", en: "My Lord, forgive me and grant me a kingdom that will not befit anyone after me. Truly You are the Bestower." },
      source: { ru: "Коран, 38:35", en: "Quran 38:35" },
      ref: { sura: 38, ayahFrom: 35 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 1.68, end: 2.34 },
        { text: "اغْفِرْ", trans: { ru: "прости", en: "forgive" }, start: 2.34, end: 3.02 },
        { text: "لِي", trans: { ru: "меня", en: "me" }, start: 3.02, end: 3.36 },
        { text: "وَهَبْ", trans: { ru: "и даруй", en: "and grant" }, start: 3.36, end: 4.3 },
        { text: "لِي", trans: { ru: "мне", en: "me" }, start: 4.3, end: 4.7 },
        { text: "مُلْكًا", trans: { ru: "власть", en: "a kingdom" }, start: 4.7, end: 5.82 },
        { text: "لَّا", trans: { ru: "не", en: "not" }, start: 5.82, end: 6.18 },
        { text: "يَنبَغِي", trans: { ru: "будет подобать", en: "will befit" }, start: 6.18, end: 8.02 },
        { text: "لِأَحَدٍ", trans: { ru: "никому", en: "anyone" }, start: 8.02, end: 9.14 },
        { text: "مِّن", trans: { ru: "с", en: "from" }, start: 9.14, end: 9.96 },
        { text: "بَعْدِي", trans: { ru: "после меня", en: "after me" }, start: 9.96, end: 12.02 },
        { text: "إِنَّكَ", trans: { ru: "поистине, Ты", en: "indeed You" }, start: 13.89, end: 15.29 },
        { text: "أَنتَ", trans: { ru: "Ты", en: "You are" }, start: 15.29, end: 16.69 },
        { text: "الْوَهَّابُ", trans: { ru: "Дарующий", en: "the Bestower" }, start: 16.69, end: 18.47 },
      ],
    },
    {
      id: "2025-93",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/93.mp3",
      title: { ru: "Дуа Айюба о вреде от шайтана", en: "Ayyub's supplication about the harm of Satan" },
      narration: { ru: "Айюб (мир ему)", en: "Ayyub (peace be upon him)" },
      fullTranslation: { ru: "Воистину, шайтан коснулся меня утомлением и мучением.", en: "Truly Satan has touched me with weariness and torment." },
      note: { ru: "Когда читают: при истощении, упадке сил, депрессивном состоянии, ощущении вреда извне.", en: "When to recite: in exhaustion, loss of strength, low spirits, the sense of harm coming from outside." },
      source: { ru: "Коран, 38:41", en: "Quran 38:41" },
      ref: { sura: 38, ayahFrom: 41 },
      sync: [
        { text: "أَنِّي", trans: { ru: "поистине, меня", en: "indeed me" }, start: 0.21, end: 1.95 },
        { text: "مَسَّنِيَ", trans: { ru: "коснулся", en: "has touched" }, start: 1.95, end: 2.91 },
        { text: "الشَّيْطَانُ", trans: { ru: "шайтан", en: "Satan" }, start: 2.91, end: 4.39 },
        { text: "بِنُصْبٍ", trans: { ru: "утомлением", en: "with weariness" }, start: 4.39, end: 5.21 },
        { text: "وَعَذَابٍ", trans: { ru: "и мучением", en: "and torment" }, start: 5.21, end: 8.43 },
      ],
    },
  ],
};
