// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2026: ChapterData = {
  id: 2026,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аз-Зумар» (39)", en: "Duas from Surah az-Zumar (39)" },
  description: { ru: "1 мольба из суры «Аз-Зумар» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "1 supplication from Surah az-Zumar — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2026-94",
      title: { ru: "О разрешении разногласий", en: "For the settling of disagreements" },
      fullTranslation: { ru: "О Аллах, Творец небес и земли, Знающий сокровенное и явное! Ты рассудишь Своих рабов в том, в чём они расходились во мнениях.", en: "O Allah, Creator of the heavens and the earth, Knower of the unseen and the seen! You will judge between Your servants concerning that in which they differed." },
      note: { ru: "Когда читают: по сунне — с этих слов Пророк ﷺ начинал ночную молитву тахаджуд; при разногласиях и расколе.", en: "When to recite: by the Sunnah, the Prophet ﷺ opened the night prayer, tahajjud, with these words; in disagreement and division." },
      source: { ru: "Коран, 39:46", en: "Quran 39:46" },
      ref: { sura: 39, ayahFrom: 46 },
      sync: [
        { text: "اللَّهُمَّ", trans: { ru: "о Аллах", en: "O Allah" }, start: 0, end: 0 },
        { text: "فَاطِرَ", trans: { ru: "Творец", en: "Creator of" }, start: 0, end: 0 },
        { text: "السَّمَاوَاتِ", trans: { ru: "небес", en: "the heavens" }, start: 0, end: 0 },
        { text: "وَالْأَرْضِ", trans: { ru: "и земли", en: "and the earth" }, start: 0, end: 0 },
        { text: "عَالِمَ", trans: { ru: "Знающий", en: "Knower of" }, start: 0, end: 0 },
        { text: "الْغَيْبِ", trans: { ru: "сокровенное", en: "the unseen" }, start: 0, end: 0 },
        { text: "وَالشَّهَادَةِ", trans: { ru: "и явное", en: "and the seen" }, start: 0, end: 0 },
        { text: "أَنتَ", trans: { ru: "Ты", en: "You" }, start: 0, end: 0 },
        { text: "تَحْكُمُ", trans: { ru: "рассудишь", en: "will judge" }, start: 0, end: 0 },
        { text: "بَيْنَ", trans: { ru: "между", en: "between" }, start: 0, end: 0 },
        { text: "عِبَادِكَ", trans: { ru: "Своими рабами", en: "Your servants" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "в", en: "concerning" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "том, в чём", en: "that in which" }, start: 0, end: 0 },
        { text: "كَانُوا", trans: { ru: "они", en: "they" }, start: 0, end: 0 },
        { text: "فِيهِ", trans: { ru: "в том", en: "in it" }, start: 0, end: 0 },
        { text: "يَخْتَلِفُونَ", trans: { ru: "расходились", en: "differed" }, start: 0, end: 0 },
      ],
    },
  ],
};
