// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2026: ChapterData = {
  id: 2026,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аз-Зумар»", en: "Duas from Surah az-Zumar" },
  duas: [
    {
      id: "2026-94",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/94.mp3?v=2e8c7ec0",
      title: { ru: "О разрешении разногласий", en: "For the settling of disagreements" },
      fullTranslation: { ru: "О Аллах, Творец небес и земли, Знающий сокровенное и явное! Ты рассудишь Своих рабов в том, в чём они расходились во мнениях.", en: "O Allah, Creator of the heavens and the earth, Knower of the unseen and the seen! You will judge between Your servants concerning that in which they differed." },
      note: { ru: "Когда читают: по сунне — с этих слов Пророк ﷺ начинал ночную молитву тахаджуд; при разногласиях и расколе.", en: "When to recite: by the Sunnah, the Prophet ﷺ opened the night prayer, tahajjud, with these words; in disagreement and division." },
      source: { ru: "Коран, 39:46", en: "Quran 39:46" },
      ref: { sura: 39, ayahFrom: 46 },
      sync: [
        { text: "اللَّهُمَّ", trans: { ru: "о Аллах", en: "O Allah" }, start: 0.26, end: 1.35 },
        { text: "فَاطِرَ", trans: { ru: "Творец", en: "Creator of" }, start: 1.35, end: 2.75 },
        { text: "السَّمَاوَاتِ", trans: { ru: "небес", en: "the heavens" }, start: 2.75, end: 4.15 },
        { text: "وَالْأَرْضِ", trans: { ru: "и земли", en: "and the earth" }, start: 4.15, end: 5.19 },
        { text: "عَالِمَ", trans: { ru: "Знающий", en: "Knower of" }, start: 6.51, end: 7.1 },
        { text: "الْغَيْبِ", trans: { ru: "сокровенное", en: "the unseen" }, start: 7.1, end: 8.1 },
        { text: "وَالشَّهَادَةِ", trans: { ru: "и явное", en: "and the seen" }, start: 8.1, end: 9.42 },
        { text: "أَنتَ", trans: { ru: "Ты", en: "You" }, start: 11.02, end: 11.61 },
        { text: "تَحْكُمُ", trans: { ru: "рассудишь", en: "will judge" }, start: 11.69, end: 12.15 },
        { text: "بَيْنَ", trans: { ru: "между", en: "between" }, start: 12.26, end: 12.68 },
        { text: "عِبَادِكَ", trans: { ru: "Своими рабами", en: "Your servants" }, start: 12.68, end: 13.86 },
        { text: "فِي", trans: { ru: "в", en: "concerning" }, start: 13.86, end: 14.2 },
        { text: "مَا", trans: { ru: "том, в чём", en: "that in which" }, start: 14.2, end: 14.54 },
        { text: "كَانُوا", trans: { ru: "они", en: "they" }, start: 14.54, end: 15.54 },
        { text: "فِيهِ", trans: { ru: "в том", en: "in it" }, start: 15.54, end: 16.2 },
        { text: "يَخْتَلِفُونَ", trans: { ru: "расходились", en: "differed" }, start: 16.2, end: 18.14 },
      ],
    },
  ],
};
