// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2028: ChapterData = {
  id: 2028,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аз-Зухруф»", en: "Duas from Surah az-Zukhruf" },
  duas: [
    {
      id: "2028-97",
      title: { ru: "Дуа в пути (транспорт)", en: "The supplication for travel" },
      fullTranslation: { ru: "Пречист Тот, Кто подчинил нам это, ведь сами мы не смогли бы этого достичь. Воистину, мы вернёмся к нашему Господу.", en: "Glory be to Him who has subjected this to us, for we could never have achieved it ourselves. And truly to our Lord we shall return." },
      note: { ru: "Когда читают: садясь в машину, самолёт, поезд — стандартная дуа путешествия по сунне.", en: "When to recite: on getting into a car, a plane, a train — the standard supplication for travel in the Sunnah." },
      source: { ru: "Коран, 43:13–14", en: "Quran 43:13–14" },
      ref: { sura: 43, ayahFrom: 13, ayahTo: 14 },
      sync: [
        { text: "سُبْحَانَ", trans: { ru: "пречист", en: "glory be to" }, start: 0, end: 0 },
        { text: "الَّذِي", trans: { ru: "Тот, Кто", en: "Him who" }, start: 0, end: 0 },
        { text: "سَخَّرَ", trans: { ru: "подчинил", en: "has subjected" }, start: 0, end: 0 },
        { text: "لَنَا", trans: { ru: "нам", en: "to us" }, start: 0, end: 0 },
        { text: "هَٰذَا", trans: { ru: "это", en: "this" }, start: 0, end: 0 },
        { text: "وَمَا", trans: { ru: "и не", en: "and not" }, start: 0, end: 0 },
        { text: "كُنَّا", trans: { ru: "были мы", en: "were we" }, start: 0, end: 0 },
        { text: "لَهُ", trans: { ru: "для него", en: "for it" }, start: 0, end: 0 },
        { text: "مُقْرِنِينَ", trans: { ru: "способны", en: "capable" }, start: 0, end: 0 },
        { text: "۝ ١٣", trans: { ru: "аят 13", en: "ayah 13" }, start: 0, end: 0, isVerseEnd: true },
        { text: "وَإِنَّا", trans: { ru: "и поистине, мы", en: "and indeed we" }, start: 0, end: 0 },
        { text: "إِلَىٰ", trans: { ru: "к", en: "to" }, start: 0, end: 0 },
        { text: "رَبِّنَا", trans: { ru: "нашему Господу", en: "our Lord" }, start: 0, end: 0 },
        { text: "لَمُنقَلِبُونَ", trans: { ru: "непременно вернёмся", en: "will surely return" }, start: 0, end: 0 },
      ],
    },
  ],
};
