// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2029: ChapterData = {
  id: 2029,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ад-Духан»", en: "Duas from Surah ad-Dukhan" },
  duas: [
    {
      id: "2029-98",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/98.mp3?v=6c16c610",
      title: { ru: "Об избавлении от бедствия", en: "For relief from a calamity" },
      fullTranslation: { ru: "Господь наш, избавь нас от мучений, ведь мы уверовали!", en: "Our Lord, remove the punishment from us, for we are believers!" },
      note: { ru: "Когда читают: при общем бедствии — эпидемии, голоде, войне, засухе.", en: "When to recite: in a shared calamity — an epidemic, famine, war, drought." },
      source: { ru: "Коран, 44:12", en: "Quran 44:12" },
      ref: { sura: 44, ayahFrom: 12 },
      sync: [
        { text: "رَّبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.3, end: 1.23 },
        { text: "اكْشِفْ", trans: { ru: "избавь", en: "remove" }, start: 1.37, end: 2.1 },
        { text: "عَنَّا", trans: { ru: "от нас", en: "from us" }, start: 2.1, end: 3.39 },
        { text: "الْعَذَابَ", trans: { ru: "мучения", en: "the punishment" }, start: 3.39, end: 4.95 },
        { text: "إِنَّا", trans: { ru: "поистине, мы", en: "indeed we" }, start: 4.95, end: 6.26 },
        { text: "مُؤْمِنُونَ", trans: { ru: "верующие", en: "are believers" }, start: 6.36, end: 8.52 },
      ],
    },
  ],
};
