// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2029: ChapterData = {
  id: 2029,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ад-Духан» (44)", en: "Duas from Surah ad-Dukhan (44)" },
  description: { ru: "1 мольба из суры «Ад-Духан» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "1 supplication from Surah ad-Dukhan — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2029-98",
      title: { ru: "Об избавлении от бедствия", en: "For relief from a calamity" },
      fullTranslation: { ru: "Господь наш, избавь нас от мучений, ведь мы уверовали!", en: "Our Lord, remove the punishment from us, for we are believers!" },
      note: { ru: "Когда читают: при общем бедствии — эпидемии, голоде, войне, засухе.", en: "When to recite: in a shared calamity — an epidemic, famine, war, drought." },
      source: { ru: "Коран, 44:12", en: "Quran 44:12" },
      ref: { sura: 44, ayahFrom: 12 },
      sync: [
        { text: "رَّبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0, end: 0 },
        { text: "اكْشِفْ", trans: { ru: "избавь", en: "remove" }, start: 0, end: 0 },
        { text: "عَنَّا", trans: { ru: "от нас", en: "from us" }, start: 0, end: 0 },
        { text: "الْعَذَابَ", trans: { ru: "мучения", en: "the punishment" }, start: 0, end: 0 },
        { text: "إِنَّا", trans: { ru: "поистине, мы", en: "indeed we" }, start: 0, end: 0 },
        { text: "مُؤْمِنُونَ", trans: { ru: "верующие", en: "are believers" }, start: 0, end: 0 },
      ],
    },
  ],
};
