// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2030: ChapterData = {
  id: 2030,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Ахкаф»", en: "Duas from Surah al-Ahqaf" },
  duas: [
    {
      id: "2030-99",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/99.mp3",
      title: { ru: "Дуа зрелости — в сорок лет", en: "The supplication of maturity — at forty" },
      narration: { ru: "Мольба человека, достигшего сорока лет", en: "The supplication of one who has reached forty years" },
      fullTranslation: { ru: "Господи, внуши мне благодарность за милость, которой Ты одарил меня и моих родителей, и побуди меня совершать праведные дела, которыми Ты доволен. Сделай моё потомство праведным. Я раскаиваюсь перед Тобой, и я — из числа мусульман.", en: "My Lord, enable me to be grateful for the favour You have bestowed on me and on my parents, and to do righteous deeds that please You. And make my offspring righteous. I turn to You in repentance, and I am among those who submit." },
      note: { ru: "Когда читают: о детях и родителях одновременно; в зрелом возрасте; при подведении итогов.", en: "When to recite: for children and parents at once; in middle age; when taking stock." },
      source: { ru: "Коран, 46:15", en: "Quran 46:15" },
      ref: { sura: 46, ayahFrom: 15 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0.27, end: 0.76 },
        { text: "أَوْزِعْنِي", trans: { ru: "внуши мне", en: "enable me" }, start: 0.76, end: 1.58 },
        { text: "أَنْ", trans: { ru: "чтобы", en: "to" }, start: 1.69, end: 2.97 },
        { text: "أَشْكُرَ", trans: { ru: "я благодарил", en: "be grateful for" }, start: 3.06, end: 3.79 },
        { text: "نِعْمَتَكَ", trans: { ru: "за Твою милость", en: "Your favour" }, start: 3.87, end: 4.82 },
        { text: "الَّتِي", trans: { ru: "которою", en: "which" }, start: 4.9, end: 5.6 },
        { text: "أَنْعَمْتَ", trans: { ru: "Ты одарил", en: "You have bestowed" }, start: 5.7, end: 7.76 },
        { text: "عَلَيَّ", trans: { ru: "меня", en: "on me" }, start: 7.86, end: 8.08 },
        { text: "وَعَلَىٰ", trans: { ru: "и", en: "and on" }, start: 8.08, end: 9.22 },
        { text: "وَالِدَيَّ", trans: { ru: "моих родителей", en: "my parents" }, start: 9.22, end: 10.32 },
        { text: "وَأَنْ", trans: { ru: "и чтобы", en: "and to" }, start: 10.32, end: 11.51 },
        { text: "أَعْمَلَ", trans: { ru: "я совершал", en: "do" }, start: 11.61, end: 12.24 },
        { text: "صَالِحًا", trans: { ru: "праведное", en: "righteousness" }, start: 12.24, end: 13.14 },
        { text: "تَرْضَاهُ", trans: { ru: "которым Ты доволен", en: "that pleases You" }, start: 13.14, end: 15.2 },
        { text: "وَأَصْلِحْ", trans: { ru: "и сделай праведным", en: "and make righteous" }, start: 17.31, end: 18.25 },
        { text: "لِي", trans: { ru: "для меня", en: "for me" }, start: 18.25, end: 18.61 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 18.61, end: 19.03 },
        { text: "ذُرِّيَّتِي", trans: { ru: "моём потомстве", en: "my offspring" }, start: 19.03, end: 20.59 },
        { text: "إِنِّي", trans: { ru: "поистине, я", en: "indeed I" }, start: 22.08, end: 22.9 },
        { text: "تُبْتُ", trans: { ru: "раскаиваюсь", en: "turn in repentance" }, start: 22.9, end: 23.78 },
        { text: "إِلَيْكَ", trans: { ru: "перед Тобой", en: "to You" }, start: 23.78, end: 24.48 },
        { text: "وَإِنِّي", trans: { ru: "и поистине, я", en: "and indeed I am" }, start: 24.58, end: 26.02 },
        { text: "مِنَ", trans: { ru: "из числа", en: "among" }, start: 26.02, end: 26.54 },
        { text: "الْمُسْلِمِينَ", trans: { ru: "мусульман", en: "those who submit" }, start: 26.54, end: 28.82 },
      ],
    },
  ],
};
