// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2030: ChapterData = {
  id: 2030,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Ахкаф» (46)", en: "Duas from Surah al-Ahqaf (46)" },
  description: { ru: "1 мольба из суры «Аль-Ахкаф» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "1 supplication from Surah al-Ahqaf — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2030-99",
      title: { ru: "Дуа зрелости — в сорок лет", en: "The supplication of maturity — at forty" },
      narration: { ru: "Мольба человека, достигшего сорока лет", en: "The supplication of one who has reached forty years" },
      fullTranslation: { ru: "Господи, внуши мне благодарность за милость, которой Ты одарил меня и моих родителей, и побуди меня совершать праведные дела, которыми Ты доволен. Сделай моё потомство праведным. Я раскаиваюсь перед Тобой, и я — из числа мусульман.", en: "My Lord, enable me to be grateful for the favour You have bestowed on me and on my parents, and to do righteous deeds that please You. And make my offspring righteous. I turn to You in repentance, and I am among those who submit." },
      note: { ru: "Когда читают: о детях и родителях одновременно; в зрелом возрасте; при подведении итогов.", en: "When to recite: for children and parents at once; in middle age; when taking stock." },
      source: { ru: "Коран, 46:15", en: "Quran 46:15" },
      ref: { sura: 46, ayahFrom: 15 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "أَوْزِعْنِي", trans: { ru: "внуши мне", en: "enable me" }, start: 0, end: 0 },
        { text: "أَنْ", trans: { ru: "чтобы", en: "to" }, start: 0, end: 0 },
        { text: "أَشْكُرَ", trans: { ru: "я благодарил", en: "be grateful for" }, start: 0, end: 0 },
        { text: "نِعْمَتَكَ", trans: { ru: "за Твою милость", en: "Your favour" }, start: 0, end: 0 },
        { text: "الَّتِي", trans: { ru: "которою", en: "which" }, start: 0, end: 0 },
        { text: "أَنْعَمْتَ", trans: { ru: "Ты одарил", en: "You have bestowed" }, start: 0, end: 0 },
        { text: "عَلَيَّ", trans: { ru: "меня", en: "on me" }, start: 0, end: 0 },
        { text: "وَعَلَىٰ", trans: { ru: "и", en: "and on" }, start: 0, end: 0 },
        { text: "وَالِدَيَّ", trans: { ru: "моих родителей", en: "my parents" }, start: 0, end: 0 },
        { text: "وَأَنْ", trans: { ru: "и чтобы", en: "and to" }, start: 0, end: 0 },
        { text: "أَعْمَلَ", trans: { ru: "я совершал", en: "do" }, start: 0, end: 0 },
        { text: "صَالِحًا", trans: { ru: "праведное", en: "righteousness" }, start: 0, end: 0 },
        { text: "تَرْضَاهُ", trans: { ru: "которым Ты доволен", en: "that pleases You" }, start: 0, end: 0 },
        { text: "وَأَصْلِحْ", trans: { ru: "и сделай праведным", en: "and make righteous" }, start: 0, end: 0 },
        { text: "لِي", trans: { ru: "для меня", en: "for me" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 0, end: 0 },
        { text: "ذُرِّيَّتِي", trans: { ru: "моём потомстве", en: "my offspring" }, start: 0, end: 0 },
        { text: "إِنِّي", trans: { ru: "поистине, я", en: "indeed I" }, start: 0, end: 0 },
        { text: "تُبْتُ", trans: { ru: "раскаиваюсь", en: "turn in repentance" }, start: 0, end: 0 },
        { text: "إِلَيْكَ", trans: { ru: "перед Тобой", en: "to You" }, start: 0, end: 0 },
        { text: "وَإِنِّي", trans: { ru: "и поистине, я", en: "and indeed I am" }, start: 0, end: 0 },
        { text: "مِنَ", trans: { ru: "из числа", en: "among" }, start: 0, end: 0 },
        { text: "الْمُسْلِمِينَ", trans: { ru: "мусульман", en: "those who submit" }, start: 0, end: 0 },
      ],
    },
  ],
};
