// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2031: ChapterData = {
  id: 2031,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Камар» (54)", en: "Duas from Surah al-Qamar (54)" },
  description: { ru: "1 мольба из суры «Аль-Камар» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "1 supplication from Surah al-Qamar — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2031-100",
      title: { ru: "Мольба побеждённого", en: "The supplication of the overcome" },
      narration: { ru: "Нух (мир ему)", en: "Nuh (peace be upon him)" },
      fullTranslation: { ru: "Я побеждён — так помоги же мне!", en: "I am overcome, so help me!" },
      note: { ru: "Когда читают: когда силы кончились и защитить себя нечем.", en: "When to recite: when your strength is gone and you have nothing left to defend yourself with." },
      source: { ru: "Коран, 54:10", en: "Quran 54:10" },
      ref: { sura: 54, ayahFrom: 10 },
      sync: [
        { text: "أَنِّي", trans: { ru: "поистине, я", en: "indeed I am" }, start: 0, end: 0 },
        { text: "مَغْلُوبٌ", trans: { ru: "побеждён", en: "overcome" }, start: 0, end: 0 },
        { text: "فَانتَصِرْ", trans: { ru: "так помоги же", en: "so help" }, start: 0, end: 0 },
      ],
    },
  ],
};
