// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2032: ChapterData = {
  id: 2032,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Хашр»", en: "Duas from Surah al-Hashr" },
  duas: [
    {
      id: "2032-101",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/101.mp3?v=8b3eb47b",
      title: { ru: "О чистоте сердца по отношению к верующим", en: "For a heart clean towards the believers" },
      narration: { ru: "Мольба пришедших после первых мусульман", en: "The supplication of those who came after the first Muslims" },
      fullTranslation: { ru: "Господь наш, прости нас и наших братьев, которые уверовали раньше нас. Не насаждай в наших сердцах злобы к тем, кто уверовал. Господь наш, воистину, Ты — Сострадательный, Милосердный.", en: "Our Lord, forgive us and our brothers who preceded us in faith. And put no rancour in our hearts towards those who have believed. Our Lord, truly You are Kind, Merciful." },
      note: { ru: "Когда читают: при обиде на другого мусульманина; при расколе в общине; о предыдущих поколениях.", en: "When to recite: when hurt by another Muslim; in a split within the community; for the generations before you." },
      source: { ru: "Коран, 59:10", en: "Quran 59:10" },
      ref: { sura: 59, ayahFrom: 10 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.28, end: 0.93 },
        { text: "اغْفِرْ", trans: { ru: "прости", en: "forgive" }, start: 0.93, end: 1.47 },
        { text: "لَنَا", trans: { ru: "нас", en: "us" }, start: 1.47, end: 2.05 },
        { text: "وَلِإِخْوَانِنَا", trans: { ru: "и наших братьев", en: "and our brothers" }, start: 2.05, end: 3.72 },
        { text: "الَّذِينَ", trans: { ru: "которые", en: "who" }, start: 3.72, end: 4.59 },
        { text: "سَبَقُونَا", trans: { ru: "опередили нас", en: "preceded us" }, start: 4.59, end: 5.65 },
        { text: "بِالْإِيمَانِ", trans: { ru: "в вере", en: "in faith" }, start: 5.76, end: 8.5 },
        { text: "وَلَا", trans: { ru: "и не", en: "and do not" }, start: 9.67, end: 10.48 },
        { text: "تَجْعَلْ", trans: { ru: "насаждай", en: "put" }, start: 10.48, end: 11.38 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 11.38, end: 11.7 },
        { text: "قُلُوبِنَا", trans: { ru: "наших сердцах", en: "our hearts" }, start: 11.7, end: 12.9 },
        { text: "غِلًّا", trans: { ru: "злобы", en: "rancour" }, start: 12.9, end: 13.75 },
        { text: "لِّلَّذِينَ", trans: { ru: "к тем, кто", en: "towards those who" }, start: 13.75, end: 15 },
        { text: "آمَنُوا", trans: { ru: "уверовал", en: "have believed" }, start: 15, end: 15.94 },
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "our Lord" }, start: 16.96, end: 18.21 },
        { text: "إِنَّكَ", trans: { ru: "поистине, Ты", en: "indeed You" }, start: 18.21, end: 19.47 },
        { text: "رَءُوفٌ", trans: { ru: "Сострадательный", en: "are Kind" }, start: 19.47, end: 20.27 },
        { text: "رَّحِيمٌ", trans: { ru: "Милосердный", en: "Merciful" }, start: 20.27, end: 21.44 },
      ],
    },
  ],
};
