// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2033: ChapterData = {
  id: 2033,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Мумтахана»", en: "Duas from Surah al-Mumtahanah" },
  duas: [
    {
      id: "2033-102",
      title: { ru: "Упование и обращение", en: "Reliance and turning to Allah" },
      fullTranslation: { ru: "Господь наш, на Тебя мы уповаем, к Тебе обращаемся, и к Тебе — возвращение.", en: "Our Lord, upon You we rely, to You we turn, and to You is the return." },
      source: { ru: "Коран, 60:4", en: "Quran 60:4" },
      ref: { sura: 60, ayahFrom: 4 },
      sync: [
        { text: "رَّبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0, end: 0 },
        { text: "عَلَيْكَ", trans: { ru: "на Тебя", en: "upon You" }, start: 0, end: 0 },
        { text: "تَوَكَّلْنَا", trans: { ru: "мы уповаем", en: "we rely" }, start: 0, end: 0 },
        { text: "وَإِلَيْكَ", trans: { ru: "и к Тебе", en: "and to You" }, start: 0, end: 0 },
        { text: "أَنَبْنَا", trans: { ru: "мы обращаемся", en: "we turn" }, start: 0, end: 0 },
        { text: "وَإِلَيْكَ", trans: { ru: "и к Тебе", en: "and to You" }, start: 0, end: 0 },
        { text: "الْمَصِيرُ", trans: { ru: "возвращение", en: "is the return" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2033-103",
      title: { ru: "«Не делай нас искушением для неверующих»", en: "\"Do not make us a trial for the disbelievers\"" },
      fullTranslation: { ru: "Господь наш, не делай нас искушением для неверующих и прости нас, Господь наш. Воистину, Ты — Могущественный, Мудрый.", en: "Our Lord, do not make us a trial for those who disbelieve, and forgive us, our Lord. Truly You are the Exalted in Might, the All-Wise." },
      source: { ru: "Коран, 60:5", en: "Quran 60:5" },
      ref: { sura: 60, ayahFrom: 5 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0, end: 0 },
        { text: "لَا", trans: { ru: "не", en: "do not" }, start: 0, end: 0 },
        { text: "تَجْعَلْنَا", trans: { ru: "делай нас", en: "make us" }, start: 0, end: 0 },
        { text: "فِتْنَةً", trans: { ru: "искушением", en: "a trial" }, start: 0, end: 0 },
        { text: "لِّلَّذِينَ", trans: { ru: "для тех, кто", en: "for those who" }, start: 0, end: 0 },
        { text: "كَفَرُوا", trans: { ru: "не уверовал", en: "disbelieve" }, start: 0, end: 0 },
        { text: "وَاغْفِرْ", trans: { ru: "и прости", en: "and forgive" }, start: 0, end: 0 },
        { text: "لَنَا", trans: { ru: "нас", en: "us" }, start: 0, end: 0 },
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "our Lord" }, start: 0, end: 0 },
        { text: "إِنَّكَ", trans: { ru: "поистине, Ты", en: "indeed You" }, start: 0, end: 0 },
        { text: "أَنتَ", trans: { ru: "Ты", en: "You are" }, start: 0, end: 0 },
        { text: "الْعَزِيزُ", trans: { ru: "Могущественный", en: "the Exalted in Might" }, start: 0, end: 0 },
        { text: "الْحَكِيمُ", trans: { ru: "Мудрый", en: "the All-Wise" }, start: 0, end: 0 },
      ],
    },
  ],
};
