// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2033: ChapterData = {
  id: 2033,
  collection: 'quran',
  title: { ru: "Дуа из суры «Аль-Мумтахана»", en: "Duas from Surah al-Mumtahanah" },
  duas: [
    {
      id: "2033-102",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/102.mp3?v=9123ee09",
      title: { ru: "Упование и обращение", en: "Reliance and turning to Allah" },
      fullTranslation: { ru: "Господь наш, на Тебя мы уповаем, к Тебе обращаемся, и к Тебе — возвращение.", en: "Our Lord, upon You we rely, to You we turn, and to You is the return." },
      source: { ru: "Коран, 60:4", en: "Quran 60:4" },
      ref: { sura: 60, ayahFrom: 4 },
      sync: [
        { text: "رَّبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.26, end: 0.86 },
        { text: "عَلَيْكَ", trans: { ru: "на Тебя", en: "upon You" }, start: 0.86, end: 1.61 },
        { text: "تَوَكَّلْنَا", trans: { ru: "мы уповаем", en: "we rely" }, start: 1.61, end: 2.59 },
        { text: "وَإِلَيْكَ", trans: { ru: "и к Тебе", en: "and to You" }, start: 2.87, end: 4.87 },
        { text: "أَنَبْنَا", trans: { ru: "мы обращаемся", en: "we turn" }, start: 4.92, end: 5.9 },
        { text: "وَإِلَيْكَ", trans: { ru: "и к Тебе", en: "and to You" }, start: 5.9, end: 7.69 },
        { text: "الْمَصِيرُ", trans: { ru: "возвращение", en: "is the return" }, start: 7.69, end: 9.72 },
      ],
    },
    {
      id: "2033-103",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/103.mp3?v=5b548f1b",
      title: { ru: "«Не делай нас искушением для неверующих»", en: "\"Do not make us a trial for the disbelievers\"" },
      fullTranslation: { ru: "Господь наш, не делай нас искушением для неверующих и прости нас, Господь наш. Воистину, Ты — Могущественный, Мудрый.", en: "Our Lord, do not make us a trial for those who disbelieve, and forgive us, our Lord. Truly You are the Exalted in Might, the All-Wise." },
      source: { ru: "Коран, 60:5", en: "Quran 60:5" },
      ref: { sura: 60, ayahFrom: 5 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.38, end: 1.15 },
        { text: "لَا", trans: { ru: "не", en: "do not" }, start: 1.15, end: 1.58 },
        { text: "تَجْعَلْنَا", trans: { ru: "делай нас", en: "make us" }, start: 1.58, end: 2.72 },
        { text: "فِتْنَةً", trans: { ru: "искушением", en: "a trial" }, start: 2.72, end: 3.67 },
        { text: "لِّلَّذِينَ", trans: { ru: "для тех, кто", en: "for those who" }, start: 3.79, end: 5.46 },
        { text: "كَفَرُوا", trans: { ru: "не уверовал", en: "disbelieve" }, start: 5.46, end: 6.56 },
        { text: "وَاغْفِرْ", trans: { ru: "и прости", en: "and forgive" }, start: 6.56, end: 7.71 },
        { text: "لَنَا", trans: { ru: "нас", en: "us" }, start: 7.71, end: 8.43 },
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "our Lord" }, start: 8.43, end: 9.87 },
        { text: "إِنَّكَ", trans: { ru: "поистине, Ты", en: "indeed You" }, start: 10.94, end: 12.78 },
        { text: "أَنتَ", trans: { ru: "Ты", en: "You are" }, start: 12.78, end: 14.68 },
        { text: "الْعَزِيزُ", trans: { ru: "Могущественный", en: "the Exalted in Might" }, start: 14.68, end: 16 },
        { text: "الْحَكِيمُ", trans: { ru: "Мудрый", en: "the All-Wise" }, start: 16, end: 17.81 },
      ],
    },
  ],
};
