// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2034: ChapterData = {
  id: 2034,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ат-Тахрим» (66)", en: "Duas from Surah at-Tahrim (66)" },
  description: { ru: "2 мольбы из суры «Ат-Тахрим» — арабский текст, пословный перевод и смысл каждой дуа с указанием аята.", en: "2 supplications from Surah at-Tahrim — Arabic text, word-by-word translation and the meaning of each dua with its ayah reference." },
  duas: [
    {
      id: "2034-104",
      title: { ru: "О свете в День воскресения", en: "For light on the Day of Resurrection" },
      fullTranslation: { ru: "Господь наш, дай нам света сполна и прости нас. Воистину, Ты способен на всякую вещь.", en: "Our Lord, perfect our light for us and forgive us. Truly You are able to do all things." },
      source: { ru: "Коран, 66:8", en: "Quran 66:8" },
      ref: { sura: 66, ayahFrom: 8 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0, end: 0 },
        { text: "أَتْمِمْ", trans: { ru: "дай сполна", en: "perfect" }, start: 0, end: 0 },
        { text: "لَنَا", trans: { ru: "нам", en: "for us" }, start: 0, end: 0 },
        { text: "نُورَنَا", trans: { ru: "наш свет", en: "our light" }, start: 0, end: 0 },
        { text: "وَاغْفِرْ", trans: { ru: "и прости", en: "and forgive" }, start: 0, end: 0 },
        { text: "لَنَا", trans: { ru: "нас", en: "us" }, start: 0, end: 0 },
        { text: "إِنَّكَ", trans: { ru: "поистине, Ты", en: "indeed You" }, start: 0, end: 0 },
        { text: "عَلَىٰ", trans: { ru: "над", en: "are over" }, start: 0, end: 0 },
        { text: "كُلِّ", trans: { ru: "всякой", en: "all" }, start: 0, end: 0 },
        { text: "شَيْءٍ", trans: { ru: "вещью", en: "things" }, start: 0, end: 0 },
        { text: "قَدِيرٌ", trans: { ru: "властен", en: "able" }, start: 0, end: 0 },
      ],
    },
    {
      id: "2034-105",
      title: { ru: "Дуа Асии — о доме в Раю", en: "The supplication of Asiyah — for a house in Paradise" },
      narration: { ru: "Жена фараона", en: "The wife of Pharaoh" },
      fullTranslation: { ru: "Господи, построй для меня дом у Себя в Раю, спаси меня от фараона и его деяний и спаси меня от людей несправедливых.", en: "My Lord, build for me a house near You in Paradise, save me from Pharaoh and his deeds, and save me from the wrongdoing people." },
      note: { ru: "Когда читают: в тяжёлом браке или семье; при насилии дома; когда невозможно уйти физически. Асия просила о соседстве прежде дома — «‘индака» («у Тебя») стоит раньше «бейтан» («дом»).", en: "When to recite: in a hard marriage or family; under violence at home; when leaving is not physically possible. Asiyah asked for the nearness before the house — 'indaka (near You) comes before baytan (a house)." },
      source: { ru: "Коран, 66:11", en: "Quran 66:11" },
      ref: { sura: 66, ayahFrom: 11 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0, end: 0 },
        { text: "ابْنِ", trans: { ru: "построй", en: "build" }, start: 0, end: 0 },
        { text: "لِي", trans: { ru: "для меня", en: "for me" }, start: 0, end: 0 },
        { text: "عِندَكَ", trans: { ru: "у Себя", en: "near You" }, start: 0, end: 0 },
        { text: "بَيْتًا", trans: { ru: "дом", en: "a house" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 0, end: 0 },
        { text: "الْجَنَّةِ", trans: { ru: "Раю", en: "Paradise" }, start: 0, end: 0 },
        { text: "وَنَجِّنِي", trans: { ru: "и спаси меня", en: "and save me" }, start: 0, end: 0 },
        { text: "مِن", trans: { ru: "от", en: "from" }, start: 0, end: 0 },
        { text: "فِرْعَوْنَ", trans: { ru: "фараона", en: "Pharaoh" }, start: 0, end: 0 },
        { text: "وَعَمَلِهِ", trans: { ru: "и его деяний", en: "and his deeds" }, start: 0, end: 0 },
        { text: "وَنَجِّنِي", trans: { ru: "и спаси меня", en: "and save me" }, start: 0, end: 0 },
        { text: "مِنَ", trans: { ru: "от", en: "from" }, start: 0, end: 0 },
        { text: "الْقَوْمِ", trans: { ru: "народа", en: "the people" }, start: 0, end: 0 },
        { text: "الظَّالِمِينَ", trans: { ru: "несправедливого", en: "who are wrongdoers" }, start: 0, end: 0 },
      ],
    },
  ],
};
