// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2034: ChapterData = {
  id: 2034,
  collection: 'quran',
  title: { ru: "Дуа из суры «Ат-Тахрим»", en: "Duas from Surah at-Tahrim" },
  duas: [
    {
      id: "2034-104",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/104.mp3",
      title: { ru: "О свете в День воскресения", en: "For light on the Day of Resurrection" },
      fullTranslation: { ru: "Господь наш, дай нам света сполна и прости нас. Воистину, Ты способен на всякую вещь.", en: "Our Lord, perfect our light for us and forgive us. Truly You are able to do all things." },
      source: { ru: "Коран, 66:8", en: "Quran 66:8" },
      ref: { sura: 66, ayahFrom: 8 },
      sync: [
        { text: "رَبَّنَا", trans: { ru: "Господь наш", en: "Our Lord" }, start: 0.3, end: 1.1 },
        { text: "أَتْمِمْ", trans: { ru: "дай сполна", en: "perfect" }, start: 2.6, end: 3.5 },
        { text: "لَنَا", trans: { ru: "нам", en: "for us" }, start: 3.6, end: 4 },
        { text: "نُورَنَا", trans: { ru: "наш свет", en: "our light" }, start: 4.4, end: 5.3 },
        { text: "وَاغْفِرْ", trans: { ru: "и прости", en: "and forgive" }, start: 5.7, end: 6.5 },
        { text: "لَنَا", trans: { ru: "нас", en: "us" }, start: 6.7, end: 7.67 },
        { text: "إِنَّكَ", trans: { ru: "поистине, Ты", en: "indeed You" }, start: 8.55, end: 10.1 },
        { text: "عَلَىٰ", trans: { ru: "над", en: "are over" }, start: 10.19, end: 11.2 },
        { text: "كُلِّ", trans: { ru: "всякой", en: "all" }, start: 11.32, end: 11.8 },
        { text: "شَيْءٍ", trans: { ru: "вещью", en: "things" }, start: 12, end: 12.6 },
        { text: "قَدِيرٌ", trans: { ru: "властен", en: "able" }, start: 13.6, end: 15.69 },
      ],
    },
    {
      id: "2034-105",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/105.mp3",
      title: { ru: "Дуа Асии — о доме в Раю", en: "The supplication of Asiyah — for a house in Paradise" },
      narration: { ru: "Жена фараона", en: "The wife of Pharaoh" },
      fullTranslation: { ru: "Господи, построй для меня дом у Себя в Раю, спаси меня от фараона и его деяний и спаси меня от людей несправедливых.", en: "My Lord, build for me a house near You in Paradise, save me from Pharaoh and his deeds, and save me from the wrongdoing people." },
      note: { ru: "Когда читают: в тяжёлом браке или семье; при насилии дома; когда невозможно уйти физически. Асия просила о соседстве прежде дома — «‘индака» («у Тебя») стоит раньше «бейтан» («дом»).", en: "When to recite: in a hard marriage or family; under violence at home; when leaving is not physically possible. Asiyah asked for the nearness before the house — 'indaka (near You) comes before baytan (a house)." },
      source: { ru: "Коран, 66:11", en: "Quran 66:11" },
      ref: { sura: 66, ayahFrom: 11 },
      sync: [
        { text: "رَبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0.27, end: 0.68 },
        { text: "ابْنِ", trans: { ru: "построй", en: "build" }, start: 0.68, end: 1.14 },
        { text: "لِي", trans: { ru: "для меня", en: "for me" }, start: 1.14, end: 1.58 },
        { text: "عِندَكَ", trans: { ru: "у Себя", en: "near You" }, start: 1.58, end: 3.12 },
        { text: "بَيْتًا", trans: { ru: "дом", en: "a house" }, start: 3.12, end: 3.68 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 3.8, end: 4.63 },
        { text: "الْجَنَّةِ", trans: { ru: "Раю", en: "Paradise" }, start: 4.74, end: 6.16 },
        { text: "وَنَجِّنِي", trans: { ru: "и спаси меня", en: "and save me" }, start: 6.16, end: 7.38 },
        { text: "مِن", trans: { ru: "от", en: "from" }, start: 7.38, end: 7.86 },
        { text: "فِرْعَوْنَ", trans: { ru: "фараона", en: "Pharaoh" }, start: 7.86, end: 9.68 },
        { text: "وَعَمَلِهِ", trans: { ru: "и его деяний", en: "and his deeds" }, start: 9.68, end: 10.8 },
        { text: "وَنَجِّنِي", trans: { ru: "и спаси меня", en: "and save me" }, start: 12.03, end: 12.8 },
        { text: "مِنَ", trans: { ru: "от", en: "from" }, start: 12.8, end: 13.32 },
        { text: "الْقَوْمِ", trans: { ru: "народа", en: "the people" }, start: 13.32, end: 14.36 },
        { text: "الظَّالِمِينَ", trans: { ru: "несправедливого", en: "who are wrongdoers" }, start: 14.36, end: 17.26 },
      ],
    },
  ],
};
