// Generated by scripts/build-quran-chapters.mjs from duas-iz-korana.md.
// Edit the reference document or data/quran/{en,glosses}.json, then re-run it.

import { ChapterData } from '../../types';

export const QURAN_CHAPTER_2035: ChapterData = {
  id: 2035,
  collection: 'quran',
  title: { ru: "Дуа из суры «Нух»", en: "Duas from Surah Nuh" },
  duas: [
    {
      id: "2035-106",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/106.mp3?v=8f6c8a9c",
      title: { ru: "Мольба Нуха против упорствующих", en: "Nuh's supplication against those who persisted" },
      fullTranslation: { ru: "Господи, не оставь на земле ни одного неверующего жителя!", en: "My Lord, do not leave upon the earth a single dweller from among the disbelievers!" },
      source: { ru: "Коран, 71:26", en: "Quran 71:26" },
      ref: { sura: 71, ayahFrom: 26 },
      sync: [
        { text: "رَّبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0.28, end: 0.78 },
        { text: "لَا", trans: { ru: "не", en: "do not" }, start: 0.78, end: 0.92 },
        { text: "تَذَرْ", trans: { ru: "оставь", en: "leave" }, start: 0.92, end: 1.64 },
        { text: "عَلَى", trans: { ru: "на", en: "upon" }, start: 1.64, end: 1.93 },
        { text: "الْأَرْضِ", trans: { ru: "земле", en: "the earth" }, start: 1.93, end: 2.73 },
        { text: "مِنَ", trans: { ru: "из", en: "from among" }, start: 2.86, end: 4.08 },
        { text: "الْكَافِرِينَ", trans: { ru: "неверующих", en: "the disbelievers" }, start: 4.18, end: 5.73 },
        { text: "دَيَّارًا", trans: { ru: "ни одного жителя", en: "a single dweller" }, start: 5.73, end: 6.91 },
      ],
    },
    {
      id: "2035-107",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/dua-from-quran/107.mp3?v=a439e1ca",
      title: { ru: "О прощении для родителей, дома и всех верующих", en: "Forgiveness for parents, household and all the believers" },
      narration: { ru: "Нух (мир ему)", en: "Nuh (peace be upon him)" },
      fullTranslation: { ru: "Господи, прости меня, моих родителей и тех, кто вошёл в мой дом верующим, а также верующих мужчин и женщин.", en: "My Lord, forgive me, my parents, whoever enters my house as a believer, and the believing men and women." },
      note: { ru: "Когда читают: о родителях, домочадцах, гостях и всей общине сразу.", en: "When to recite: for parents, household, guests and the whole community at once." },
      source: { ru: "Коран, 71:28", en: "Quran 71:28" },
      ref: { sura: 71, ayahFrom: 28 },
      sync: [
        { text: "رَّبِّ", trans: { ru: "Господи", en: "My Lord" }, start: 0.29, end: 0.8 },
        { text: "اغْفِرْ", trans: { ru: "прости", en: "forgive" }, start: 0.8, end: 1.42 },
        { text: "لِي", trans: { ru: "меня", en: "me" }, start: 1.42, end: 1.73 },
        { text: "وَلِوَالِدَيَّ", trans: { ru: "и моих родителей", en: "and my parents" }, start: 1.73, end: 3.09 },
        { text: "وَلِمَن", trans: { ru: "и того, кто", en: "and whoever" }, start: 3.09, end: 4.16 },
        { text: "دَخَلَ", trans: { ru: "вошёл", en: "enters" }, start: 4.16, end: 5.16 },
        { text: "بَيْتِيَ", trans: { ru: "в мой дом", en: "my house" }, start: 5.16, end: 5.96 },
        { text: "مُؤْمِنًا", trans: { ru: "верующим", en: "as a believer" }, start: 5.96, end: 6.9 },
        { text: "وَلِلْمُؤْمِنِينَ", trans: { ru: "и верующих мужчин", en: "and the believing men" }, start: 7.03, end: 8.92 },
        { text: "وَالْمُؤْمِنَاتِ", trans: { ru: "и верующих женщин", en: "and the believing women" }, start: 9.04, end: 10.63 },
      ],
    },
  ],
};
