// Generated by scripts/build-quran-chapters.mjs. Do not edit by hand.
//
// Quranic supplications, arranged in mushaf order and grouped by sura, as
// laid out in duas-iz-korana.md. Chapter ids live in the 2000+ range so they
// never collide with the 1..134 ids of the Sunnah collection.

import type { ChapterData } from '../../types';
import { QURAN_CHAPTER_2001 } from './2001-surah-001-al-fatihah';
import { QURAN_CHAPTER_2002 } from './2002-surah-002-al-baqarah';
import { QURAN_CHAPTER_2003 } from './2003-surah-003-al-imran';
import { QURAN_CHAPTER_2004 } from './2004-surah-004-an-nisa';
import { QURAN_CHAPTER_2005 } from './2005-surah-005-al-maidah';
import { QURAN_CHAPTER_2006 } from './2006-surah-006-al-anam';
import { QURAN_CHAPTER_2007 } from './2007-surah-007-al-araf';
import { QURAN_CHAPTER_2008 } from './2008-surah-009-at-tawbah';
import { QURAN_CHAPTER_2009 } from './2009-surah-010-yunus';
import { QURAN_CHAPTER_2010 } from './2010-surah-011-hud';
import { QURAN_CHAPTER_2011 } from './2011-surah-012-yusuf';
import { QURAN_CHAPTER_2012 } from './2012-surah-014-ibrahim';
import { QURAN_CHAPTER_2013 } from './2013-surah-017-al-isra';
import { QURAN_CHAPTER_2014 } from './2014-surah-018-al-kahf';
import { QURAN_CHAPTER_2015 } from './2015-surah-019-maryam';
import { QURAN_CHAPTER_2016 } from './2016-surah-020-ta-ha';
import { QURAN_CHAPTER_2017 } from './2017-surah-021-al-anbiya';
import { QURAN_CHAPTER_2018 } from './2018-surah-023-al-muminun';
import { QURAN_CHAPTER_2019 } from './2019-surah-025-al-furqan';
import { QURAN_CHAPTER_2020 } from './2020-surah-026-ash-shuara';
import { QURAN_CHAPTER_2021 } from './2021-surah-027-an-naml';
import { QURAN_CHAPTER_2022 } from './2022-surah-028-al-qasas';
import { QURAN_CHAPTER_2023 } from './2023-surah-029-al-ankabut';
import { QURAN_CHAPTER_2024 } from './2024-surah-037-as-saffat';
import { QURAN_CHAPTER_2025 } from './2025-surah-038-sad';
import { QURAN_CHAPTER_2026 } from './2026-surah-039-az-zumar';
import { QURAN_CHAPTER_2027 } from './2027-surah-040-ghafir';
import { QURAN_CHAPTER_2028 } from './2028-surah-043-az-zukhruf';
import { QURAN_CHAPTER_2029 } from './2029-surah-044-ad-dukhan';
import { QURAN_CHAPTER_2030 } from './2030-surah-046-al-ahqaf';
import { QURAN_CHAPTER_2031 } from './2031-surah-054-al-qamar';
import { QURAN_CHAPTER_2032 } from './2032-surah-059-al-hashr';
import { QURAN_CHAPTER_2033 } from './2033-surah-060-al-mumtahanah';
import { QURAN_CHAPTER_2034 } from './2034-surah-066-at-tahrim';
import { QURAN_CHAPTER_2035 } from './2035-surah-071-nuh';
import { QURAN_CHAPTER_2036 } from './2036-surah-113-al-falaq-and-an-nas';

export const QURAN_DATABASE: ChapterData[] = [
  QURAN_CHAPTER_2001,
  QURAN_CHAPTER_2002,
  QURAN_CHAPTER_2003,
  QURAN_CHAPTER_2004,
  QURAN_CHAPTER_2005,
  QURAN_CHAPTER_2006,
  QURAN_CHAPTER_2007,
  QURAN_CHAPTER_2008,
  QURAN_CHAPTER_2009,
  QURAN_CHAPTER_2010,
  QURAN_CHAPTER_2011,
  QURAN_CHAPTER_2012,
  QURAN_CHAPTER_2013,
  QURAN_CHAPTER_2014,
  QURAN_CHAPTER_2015,
  QURAN_CHAPTER_2016,
  QURAN_CHAPTER_2017,
  QURAN_CHAPTER_2018,
  QURAN_CHAPTER_2019,
  QURAN_CHAPTER_2020,
  QURAN_CHAPTER_2021,
  QURAN_CHAPTER_2022,
  QURAN_CHAPTER_2023,
  QURAN_CHAPTER_2024,
  QURAN_CHAPTER_2025,
  QURAN_CHAPTER_2026,
  QURAN_CHAPTER_2027,
  QURAN_CHAPTER_2028,
  QURAN_CHAPTER_2029,
  QURAN_CHAPTER_2030,
  QURAN_CHAPTER_2031,
  QURAN_CHAPTER_2032,
  QURAN_CHAPTER_2033,
  QURAN_CHAPTER_2034,
  QURAN_CHAPTER_2035,
  QURAN_CHAPTER_2036,
];
