// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/01.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3001: ChapterData = {
  id: 3001,
  collection: 'nawawi',
  title: { ru: "Дела оцениваются по намерениям", en: "Actions are judged by intentions" },
  duas: [
    {
      id: "3001-1",
      narration: { ru: "Со слов повелителя правоверных Абу Хафса Умара ибн аль-Хаттаба, да будет доволен им Аллах, передаётся, что он сказал: «Я слышал, как посланник Аллаха ﷺ сказал…»", en: "On the authority of the Commander of the Faithful, Abu Hafs Umar ibn al-Khattab, may Allah be pleased with him, who said: “I heard the Messenger of Allah ﷺ say…”" },
      fullTranslation: { ru: "Поистине, дела оцениваются только по намерениям, и, поистине, каждому человеку достанется лишь то, что он намеревался обрести. Тот, чья хиджра была к Аллаху и Его посланнику, переселился к Аллаху и Его посланнику, а тот, чья хиджра была ради мирского, которое он хотел обрести, или ради женщины, на которой хотел жениться, переселился к тому, ради чего переселялся.", en: "Actions are judged only by intentions, and every man shall have only what he intended. So whoever emigrated to Allah and His Messenger, his emigration was to Allah and His Messenger; and whoever emigrated for some worldly gain he would attain, or a woman he would marry, his emigration was to that for which he emigrated." },
      note: { ru: "Этим хадисом аль-Бухари открывает свой сборник «ас-Сахих».", en: "Al-Bukhari opens his collection as-Sahih with this hadith." },
      source: { ru: "аль-Бухари 1; Муслим 1907", en: "al-Bukhari 1; Muslim 1907" },
      sync: [
        { text: "إِنَّمَا", trans: { ru: "поистине", en: "verily" }, start: 0, end: 0 },
        { text: "الْأَعْمَالُ", trans: { ru: "дела", en: "actions are" }, start: 0, end: 0 },
        { text: "بِالنِّيَّاتِ", trans: { ru: "по намерениям", en: "by intentions" }, start: 0, end: 0 },
        { text: "وَإِنَّمَا", trans: { ru: "и поистине", en: "and verily" }, start: 0, end: 0 },
        { text: "لِكُلِّ", trans: { ru: "каждому", en: "for every" }, start: 0, end: 0 },
        { text: "امْرِئٍ", trans: { ru: "человеку", en: "man" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "то, что", en: "what" }, start: 0, end: 0 },
        { text: "نَوَى", trans: { ru: "он намеревался", en: "he intended" }, start: 0, end: 0 },
        { text: "فَمَنْ", trans: { ru: "и тот, чья", en: "so whoever" }, start: 0, end: 0 },
        { text: "كَانَتْ", trans: { ru: "была", en: "was" }, start: 0, end: 0 },
        { text: "هِجْرَتُهُ", trans: { ru: "хиджра", en: "his emigration" }, start: 0, end: 0 },
        { text: "إِلَى", trans: { ru: "к", en: "to" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаху", en: "Allah" }, start: 0, end: 0 },
        { text: "وَرَسُولِهِ", trans: { ru: "и Его посланнику", en: "and His Messenger" }, start: 0, end: 0 },
        { text: "فَهِجْرَتُهُ", trans: { ru: "то его хиджра", en: "then his emigration" }, start: 0, end: 0 },
        { text: "إِلَى", trans: { ru: "к", en: "to" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаху", en: "Allah" }, start: 0, end: 0 },
        { text: "وَرَسُولِهِ", trans: { ru: "и Его посланнику", en: "and His Messenger" }, start: 0, end: 0 },
        { text: "وَمَنْ", trans: { ru: "а тот, чья", en: "and whoever" }, start: 0, end: 0 },
        { text: "كَانَتْ", trans: { ru: "была", en: "was" }, start: 0, end: 0 },
        { text: "هِجْرَتُهُ", trans: { ru: "хиджра", en: "his emigration" }, start: 0, end: 0 },
        { text: "لِدُنْيَا", trans: { ru: "ради мирского", en: "for worldly gain" }, start: 0, end: 0 },
        { text: "يُصِيبُهَا", trans: { ru: "которое он обретёт", en: "he would attain" }, start: 0, end: 0 },
        { text: "أَوِ", trans: { ru: "или", en: "or" }, start: 0, end: 0 },
        { text: "امْرَأَةٍ", trans: { ru: "женщины", en: "a woman" }, start: 0, end: 0 },
        { text: "يَنْكِحُهَا", trans: { ru: "на которой женится", en: "he would marry" }, start: 0, end: 0 },
        { text: "فَهِجْرَتُهُ", trans: { ru: "то его хиджра", en: "then his emigration" }, start: 0, end: 0 },
        { text: "إِلَى", trans: { ru: "к", en: "to" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "тому, ради чего", en: "that for which" }, start: 0, end: 0 },
        { text: "هَاجَرَ", trans: { ru: "он переселился", en: "he emigrated" }, start: 0, end: 0 },
        { text: "إِلَيْهِ", trans: { ru: "к нему", en: "towards it" }, start: 0, end: 0 },
      ],
    },
  ],
};
