// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/03.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3003: ChapterData = {
  id: 3003,
  collection: 'nawawi',
  title: { ru: "Ислам построен на пяти столпах", en: "Islam is built upon five pillars" },
  duas: [
    {
      id: "3003-1",
      narration: { ru: "Со слов Абу Абд ар-Рахмана Абдуллаха ибн Умара ибн аль-Хаттаба, да будет доволен Аллах ими обоими, передаётся, что он сказал: «Я слышал, как посланник Аллаха ﷺ сказал…»", en: "On the authority of Abu Abd ar-Rahman Abdullah ibn Umar ibn al-Khattab, may Allah be pleased with them both, who said: “I heard the Messenger of Allah ﷺ say…”" },
      fullTranslation: { ru: "Ислам построен на пяти столпах: свидетельстве о том, что нет божества, достойного поклонения, кроме Аллаха, и что Мухаммад — посланник Аллаха; совершении молитвы; выплате закята; хадже к Дому и посте в рамадан.", en: "Islam is built upon five: the testimony that there is no god but Allah and that Muhammad is the Messenger of Allah, the establishment of the prayer, the giving of zakat, the pilgrimage to the House, and the fast of Ramadan." },
      source: { ru: "аль-Бухари 8; Муслим 16", en: "al-Bukhari 8; Muslim 16" },
      sync: [
        { text: "بُنِيَ", trans: { ru: "построен", en: "is built" }, start: 0, end: 0 },
        { text: "الْإِسْلَامُ", trans: { ru: "ислам", en: "Islam" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "на", en: "upon" }, start: 0, end: 0 },
        { text: "خَمْسٍ", trans: { ru: "пяти", en: "five" }, start: 0, end: 0 },
        { text: "شَهَادَةِ", trans: { ru: "свидетельстве", en: "the testimony" }, start: 0, end: 0 },
        { text: "أَنْ", trans: { ru: "что", en: "that" }, start: 0, end: 0 },
        { text: "لَا", trans: { ru: "нет", en: "there is no" }, start: 0, end: 0 },
        { text: "إِلَهَ", trans: { ru: "божества", en: "god" }, start: 0, end: 0 },
        { text: "إِلَّا", trans: { ru: "кроме", en: "but" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллаха", en: "Allah" }, start: 0, end: 0 },
        { text: "وَأَنَّ", trans: { ru: "и что", en: "and that" }, start: 0, end: 0 },
        { text: "مُحَمَّدًا", trans: { ru: "Мухаммад", en: "Muhammad" }, start: 0, end: 0 },
        { text: "رَسُولُ", trans: { ru: "посланник", en: "is the Messenger of" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "Allah" }, start: 0, end: 0 },
        { text: "وَإِقَامِ", trans: { ru: "и совершении", en: "and the establishment of" }, start: 0, end: 0 },
        { text: "الصَّلَاةِ", trans: { ru: "молитвы", en: "the prayer" }, start: 0, end: 0 },
        { text: "وَإِيتَاءِ", trans: { ru: "и выплате", en: "and the giving of" }, start: 0, end: 0 },
        { text: "الزَّكَاةِ", trans: { ru: "закята", en: "zakat" }, start: 0, end: 0 },
        { text: "وَحَجِّ", trans: { ru: "и хадже к", en: "and the pilgrimage to" }, start: 0, end: 0 },
        { text: "الْبَيْتِ", trans: { ru: "Дому", en: "the House" }, start: 0, end: 0 },
        { text: "وَصَوْمِ", trans: { ru: "и посте", en: "and the fast of" }, start: 0, end: 0 },
        { text: "رَمَضَانَ", trans: { ru: "рамадана", en: "Ramadan" }, start: 0, end: 0 },
      ],
    },
  ],
};
