// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/05.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3005: ChapterData = {
  id: 3005,
  collection: 'nawawi',
  title: { ru: "Новшество в религии отвергается", en: "An innovation in the religion is rejected" },
  duas: [
    {
      id: "3005-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/05.mp3?v=cf4dd35d",
      narration: { ru: "От матери правоверных Умм Абдуллах — Аиши (да будет доволен ею Аллах) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of the Mother of the Believers, Umm Abdillah Aisha (may Allah be pleased with her), who said that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Кто введёт в наше дело то, что к нему не относится, то оно будет отвергнуто.", en: "Whoever introduces into this affair of ours something that does not belong to it, it is rejected." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ. وَفِي رِوَايَةٍ لِمُسْلِمٍ: ﴿مَنْ عَمِلَ عَمَلاً لَيْسَ عَلَيْهِ أَمْرُنَا فَهُوَ رَدٌّ﴾.",
      note: { ru: "Хадис передали аль-Бухари и Муслим. В версии Муслима сказано: «Деяния, не соответствующие нашему делу, будут отвергнуты».", en: "Related by al-Bukhari and Muslim. In Muslim's wording: “Whoever performs a deed that is not in accordance with this affair of ours, it is rejected.”" },
      source: { ru: "аль-Бухари 2697; Муслим 1718", en: "al-Bukhari 2697; Muslim 1718" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.3, end: 0.42 },
        { text: "أُمِّ", trans: { ru: "матери", en: "the Mother of" }, start: 0.42, end: 1.1 },
        { text: "الْمُؤْمِنِينَ", trans: { ru: "правоверных", en: "the Faithful" }, start: 1.1, end: 2.25 },
        { text: "أُمِّ", trans: { ru: "матери", en: "the Mother of" }, start: 2.34, end: 2.5 },
        { text: "عَبْدِ", trans: { ru: "Абд", en: "Abd" }, start: 2.5, end: 3.16 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 3.16, end: 3.5 },
        { text: "عَائِشَةَ", trans: { ru: "Аиши", en: "Aisha" }, start: 3.5, end: 4.94 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 5.02, end: 5.42 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 5.42, end: 5.7 },
        { text: "عَنْهَا", trans: { ru: "ею", en: "with her" }, start: 5.7, end: 6.99 },
        { text: "قَالَتْ", trans: { ru: "сказала", en: "she said" }, start: 7.12, end: 7.57 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 7.9, end: 8.5 },
        { text: "رَسُولُ", trans: { ru: "Посланник", en: "the Messenger of" }, start: 8.74, end: 9.46 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 9.46, end: 9.84 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 9.84, end: 10.56 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 10.56, end: 11 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 11, end: 11.62 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 11.62, end: 12.58 },
        { text: "مَنْ", trans: { ru: "кто", en: "whoever" }, start: 13.47, end: 14.2 },
        { text: "أَحْدَثَ", trans: { ru: "внесёт новое", en: "introduces" }, start: 14.3, end: 14.73 },
        { text: "فِي", trans: { ru: "в", en: "into" }, start: 14.73, end: 14.97 },
        { text: "أَمْرِنَا", trans: { ru: "наше дело", en: "this affair of ours" }, start: 14.97, end: 15.81 },
        { text: "هَذَا", trans: { ru: "это", en: "this" }, start: 15.81, end: 16.35 },
        { text: "مَا", trans: { ru: "то, что", en: "what" }, start: 16.35, end: 16.87 },
        { text: "لَيْسَ", trans: { ru: "не", en: "is not" }, start: 16.87, end: 17.49 },
        { text: "مِنْهُ", trans: { ru: "из него", en: "of it" }, start: 17.49, end: 18.3 },
        { text: "فَهُوَ", trans: { ru: "то оно", en: "then it is" }, start: 18.96, end: 19.28 },
        { text: "رَدٌّ", trans: { ru: "отвергнуто", en: "rejected" }, start: 19.28, end: 20.02 },
      ],
    },
  ],
};
