// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/07.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3007: ChapterData = {
  id: 3007,
  collection: 'nawawi',
  title: { ru: "Религия — это искренность", en: "The religion is sincere counsel" },
  duas: [
    {
      id: "3007-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/07.mp3?v=8a227873",
      narration: { ru: "От Абу Рукайя Тамима ибн Ауса ад-Дари (да будет доволен им Аллах) передаётся, что Пророк (да благословит его Аллах и приветствует) сказал трижды:", en: "On the authority of Abu Ruqayya Tamim ibn Aws ad-Dari (may Allah be pleased with him), that the Prophet (may Allah bless him and grant him peace) said three times:" },
      fullTranslation: { ru: "Религия — это искренность». И мы спросили: «К кому, о Посланник Аллаха?». И он сказал: «К Аллаху, Его книге, Его Посланнику, имамам мусульман и ко всем обычным мусульманам.", en: "The religion is sincerity.” We said: “To whom, O Messenger of Allah?” He said: “To Allah, to His Book, to His Messenger, to the leaders of the Muslims and to the Muslims at large." },
      takhrijArabic: "رَوَاهُ مُسْلِمٌ.",
      note: { ru: "Хадис передал Муслим.", en: "Related by Muslim." },
      source: { ru: "Муслим 55", en: "Muslim 55" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.55, end: 0.82 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0.82, end: 1.34 },
        { text: "رُقَيَّةَ", trans: { ru: "Рукайи", en: "Ruqayya" }, start: 1.34, end: 2.25 },
        { text: "تَمِيمِ", trans: { ru: "Тамима", en: "Tamim" }, start: 2.25, end: 2.91 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 2.91, end: 3.17 },
        { text: "أَوْسٍ", trans: { ru: "Ауса", en: "Aws" }, start: 3.17, end: 3.69 },
        { text: "الدَّارِيِّ", trans: { ru: "ад-Дари", en: "ad-Dari" }, start: 3.69, end: 5.39 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 5.39, end: 5.91 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 5.91, end: 6.57 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 6.57, end: 6.96 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 6.96, end: 7.48 },
        { text: "إِنَّ", trans: { ru: "поистине", en: "truly" }, start: 8.49, end: 8.93 },
        { text: "رَسُولَ", trans: { ru: "посланника", en: "the Messenger of" }, start: 8.93, end: 9.48 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 9.48, end: 10.03 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 10.03, end: 10.58 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 10.58, end: 11.13 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 11.13, end: 11.68 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 11.68, end: 12.45 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 12.45, end: 12.89 },
        { text: "الدِّينُ", trans: { ru: "религия", en: "the religion" }, start: 14.37, end: 15.22 },
        { text: "النَّصِيحَةُ", trans: { ru: "искренность", en: "is sincere counsel" }, start: 15.22, end: 16.25 },
        { text: "لِلَّهِ", trans: { ru: "по отношению к Аллаху", en: "towards Allah" }, start: 17.13, end: 18.14 },
        { text: "وَلِكِتَابِهِ", trans: { ru: "и к Его писанию", en: "and His Book" }, start: 18.73, end: 20.09 },
        { text: "وَلِرَسُولِهِ", trans: { ru: "и к Его посланнику", en: "and His Messenger" }, start: 20.66, end: 22.04 },
        { text: "وَلِأَئِمَّةِ", trans: { ru: "и к предводителям", en: "and the leaders of" }, start: 22.61, end: 23.86 },
        { text: "الْمُسْلِمِينَ", trans: { ru: "мусульман", en: "the Muslims" }, start: 23.86, end: 25.25 },
        { text: "وَعَامَّتِهِمْ", trans: { ru: "и к простым из них", en: "and their common folk" }, start: 25.25, end: 26.77 },
      ],
    },
  ],
};
