// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/07.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3007: ChapterData = {
  id: 3007,
  collection: 'nawawi',
  title: { ru: "Религия — это искренность", en: "The religion is sincere counsel" },
  duas: [
    {
      id: "3007-1",
      narration: { ru: "Со слов Абу Рукаййи Тамима ибн Ауса ад-Дари, да будет доволен им Аллах, передаётся, что Пророк ﷺ сказал: «Религия — это искренность». Мы спросили: «По отношению к кому?» Он ответил:", en: "On the authority of Abu Ruqayyah Tamim ibn Aws ad-Dari, may Allah be pleased with him, that the Prophet ﷺ said: “The religion is sincere counsel.” We said: “To whom?” He said:" },
      fullTranslation: { ru: "Религия — это искренность. По отношению к Аллаху, к Его писанию, к Его посланнику, к предводителям мусульман и к простым мусульманам.", en: "The religion is sincere counsel — towards Allah, His Book, His Messenger, the leaders of the Muslims, and their common folk." },
      source: { ru: "Муслим 55", en: "Muslim 55" },
      sync: [
        { text: "الدِّينُ", trans: { ru: "религия", en: "the religion" }, start: 0, end: 0 },
        { text: "النَّصِيحَةُ", trans: { ru: "искренность", en: "is sincere counsel" }, start: 0, end: 0 },
        { text: "لِلَّهِ", trans: { ru: "по отношению к Аллаху", en: "towards Allah" }, start: 0, end: 0 },
        { text: "وَلِكِتَابِهِ", trans: { ru: "и к Его писанию", en: "and His Book" }, start: 0, end: 0 },
        { text: "وَلِرَسُولِهِ", trans: { ru: "и к Его посланнику", en: "and His Messenger" }, start: 0, end: 0 },
        { text: "وَلِأَئِمَّةِ", trans: { ru: "и к предводителям", en: "and the leaders of" }, start: 0, end: 0 },
        { text: "الْمُسْلِمِينَ", trans: { ru: "мусульман", en: "the Muslims" }, start: 0, end: 0 },
        { text: "وَعَامَّتِهِمْ", trans: { ru: "и к простым из них", en: "and their common folk" }, start: 0, end: 0 },
      ],
    },
  ],
};
