// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/07.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3007: ChapterData = {
  id: 3007,
  collection: 'nawawi',
  title: { ru: "Религия — это искренность", en: "The religion is sincere counsel" },
  duas: [
    {
      id: "3007-1",
      narration: { ru: "От Абу Рукайя Тамима ибн Ауса ад-Дари (да будет доволен им Аллах) передаётся, что Пророк (да благословит его Аллах и приветствует) сказал трижды:", en: "On the authority of Abu Ruqayya Tamim ibn Aws ad-Dari (may Allah be pleased with him), that the Prophet (may Allah bless him and grant him peace) said three times:" },
      fullTranslation: { ru: "Религия — это искренность». И мы спросили: «К кому, о Посланник Аллаха?». И он сказал: «К Аллаху, Его книге, Его Посланнику, имамам мусульман и ко всем обычным мусульманам.", en: "The religion is sincerity.” We said: “To whom, O Messenger of Allah?” He said: “To Allah, to His Book, to His Messenger, to the leaders of the Muslims and to the Muslims at large." },
      takhrijArabic: "رَوَاهُ مُسْلِمٌ.",
      note: { ru: "Хадис передал Муслим.", en: "Related by Muslim." },
      source: { ru: "Муслим 55", en: "Muslim 55" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0, end: 0 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0, end: 0 },
        { text: "رُقَيَّةَ", trans: { ru: "Рукайи", en: "Ruqayya" }, start: 0, end: 0 },
        { text: "تَمِيمِ", trans: { ru: "Тамима", en: "Tamim" }, start: 0, end: 0 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 0, end: 0 },
        { text: "أَوْسٍ", trans: { ru: "Ауса", en: "Aws" }, start: 0, end: 0 },
        { text: "الدَّارِيِّ", trans: { ru: "ад-Дари", en: "ad-Dari" }, start: 0, end: 0 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 0, end: 0 },
        { text: "إِنَّ", trans: { ru: "поистине", en: "truly" }, start: 0, end: 0 },
        { text: "رَسُولَ", trans: { ru: "посланника", en: "the Messenger of" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 0, end: 0 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 0, end: 0 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 0, end: 0 },
        { text: "الدِّينُ", trans: { ru: "религия", en: "the religion" }, start: 0, end: 0 },
        { text: "النَّصِيحَةُ", trans: { ru: "искренность", en: "is sincere counsel" }, start: 0, end: 0 },
        { text: "لِلَّهِ", trans: { ru: "по отношению к Аллаху", en: "towards Allah" }, start: 0, end: 0 },
        { text: "وَلِكِتَابِهِ", trans: { ru: "и к Его писанию", en: "and His Book" }, start: 0, end: 0 },
        { text: "وَلِرَسُولِهِ", trans: { ru: "и к Его посланнику", en: "and His Messenger" }, start: 0, end: 0 },
        { text: "وَلِأَئِمَّةِ", trans: { ru: "и к предводителям", en: "and the leaders of" }, start: 0, end: 0 },
        { text: "الْمُسْلِمِينَ", trans: { ru: "мусульман", en: "the Muslims" }, start: 0, end: 0 },
        { text: "وَعَامَّتِهِمْ", trans: { ru: "и к простым из них", en: "and their common folk" }, start: 0, end: 0 },
      ],
    },
  ],
};
