// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/08.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3008: ChapterData = {
  id: 3008,
  collection: 'nawawi',
  title: { ru: "Неприкосновенность мусульманина", en: "The inviolability of the Muslim" },
  duas: [
    {
      id: "3008-1",
      narration: { ru: "Со слов Ибн Умара, да будет доволен Аллах ими обоими, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Ibn Umar, may Allah be pleased with them both, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Мне велено сражаться с людьми, пока они не засвидетельствуют, что нет божества, кроме Аллаха, и что Мухаммад — посланник Аллаха, не станут совершать молитву и выплачивать закят. А если они сделают это, то защитят от меня свою кровь и своё имущество, кроме как по праву ислама, и расчёт с ними — у Аллаха Всевышнего.", en: "I have been commanded to fight the people until they testify that there is no god but Allah and that Muhammad is the Messenger of Allah, and they establish the prayer and give the zakat. If they do that, their blood and their property are protected from me, except by the right of Islam, and their reckoning is with Allah the Exalted." },
      source: { ru: "аль-Бухари 25; Муслим 22", en: "al-Bukhari 25; Muslim 22" },
      sync: [
        { text: "أُمِرْتُ", trans: { ru: "мне велено", en: "I have been commanded" }, start: 0, end: 0 },
        { text: "أَنْ", trans: { ru: "чтобы", en: "to" }, start: 0, end: 0 },
        { text: "أُقَاتِلَ", trans: { ru: "я сражался", en: "fight" }, start: 0, end: 0 },
        { text: "النَّاسَ", trans: { ru: "с людьми", en: "the people" }, start: 0, end: 0 },
        { text: "حَتَّى", trans: { ru: "пока", en: "until" }, start: 0, end: 0 },
        { text: "يَشْهَدُوا", trans: { ru: "они не засвидетельствуют", en: "they testify" }, start: 0, end: 0 },
        { text: "أَنْ", trans: { ru: "что", en: "that" }, start: 0, end: 0 },
        { text: "لَا", trans: { ru: "нет", en: "there is no" }, start: 0, end: 0 },
        { text: "إِلَهَ", trans: { ru: "божества", en: "god" }, start: 0, end: 0 },
        { text: "إِلَّا", trans: { ru: "кроме", en: "but" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллаха", en: "Allah" }, start: 0, end: 0 },
        { text: "وَأَنَّ", trans: { ru: "и что", en: "and that" }, start: 0, end: 0 },
        { text: "مُحَمَّدًا", trans: { ru: "Мухаммад", en: "Muhammad" }, start: 0, end: 0 },
        { text: "رَسُولُ", trans: { ru: "посланник", en: "is the Messenger of" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "Allah" }, start: 0, end: 0 },
        { text: "وَيُقِيمُوا", trans: { ru: "и не станут совершать", en: "and they establish" }, start: 0, end: 0 },
        { text: "الصَّلَاةَ", trans: { ru: "молитву", en: "the prayer" }, start: 0, end: 0 },
        { text: "وَيُؤْتُوا", trans: { ru: "и выплачивать", en: "and give" }, start: 0, end: 0 },
        { text: "الزَّكَاةَ", trans: { ru: "закят", en: "the zakat" }, start: 0, end: 0 },
        { text: "فَإِذَا", trans: { ru: "и если", en: "and if" }, start: 0, end: 0 },
        { text: "فَعَلُوا", trans: { ru: "они сделают", en: "they do" }, start: 0, end: 0 },
        { text: "ذَلِكَ", trans: { ru: "это", en: "that" }, start: 0, end: 0 },
        { text: "عَصَمُوا", trans: { ru: "они защитят", en: "they have protected" }, start: 0, end: 0 },
        { text: "مِنِّي", trans: { ru: "от меня", en: "from me" }, start: 0, end: 0 },
        { text: "دِمَاءَهُمْ", trans: { ru: "свою кровь", en: "their blood" }, start: 0, end: 0 },
        { text: "وَأَمْوَالَهُمْ", trans: { ru: "и своё имущество", en: "and their property" }, start: 0, end: 0 },
        { text: "إِلَّا", trans: { ru: "кроме как", en: "except" }, start: 0, end: 0 },
        { text: "بِحَقِّ", trans: { ru: "по праву", en: "by the right of" }, start: 0, end: 0 },
        { text: "الْإِسْلَامِ", trans: { ru: "ислама", en: "Islam" }, start: 0, end: 0 },
        { text: "وَحِسَابُهُمْ", trans: { ru: "а расчёт с ними", en: "and their reckoning is" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "у", en: "with" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "Allah" }, start: 0, end: 0 },
        { text: "تَعَالَى", trans: { ru: "Всевышнего", en: "the Exalted" }, start: 0, end: 0 },
      ],
    },
  ],
};
