// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/09.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3009: ChapterData = {
  id: 3009,
  collection: 'nawawi',
  title: { ru: "Делайте то, что вам по силам", en: "Do what you are able to do" },
  duas: [
    {
      id: "3009-1",
      narration: { ru: "От Абу Хурайры Абдуррахмана ибн Сахра (да будет доволен им Аллах) передаётся, что он слышал, как Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Hurayra Abd ar-Rahman ibn Sakhr (may Allah be pleased with him), who heard the Messenger of Allah (may Allah bless him and grant him peace) say:" },
      isnadArabic: "عَنْ أَبِي هُرَيْرَةَ عَبْدِ الرَّحْمَنِ بنِ صَخْرٍ رَضِيَ اللهُ عَنْهُ قَالَ: سَمِعْتُ رَسُولَ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ يَقُولُ:",
      fullTranslation: { ru: "Отстраняйтесь от того, что я запретил вам, и делайте, что можете, из того, что я повелеваю вам, а погубило общины до вас множество вопросов и их разногласия с их же пророками.", en: "Avoid what I have forbidden you, and do of what I have commanded you as much as you are able. What destroyed the nations before you was their many questions and their disagreement with their prophets." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ.",
      note: { ru: "Хадис передали аль-Бухари и Муслим.", en: "Related by al-Bukhari and Muslim." },
      source: { ru: "аль-Бухари 7288; Муслим 1337", en: "al-Bukhari 7288; Muslim 1337" },
      sync: [
        { text: "مَا", trans: { ru: "то, что", en: "what" }, start: 0, end: 0 },
        { text: "نَهَيْتُكُمْ", trans: { ru: "я запретил вам", en: "I have forbidden you" }, start: 0, end: 0 },
        { text: "عَنْهُ", trans: { ru: "от него", en: "from" }, start: 0, end: 0 },
        { text: "فَاجْتَنِبُوهُ", trans: { ru: "избегайте этого", en: "avoid it" }, start: 0, end: 0 },
        { text: "وَمَا", trans: { ru: "а то, что", en: "and what" }, start: 0, end: 0 },
        { text: "أَمَرْتُكُمْ", trans: { ru: "я велел вам", en: "I have commanded you" }, start: 0, end: 0 },
        { text: "بِهِ", trans: { ru: "им", en: "with" }, start: 0, end: 0 },
        { text: "فَأْتُوا", trans: { ru: "исполняйте", en: "do" }, start: 0, end: 0 },
        { text: "مِنْهُ", trans: { ru: "из него", en: "of it" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "то, что", en: "what" }, start: 0, end: 0 },
        { text: "اسْتَطَعْتُمْ", trans: { ru: "вы можете", en: "you are able" }, start: 0, end: 0 },
        { text: "فَإِنَّمَا", trans: { ru: "ибо", en: "for indeed" }, start: 0, end: 0 },
        { text: "أَهْلَكَ", trans: { ru: "погубило", en: "destroyed" }, start: 0, end: 0 },
        { text: "الَّذِينَ", trans: { ru: "тех", en: "those" }, start: 0, end: 0 },
        { text: "مِنْ", trans: { ru: "из", en: "from" }, start: 0, end: 0 },
        { text: "قَبْلِكُمْ", trans: { ru: "живших до вас", en: "before you" }, start: 0, end: 0 },
        { text: "كَثْرَةُ", trans: { ru: "множество", en: "the abundance of" }, start: 0, end: 0 },
        { text: "مَسَائِلِهِمْ", trans: { ru: "их вопросов", en: "their questions" }, start: 0, end: 0 },
        { text: "وَاخْتِلَافُهُمْ", trans: { ru: "и их разногласия", en: "and their disagreement" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "с", en: "with" }, start: 0, end: 0 },
        { text: "أَنْبِيَائِهِمْ", trans: { ru: "их пророками", en: "their prophets" }, start: 0, end: 0 },
      ],
    },
  ],
};
