// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/11.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3011: ChapterData = {
  id: 3011,
  collection: 'nawawi',
  title: { ru: "Оставь то, что вызывает у тебя сомнение", en: "Leave what makes you doubt" },
  duas: [
    {
      id: "3011-1",
      narration: { ru: "От Абу Мухаммада аль-Хасана ибн Али ибн Аби Талиба, внука Посланника Аллаха (да благословит его Аллах и приветствует) и его райхана (да будет доволен им Аллах) передаётся: «Я запомнил от Посланника Аллаха (да благословит его Аллах и приветствует) следующее:", en: "On the authority of Abu Muhammad al-Hasan ibn Ali ibn Abi Talib, the grandson of the Messenger of Allah (may Allah bless him and grant him peace) and his fragrant flower (may Allah be pleased with them both), who said: “I memorised from the Messenger of Allah (may Allah bless him and grant him peace) the following:" },
      isnadArabic: "عَنْ أَبِي مُحَمَّدٍ الْحَسَنِ بنِ عَلِيٍّ بنِ أَبِي طَالِبٍ سِبْطِ رَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ وَرَيْحَانَتِهِ رَضِيَ اللهُ عَنْهُمَا قَالَ: حَفِظْتُ مِنْ رَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ:",
      fullTranslation: { ru: "Оставь то, в чём сомневаешься, в пользу того, в чём не сомневаешься.", en: "Leave what makes you doubt for what does not make you doubt." },
      takhrijArabic: "رَوَاهُ التِّرْمِذِيُّ وَالنَّسَائِيُّ، وَقَالَ التِّرْمِذِيُّ: حَدِيثٌ حَسَنٌ صَحِيحٌ.",
      note: { ru: "Хадис передали ан-Насаи и ат-Тирмизи. Ат-Тирмизи сказал: «Хадис хасан сахих».", en: "Related by an-Nasa'i and at-Tirmidhi. At-Tirmidhi said: “A hasan sahih hadith.”" },
      source: { ru: "ат-Тирмизи 2518; ан-Наса‘и 5711", en: "at-Tirmidhi 2518; an-Nasa'i 5711" },
      sync: [
        { text: "دَعْ", trans: { ru: "оставь", en: "leave" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "то, что", en: "what" }, start: 0, end: 0 },
        { text: "يَرِيبُكَ", trans: { ru: "вызывает у тебя сомнение", en: "makes you doubt" }, start: 0, end: 0 },
        { text: "إِلَى", trans: { ru: "ради", en: "for" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "того, что", en: "what" }, start: 0, end: 0 },
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 0, end: 0 },
        { text: "يَرِيبُكَ", trans: { ru: "вызывает у тебя сомнения", en: "make you doubt" }, start: 0, end: 0 },
      ],
    },
  ],
};
