// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/11.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3011: ChapterData = {
  id: 3011,
  collection: 'nawawi',
  title: { ru: "Оставь то, что вызывает у тебя сомнение", en: "Leave what makes you doubt" },
  duas: [
    {
      id: "3011-1",
      narration: { ru: "Со слов Абу Мухаммада аль-Хасана ибн Али, внука посланника Аллаха ﷺ и его любимца, да будет доволен Аллах ими обоими, передаётся, что он сказал: «Я запомнил от посланника Аллаха ﷺ слова…»", en: "On the authority of Abu Muhammad al-Hasan ibn Ali, the grandson and beloved of the Messenger of Allah ﷺ, may Allah be pleased with them both, who said: “I memorised from the Messenger of Allah ﷺ…”" },
      fullTranslation: { ru: "Оставь то, что вызывает у тебя сомнение, ради того, что сомнения у тебя не вызывает.", en: "Leave what makes you doubt for what does not make you doubt." },
      source: { ru: "ат-Тирмизи 2518; ан-Наса‘и 5711", en: "at-Tirmidhi 2518; an-Nasa'i 5711" },
      sync: [
        { text: "دَعْ", trans: { ru: "оставь", en: "leave" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "то, что", en: "what" }, start: 0, end: 0 },
        { text: "يَرِيبُكَ", trans: { ru: "вызывает у тебя сомнение", en: "makes you doubt" }, start: 0, end: 0 },
        { text: "إِلَى", trans: { ru: "ради", en: "for" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "того, что", en: "what" }, start: 0, end: 0 },
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 0, end: 0 },
        { text: "يَرِيبُكَ", trans: { ru: "вызывает у тебя сомнения", en: "make you doubt" }, start: 0, end: 0 },
      ],
    },
  ],
};
