// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/12.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3012: ChapterData = {
  id: 3012,
  collection: 'nawawi',
  title: { ru: "Оставить то, что тебя не касается", en: "Leaving what does not concern you" },
  duas: [
    {
      id: "3012-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/12.mp3?v=26b7798e",
      narration: { ru: "От Абу Хурайры (да будет доволен им Аллах) передаётся, что Пророк (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Hurayra (may Allah be pleased with him), that the Prophet (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Из благого Ислама человека — оставление того, что его не касается.", en: "Part of a man's excellence in Islam is his leaving what does not concern him." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ، رَوَاهُ التِّرْمِذِيُّ وَغَيْرُهُ هَكَذَا.",
      note: { ru: "Хадис хороший. Его передал ат-Тирмизи и другие.", en: "A hasan hadith, related by at-Tirmidhi and others." },
      source: { ru: "ат-Тирмизи 2317; Ибн Маджа 3976", en: "at-Tirmidhi 2317; Ibn Majah 3976" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.41, end: 0.63 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0.63, end: 1.18 },
        { text: "هُرَيْرَةَ", trans: { ru: "Хурайры", en: "Hurayra" }, start: 1.18, end: 2.05 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 2.05, end: 2.61 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 2.61, end: 2.87 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 2.87, end: 3.84 },
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 4.75, end: 5.18 },
        { text: "النَّبِيِّ", trans: { ru: "Пророка", en: "the Prophet" }, start: 5.18, end: 5.81 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 5.81, end: 6.2 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 6.2, end: 6.56 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 6.56, end: 7.1 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 7.1, end: 7.96 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 7.96, end: 8.27 },
        { text: "مِنْ", trans: { ru: "из", en: "part of" }, start: 9.66, end: 9.78 },
        { text: "حُسْنِ", trans: { ru: "красоты", en: "the excellence of" }, start: 9.91, end: 10.65 },
        { text: "إِسْلَامِ", trans: { ru: "ислама", en: "the Islam of" }, start: 10.65, end: 11.33 },
        { text: "الْمَرْءِ", trans: { ru: "человека", en: "a man" }, start: 11.33, end: 12.18 },
        { text: "تَرْكُهُ", trans: { ru: "его оставление", en: "is his leaving" }, start: 13.18, end: 13.47 },
        { text: "مَا", trans: { ru: "того, что", en: "what" }, start: 13.58, end: 14.18 },
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 14.18, end: 14.67 },
        { text: "يَعْنِيهِ", trans: { ru: "его касается", en: "concern him" }, start: 14.67, end: 15.9 },
      ],
    },
  ],
};
