// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/12.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3012: ChapterData = {
  id: 3012,
  collection: 'nawawi',
  title: { ru: "Оставить то, что тебя не касается", en: "Leaving what does not concern you" },
  duas: [
    {
      id: "3012-1",
      narration: { ru: "От Абу Хурайры (да будет доволен им Аллах) передаётся, что Пророк (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Hurayra (may Allah be pleased with him), that the Prophet (may Allah bless him and grant him peace) said:" },
      isnadArabic: "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ عَنِ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ قَالَ:",
      fullTranslation: { ru: "Из благого Ислама человека — оставление того, что его не касается.", en: "Part of a man's excellence in Islam is his leaving what does not concern him." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ، رَوَاهُ التِّرْمِذِيُّ وَغَيْرُهُ هَكَذَا.",
      note: { ru: "Хадис хороший. Его передал ат-Тирмизи и другие.", en: "A hasan hadith, related by at-Tirmidhi and others." },
      source: { ru: "ат-Тирмизи 2317; Ибн Маджа 3976", en: "at-Tirmidhi 2317; Ibn Majah 3976" },
      sync: [
        { text: "مِنْ", trans: { ru: "из", en: "part of" }, start: 0, end: 0 },
        { text: "حُسْنِ", trans: { ru: "красоты", en: "the excellence of" }, start: 0, end: 0 },
        { text: "إِسْلَامِ", trans: { ru: "ислама", en: "the Islam of" }, start: 0, end: 0 },
        { text: "الْمَرْءِ", trans: { ru: "человека", en: "a man" }, start: 0, end: 0 },
        { text: "تَرْكُهُ", trans: { ru: "его оставление", en: "is his leaving" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "того, что", en: "what" }, start: 0, end: 0 },
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 0, end: 0 },
        { text: "يَعْنِيهِ", trans: { ru: "его касается", en: "concern him" }, start: 0, end: 0 },
      ],
    },
  ],
};
