// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/12.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3012: ChapterData = {
  id: 3012,
  collection: 'nawawi',
  title: { ru: "Оставить то, что тебя не касается", en: "Leaving what does not concern you" },
  duas: [
    {
      id: "3012-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/12.mp3?v=2cea42cf",
      narration: { ru: "От Абу Хурайры (да будет доволен им Аллах) передаётся, что Пророк (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Hurayra (may Allah be pleased with him), that the Prophet (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Из благого Ислама человека — оставление того, что его не касается.", en: "Part of a man's excellence in Islam is his leaving what does not concern him." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ، رَوَاهُ التِّرْمِذِيُّ وَغَيْرُهُ هَكَذَا.",
      note: { ru: "Хадис хороший. Его передал ат-Тирмизи и другие.", en: "A hasan hadith, related by at-Tirmidhi and others." },
      source: { ru: "ат-Тирмизи 2317; Ибн Маджа 3976", en: "at-Tirmidhi 2317; Ibn Majah 3976" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.28, end: 0.58 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0.62, end: 0.92 },
        { text: "هُرَيْرَةَ", trans: { ru: "Хурайры", en: "Hurayra" }, start: 0.97, end: 1.42 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 1.49, end: 1.97 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 1.97, end: 2.16 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 2.16, end: 2.81 },
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 3.22, end: 3.42 },
        { text: "النَّبِيِّ", trans: { ru: "Пророка", en: "the Prophet" }, start: 3.42, end: 4.04 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 4.04, end: 4.41 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 4.41, end: 4.6 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 4.64, end: 5.1 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 5.16, end: 5.84 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 5.95, end: 6.32 },
        { text: "مِنْ", trans: { ru: "из", en: "part of" }, start: 7.11, end: 7.35 },
        { text: "حُسْنِ", trans: { ru: "красоты", en: "the excellence of" }, start: 7.43, end: 7.81 },
        { text: "إِسْلَامِ", trans: { ru: "ислама", en: "the Islam of" }, start: 7.88, end: 8.27 },
        { text: "الْمَرْءِ", trans: { ru: "человека", en: "a man" }, start: 8.27, end: 8.77 },
        { text: "تَرْكُهُ", trans: { ru: "его оставление", en: "is his leaving" }, start: 9.45, end: 9.59 },
        { text: "مَا", trans: { ru: "того, что", en: "what" }, start: 9.74, end: 10.22 },
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 10.22, end: 10.62 },
        { text: "يَعْنِيهِ", trans: { ru: "его касается", en: "concern him" }, start: 10.62, end: 11.38 },
      ],
    },
  ],
};
