// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/13.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3013: ChapterData = {
  id: 3013,
  collection: 'nawawi',
  title: { ru: "Желать брату того же, чего себе", en: "Loving for your brother what you love for yourself" },
  duas: [
    {
      id: "3013-1",
      narration: { ru: "От Абу Хамзы Анаса ибн Малика (да будет доволен им Аллах) — слуги Посланника Аллаха (да благословит его Аллах и приветствует) — передаётся, что Пророк (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Hamza Anas ibn Malik (may Allah be pleased with him), the servant of the Messenger of Allah (may Allah bless him and grant him peace), that the Prophet (may Allah bless him and grant him peace) said:" },
      isnadArabic: "عَنْ أَبِي حَمْزَةَ أَنَسِ بنِ مَالِكٍ رَضِيَ اللهُ عَنْهُ خَادِمِ رَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ عَنِ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ أَنَّهُ قَالَ:",
      fullTranslation: { ru: "Никто из вас не уверует, пока не будет любить для своего брата то же, что любит для себя.", en: "None of you truly believes until he loves for his brother what he loves for himself." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ.",
      note: { ru: "Хадис передали аль-Бухари и Муслим.", en: "Related by al-Bukhari and Muslim." },
      source: { ru: "аль-Бухари 13; Муслим 45", en: "al-Bukhari 13; Muslim 45" },
      sync: [
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 0, end: 0 },
        { text: "يُؤْمِنُ", trans: { ru: "уверует", en: "believe" }, start: 0, end: 0 },
        { text: "أَحَدُكُمْ", trans: { ru: "никто из вас", en: "any of you" }, start: 0, end: 0 },
        { text: "حَتَّى", trans: { ru: "пока", en: "until" }, start: 0, end: 0 },
        { text: "يُحِبَّ", trans: { ru: "не полюбит", en: "he loves" }, start: 0, end: 0 },
        { text: "لِأَخِيهِ", trans: { ru: "для своего брата", en: "for his brother" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "то, что", en: "what" }, start: 0, end: 0 },
        { text: "يُحِبُّ", trans: { ru: "любит", en: "he loves" }, start: 0, end: 0 },
        { text: "لِنَفْسِهِ", trans: { ru: "для себя", en: "for himself" }, start: 0, end: 0 },
      ],
    },
  ],
};
