// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/14.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3014: ChapterData = {
  id: 3014,
  collection: 'nawawi',
  title: { ru: "Кровь мусульманина дозволена лишь в трёх случаях", en: "The blood of a Muslim is lawful only in three cases" },
  duas: [
    {
      id: "3014-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/14.mp3?v=253e07c4",
      narration: { ru: "От Ибн Мас‘уда (да будет доволен им Аллах) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Ibn Mas'ud (may Allah be pleased with him), that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Не дозволено проливать кровь мусульманина, кроме как в трёх случаях: за прелюбодеяние состоявшего в браке, за убийство и за оставление религии и покидание общины.", en: "The blood of a Muslim is not lawful except in three cases: the married person who commits adultery, a life for a life, and the one who abandons his religion and departs from the community." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ.",
      note: { ru: "Хадис передали аль-Бухари и Муслим.", en: "Related by al-Bukhari and Muslim." },
      source: { ru: "аль-Бухари 6878; Муслим 1676", en: "al-Bukhari 6878; Muslim 1676" },
      sync: [
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 0.87, end: 0.93 },
        { text: "ابنِ", trans: { ru: "Ибн", en: "Ibn" }, start: 0.93, end: 1.31 },
        { text: "مَسْعُودٍ", trans: { ru: "Мас‘уда", en: "Mas'ud" }, start: 1.31, end: 1.95 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 1.95, end: 2.53 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 2.53, end: 2.79 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 2.79, end: 3.8 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 3.9, end: 4.45 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 5.57, end: 5.6 },
        { text: "رَسُولُ", trans: { ru: "Посланник", en: "the Messenger of" }, start: 5.6, end: 6.26 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 6.26, end: 6.58 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 6.58, end: 7.32 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 7.32, end: 7.68 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 7.68, end: 8.26 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 8.26, end: 9.36 },
        { text: "لَا", trans: { ru: "не", en: "not" }, start: 10.62, end: 10.7 },
        { text: "يَحِلُّ", trans: { ru: "дозволена", en: "is lawful" }, start: 10.7, end: 11.3 },
        { text: "دَمُ", trans: { ru: "кровь", en: "the blood of" }, start: 11.3, end: 11.76 },
        { text: "امْرِئٍ", trans: { ru: "человека", en: "a man" }, start: 11.76, end: 12.12 },
        { text: "مُسْلِمٍ", trans: { ru: "мусульманина", en: "who is Muslim" }, start: 12.12, end: 12.88 },
        { text: "إِلَّا", trans: { ru: "кроме как", en: "except" }, start: 12.88, end: 13.22 },
        { text: "بِإِحْدَى", trans: { ru: "в одном из", en: "by one of" }, start: 13.35, end: 14.54 },
        { text: "ثَلَاثٍ", trans: { ru: "трёх", en: "three" }, start: 14.54, end: 15.38 },
        { text: "الثَّيِّبُ", trans: { ru: "состоявший в браке", en: "the married person" }, start: 16.59, end: 17.3 },
        { text: "الزَّانِي", trans: { ru: "прелюбодей", en: "who commits adultery" }, start: 17.3, end: 18.19 },
        { text: "وَالنَّفْسُ", trans: { ru: "и душа", en: "and a life" }, start: 19.29, end: 19.85 },
        { text: "بِالنَّفْسِ", trans: { ru: "за душу", en: "for a life" }, start: 19.85, end: 20.87 },
        { text: "وَالتَّارِكُ", trans: { ru: "и оставивший", en: "and the one who abandons" }, start: 22.08, end: 22.83 },
        { text: "لِدِينِهِ", trans: { ru: "свою религию", en: "his religion" }, start: 22.91, end: 23.66 },
        { text: "الْمُفَارِقُ", trans: { ru: "отделившийся", en: "separating" }, start: 23.66, end: 24.55 },
        { text: "لِلْجَمَاعَةِ", trans: { ru: "от общины", en: "from the community" }, start: 24.63, end: 25.67 },
      ],
    },
  ],
};
