// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/14.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3014: ChapterData = {
  id: 3014,
  collection: 'nawawi',
  title: { ru: "Кровь мусульманина дозволена лишь в трёх случаях", en: "The blood of a Muslim is lawful only in three cases" },
  duas: [
    {
      id: "3014-1",
      narration: { ru: "От Ибн Мас‘уда (да будет доволен им Аллах) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Ibn Mas'ud (may Allah be pleased with him), that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      isnadArabic: "عَنِ ابنِ مَسْعُودٍ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ:",
      fullTranslation: { ru: "Не дозволено проливать кровь мусульманина, кроме как в трёх случаях: за прелюбодеяние состоявшего в браке, за убийство и за оставление религии и покидание общины.", en: "The blood of a Muslim is not lawful except in three cases: the married person who commits adultery, a life for a life, and the one who abandons his religion and departs from the community." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ.",
      note: { ru: "Хадис передали аль-Бухари и Муслим.", en: "Related by al-Bukhari and Muslim." },
      source: { ru: "аль-Бухари 6878; Муслим 1676", en: "al-Bukhari 6878; Muslim 1676" },
      sync: [
        { text: "لَا", trans: { ru: "не", en: "not" }, start: 0, end: 0 },
        { text: "يَحِلُّ", trans: { ru: "дозволена", en: "is lawful" }, start: 0, end: 0 },
        { text: "دَمُ", trans: { ru: "кровь", en: "the blood of" }, start: 0, end: 0 },
        { text: "امْرِئٍ", trans: { ru: "человека", en: "a man" }, start: 0, end: 0 },
        { text: "مُسْلِمٍ", trans: { ru: "мусульманина", en: "who is Muslim" }, start: 0, end: 0 },
        { text: "إِلَّا", trans: { ru: "кроме как", en: "except" }, start: 0, end: 0 },
        { text: "بِإِحْدَى", trans: { ru: "в одном из", en: "by one of" }, start: 0, end: 0 },
        { text: "ثَلَاثٍ", trans: { ru: "трёх", en: "three" }, start: 0, end: 0 },
        { text: "الثَّيِّبُ", trans: { ru: "состоявший в браке", en: "the married person" }, start: 0, end: 0 },
        { text: "الزَّانِي", trans: { ru: "прелюбодей", en: "who commits adultery" }, start: 0, end: 0 },
        { text: "وَالنَّفْسُ", trans: { ru: "и душа", en: "and a life" }, start: 0, end: 0 },
        { text: "بِالنَّفْسِ", trans: { ru: "за душу", en: "for a life" }, start: 0, end: 0 },
        { text: "وَالتَّارِكُ", trans: { ru: "и оставивший", en: "and the one who abandons" }, start: 0, end: 0 },
        { text: "لِدِينِهِ", trans: { ru: "свою религию", en: "his religion" }, start: 0, end: 0 },
        { text: "الْمُفَارِقُ", trans: { ru: "отделившийся", en: "separating" }, start: 0, end: 0 },
        { text: "لِلْجَمَاعَةِ", trans: { ru: "от общины", en: "from the community" }, start: 0, end: 0 },
      ],
    },
  ],
};
