// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/15.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3015: ChapterData = {
  id: 3015,
  collection: 'nawawi',
  title: { ru: "Пусть говорит благое или молчит", en: "Let him speak good or keep silent" },
  duas: [
    {
      id: "3015-1",
      narration: { ru: "Со слов Абу Хурайры, да будет доволен им Аллах, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Abu Hurayra, may Allah be pleased with him, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Пусть тот, кто верует в Аллаха и в Последний день, говорит благое или молчит. И пусть тот, кто верует в Аллаха и в Последний день, оказывает почёт своему соседу. И пусть тот, кто верует в Аллаха и в Последний день, оказывает почёт своему гостю.", en: "Whoever believes in Allah and the Last Day, let him speak good or keep silent. Whoever believes in Allah and the Last Day, let him honour his neighbour. And whoever believes in Allah and the Last Day, let him honour his guest." },
      source: { ru: "аль-Бухари 6018; Муслим 47", en: "al-Bukhari 6018; Muslim 47" },
      sync: [
        { text: "مَنْ", trans: { ru: "кто", en: "whoever" }, start: 0, end: 0 },
        { text: "كَانَ", trans: { ru: "пребывает в том, что", en: "is such that he" }, start: 0, end: 0 },
        { text: "يُؤْمِنُ", trans: { ru: "верует", en: "believing" }, start: 0, end: 0 },
        { text: "بِاللهِ", trans: { ru: "в Аллаха", en: "in Allah" }, start: 0, end: 0 },
        { text: "وَالْيَوْمِ", trans: { ru: "и в день", en: "and the Day" }, start: 0, end: 0 },
        { text: "الْآخِرِ", trans: { ru: "Последний", en: "the Last" }, start: 0, end: 0 },
        { text: "فَلْيَقُلْ", trans: { ru: "пусть говорит", en: "let him say" }, start: 0, end: 0 },
        { text: "خَيْرًا", trans: { ru: "благое", en: "what is good" }, start: 0, end: 0 },
        { text: "أَوْ", trans: { ru: "или", en: "or" }, start: 0, end: 0 },
        { text: "لِيَصْمُتْ", trans: { ru: "пусть молчит", en: "let him keep silent" }, start: 0, end: 0 },
        { text: "وَمَنْ", trans: { ru: "и кто", en: "and whoever" }, start: 0, end: 0 },
        { text: "كَانَ", trans: { ru: "пребывает в том, что", en: "is such that he" }, start: 0, end: 0 },
        { text: "يُؤْمِنُ", trans: { ru: "верует", en: "believing" }, start: 0, end: 0 },
        { text: "بِاللهِ", trans: { ru: "в Аллаха", en: "in Allah" }, start: 0, end: 0 },
        { text: "وَالْيَوْمِ", trans: { ru: "и в день", en: "and the Day" }, start: 0, end: 0 },
        { text: "الْآخِرِ", trans: { ru: "Последний", en: "the Last" }, start: 0, end: 0 },
        { text: "فَلْيُكْرِمْ", trans: { ru: "пусть почитает", en: "let him honour" }, start: 0, end: 0 },
        { text: "جَارَهُ", trans: { ru: "своего соседа", en: "his neighbour" }, start: 0, end: 0 },
        { text: "وَمَنْ", trans: { ru: "и кто", en: "and whoever" }, start: 0, end: 0 },
        { text: "كَانَ", trans: { ru: "пребывает в том, что", en: "is such that he" }, start: 0, end: 0 },
        { text: "يُؤْمِنُ", trans: { ru: "верует", en: "believing" }, start: 0, end: 0 },
        { text: "بِاللهِ", trans: { ru: "в Аллаха", en: "in Allah" }, start: 0, end: 0 },
        { text: "وَالْيَوْمِ", trans: { ru: "и в день", en: "and the Day" }, start: 0, end: 0 },
        { text: "الْآخِرِ", trans: { ru: "Последний", en: "the Last" }, start: 0, end: 0 },
        { text: "فَلْيُكْرِمْ", trans: { ru: "пусть почитает", en: "let him honour" }, start: 0, end: 0 },
        { text: "ضَيْفَهُ", trans: { ru: "своего гостя", en: "his guest" }, start: 0, end: 0 },
      ],
    },
  ],
};
