// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/16.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3016: ChapterData = {
  id: 3016,
  collection: 'nawawi',
  title: { ru: "Не гневайся", en: "Do not become angry" },
  duas: [
    {
      id: "3016-1",
      narration: { ru: "Со слов Абу Хурайры, да будет доволен им Аллах, передаётся, что один человек сказал Пророку ﷺ: «Дай мне наставление». Он ответил: «Не гневайся». Тот повторил свою просьбу несколько раз, и он сказал:", en: "On the authority of Abu Hurayra, may Allah be pleased with him, that a man said to the Prophet ﷺ: “Counsel me.” He said: “Do not become angry.” The man repeated his request several times, and he said:" },
      fullTranslation: { ru: "Не гневайся.", en: "Do not become angry." },
      source: { ru: "аль-Бухари 6116", en: "al-Bukhari 6116" },
      sync: [
        { text: "لَا", trans: { ru: "не", en: "do not" }, start: 0, end: 0 },
        { text: "تَغْضَبْ", trans: { ru: "гневайся", en: "become angry" }, start: 0, end: 0 },
      ],
    },
  ],
};
