// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/16.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3016: ChapterData = {
  id: 3016,
  collection: 'nawawi',
  title: { ru: "Не гневайся", en: "Do not become angry" },
  duas: [
    {
      id: "3016-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/16.mp3?v=df22a702",
      narration: { ru: "От Абу Хурайры (да будет доволен им Аллах) передаётся, что некий человек сказал Пророку (да благословит его Аллах и приветствует): «Сделай мне наставление». И он ответил:", en: "On the authority of Abu Hurayra (may Allah be pleased with him), that a man said to the Prophet (may Allah bless him and grant him peace): “Counsel me.” He said:" },
      fullTranslation: { ru: "Не гневайся». И тот повторил просьбу несколько раз, а Пророк (да благословит его Аллах и приветствует) отвечал: «Не гневайся.", en: "Do not become angry.” The man repeated his request several times, and each time the Prophet (may Allah bless him and grant him peace) answered: “Do not become angry." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ.",
      note: { ru: "Хадис передал аль-Бухари.", en: "Related by al-Bukhari." },
      source: { ru: "аль-Бухари 6116", en: "al-Bukhari 6116" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.3, end: 0.6 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0.8, end: 0.9 },
        { text: "هُرَيْرَةَ", trans: { ru: "Хурайры", en: "Hurayra" }, start: 1.1, end: 1.6 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 1.9, end: 2.2 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 2.4, end: 2.6 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 2.9, end: 3.39 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 3.48, end: 4.04 },
        { text: "إِنَّ", trans: { ru: "поистине", en: "truly" }, start: 5.67, end: 5.9 },
        { text: "رَجُلاً", trans: { ru: "человек", en: "a man" }, start: 6.1, end: 6.68 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 6.77, end: 7.1 },
        { text: "لِلنَّبِيِّ", trans: { ru: "Пророку", en: "to the Prophet" }, start: 7.2, end: 7.7 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 8.1, end: 8.4 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 8.5, end: 8.7 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 9.1, end: 9.6 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 9.7, end: 10.54 },
        { text: "أَوْصِنِي", trans: { ru: "наставь меня", en: "counsel me" }, start: 11.75, end: 12.45 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 14.03, end: 14.7 },
        { text: "لَا", trans: { ru: "не", en: "do not" }, start: 16.14, end: 16.66 },
        { text: "تَغْضَبْ", trans: { ru: "гневайся", en: "become angry" }, start: 16.76, end: 17.53 },
      ],
    },
  ],
};
