// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/17.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3017: ChapterData = {
  id: 3017,
  collection: 'nawawi',
  title: { ru: "Аллах предписал совершенство во всём", en: "Allah has prescribed excellence in everything" },
  duas: [
    {
      id: "3017-1",
      narration: { ru: "Со слов Абу Я‘ля Шаддада ибн Ауса, да будет доволен им Аллах, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Abu Ya‘la Shaddad ibn Aws, may Allah be pleased with him, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Поистине, Аллах предписал совершенство во всём. Если убиваете — убивайте хорошо, если режете — режьте хорошо. И пусть каждый из вас наточит своё лезвие и избавит от мучений своё животное.", en: "Allah has prescribed excellence in everything. So if you kill, kill well; and if you slaughter, slaughter well. Let each of you sharpen his blade and spare the animal he slaughters." },
      source: { ru: "Муслим 1955", en: "Muslim 1955" },
      sync: [
        { text: "إِنَّ", trans: { ru: "поистине", en: "indeed" }, start: 0, end: 0 },
        { text: "اللهَ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "كَتَبَ", trans: { ru: "предписал", en: "has prescribed" }, start: 0, end: 0 },
        { text: "الْإِحْسَانَ", trans: { ru: "совершенство", en: "excellence" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "во", en: "upon" }, start: 0, end: 0 },
        { text: "كُلِّ", trans: { ru: "всякой", en: "every" }, start: 0, end: 0 },
        { text: "شَيْءٍ", trans: { ru: "вещи", en: "thing" }, start: 0, end: 0 },
        { text: "فَإِذَا", trans: { ru: "и если", en: "so if" }, start: 0, end: 0 },
        { text: "قَتَلْتُمْ", trans: { ru: "вы убиваете", en: "you kill" }, start: 0, end: 0 },
        { text: "فَأَحْسِنُوا", trans: { ru: "то делайте хорошо", en: "then do well" }, start: 0, end: 0 },
        { text: "الْقِتْلَةَ", trans: { ru: "убиение", en: "the killing" }, start: 0, end: 0 },
        { text: "وَإِذَا", trans: { ru: "и если", en: "and if" }, start: 0, end: 0 },
        { text: "ذَبَحْتُمْ", trans: { ru: "вы режете", en: "you slaughter" }, start: 0, end: 0 },
        { text: "فَأَحْسِنُوا", trans: { ru: "то делайте хорошо", en: "then do well" }, start: 0, end: 0 },
        { text: "الذِّبْحَةَ", trans: { ru: "заклание", en: "the slaughtering" }, start: 0, end: 0 },
        { text: "وَلْيُحِدَّ", trans: { ru: "и пусть наточит", en: "and let sharpen" }, start: 0, end: 0 },
        { text: "أَحَدُكُمْ", trans: { ru: "каждый из вас", en: "each of you" }, start: 0, end: 0 },
        { text: "شَفْرَتَهُ", trans: { ru: "своё лезвие", en: "his blade" }, start: 0, end: 0 },
        { text: "وَلْيُرِحْ", trans: { ru: "и пусть избавит от мучений", en: "and let him spare" }, start: 0, end: 0 },
        { text: "ذَبِيحَتَهُ", trans: { ru: "своё животное", en: "the animal he slaughters" }, start: 0, end: 0 },
      ],
    },
  ],
};
