// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/18.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3018: ChapterData = {
  id: 3018,
  collection: 'nawawi',
  title: { ru: "Бойся Аллаха, где бы ты ни был", en: "Fear Allah wherever you are" },
  duas: [
    {
      id: "3018-1",
      narration: { ru: "Со слов Абу Зарра Джундуба ибн Джунады и Абу Абд ар-Рахмана Му‘аза ибн Джабаля, да будет доволен ими обоими Аллах, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Abu Dharr Jundub ibn Junada and Abu Abd ar-Rahman Mu‘adh ibn Jabal, may Allah be pleased with them both, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Бойся Аллаха, где бы ты ни был; вслед за дурным поступком соверши благой, и он сотрёт его; и обращайся с людьми наилучшим нравом.", en: "Fear Allah wherever you are; follow a bad deed with a good one and it will erase it; and treat people with good character." },
      source: { ru: "ат-Тирмизи 1987", en: "at-Tirmidhi 1987" },
      sync: [
        { text: "اتَّقِ", trans: { ru: "бойся", en: "fear" }, start: 0, end: 0 },
        { text: "اللهَ", trans: { ru: "Аллаха", en: "Allah" }, start: 0, end: 0 },
        { text: "حَيْثُمَا", trans: { ru: "где бы", en: "wherever" }, start: 0, end: 0 },
        { text: "كُنْتَ", trans: { ru: "ты ни был", en: "you are" }, start: 0, end: 0 },
        { text: "وَأَتْبِعِ", trans: { ru: "и соверши вслед за", en: "and follow" }, start: 0, end: 0 },
        { text: "السَّيِّئَةَ", trans: { ru: "дурным поступком", en: "the bad deed" }, start: 0, end: 0 },
        { text: "الْحَسَنَةَ", trans: { ru: "благой", en: "with a good one" }, start: 0, end: 0 },
        { text: "تَمْحُهَا", trans: { ru: "он сотрёт его", en: "it will erase it" }, start: 0, end: 0 },
        { text: "وَخَالِقِ", trans: { ru: "и обращайся с", en: "and treat" }, start: 0, end: 0 },
        { text: "النَّاسَ", trans: { ru: "людьми", en: "people" }, start: 0, end: 0 },
        { text: "بِخُلُقٍ", trans: { ru: "нравом", en: "with character" }, start: 0, end: 0 },
        { text: "حَسَنٍ", trans: { ru: "прекрасным", en: "that is good" }, start: 0, end: 0 },
      ],
    },
  ],
};
