// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/20.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3020: ChapterData = {
  id: 3020,
  collection: 'nawawi',
  title: { ru: "Если не стыдишься — делай что хочешь", en: "If you feel no shame, do as you wish" },
  duas: [
    {
      id: "3020-1",
      narration: { ru: "От Абу Мас‘уда Укбы ибн Амра аль-Ансари аль-Бадри (да будет доволен им Аллах) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Mas'ud Uqba ibn Amr al-Ansari al-Badri (may Allah be pleased with him), that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      isnadArabic: "عَنْ أَبِي مَسْعُودٍ عُقْبَةَ بنِ عَمْرٍو الأَنْصَارِيِّ الْبَدْرِيِّ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ:",
      fullTranslation: { ru: "То, что люди сохранили из речи первых пророков: «Если тебе не стыдно, то делай, что хочешь».", en: "Among the words people have retained from the earliest prophecy is this: “If you feel no shame, then do as you wish.”" },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ.",
      note: { ru: "Хадис передал аль-Бухари.", en: "Related by al-Bukhari." },
      source: { ru: "аль-Бухари 3483", en: "al-Bukhari 3483" },
      sync: [
        { text: "إِنَّ", trans: { ru: "поистине", en: "indeed" }, start: 0, end: 0 },
        { text: "مِمَّا", trans: { ru: "из того, что", en: "among what" }, start: 0, end: 0 },
        { text: "أَدْرَكَ", trans: { ru: "застали", en: "people have received" }, start: 0, end: 0 },
        { text: "النَّاسُ", trans: { ru: "люди", en: "the people" }, start: 0, end: 0 },
        { text: "مِنْ", trans: { ru: "из", en: "of" }, start: 0, end: 0 },
        { text: "كَلَامِ", trans: { ru: "слов", en: "the words of" }, start: 0, end: 0 },
        { text: "النُّبُوَّةِ", trans: { ru: "пророчества", en: "the prophethood" }, start: 0, end: 0 },
        { text: "الْأُولَى", trans: { ru: "первого", en: "the first" }, start: 0, end: 0 },
        { text: "إِذَا", trans: { ru: "если", en: "if" }, start: 0, end: 0 },
        { text: "لَمْ", trans: { ru: "не", en: "you do not" }, start: 0, end: 0 },
        { text: "تَسْتَحِ", trans: { ru: "стыдишься ты", en: "feel shame" }, start: 0, end: 0 },
        { text: "فَاصْنَعْ", trans: { ru: "то делай", en: "then do" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "что", en: "what" }, start: 0, end: 0 },
        { text: "شِئْتَ", trans: { ru: "хочешь", en: "you wish" }, start: 0, end: 0 },
      ],
    },
  ],
};
