// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/21.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3021: ChapterData = {
  id: 3021,
  collection: 'nawawi',
  title: { ru: "Скажи: «Я уверовал в Аллаха» — и будь стоек", en: "Say “I believe in Allah”, then be steadfast" },
  duas: [
    {
      id: "3021-1",
      narration: { ru: "От Абу Амра (или Абу Амрата) Суфьяна ибн Абдуллаха (да будет доволен им Аллах) передаётся, что он сказал: «О Посланник Аллаха, скажи мне об Исламе такое, чтобы я больше никого не спрашивал». И он (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Amr — and it is also said Abu Amra — Sufyan ibn Abdillah (may Allah be pleased with him), who said: “O Messenger of Allah, tell me something about Islam about which I need ask no one after you.” He (may Allah bless him and grant him peace) said:" },
      isnadArabic: "عَنْ أَبِي عَمْرٍو وَقِيلَ أَبِي عَمْرَةَ سُفْيَانَ بْنِ عَبْدِ اللهِ رَضِيَ اللهُ عَنْهُ قَالَ:",
      fullTranslation: { ru: "Скажи: «Я уверовал в Аллаха», а затем будь стоек в соблюдении религии.", en: "Say: “I believe in Allah” — and then be steadfast." },
      takhrijArabic: "رَوَاهُ مُسْلِمٌ.",
      note: { ru: "Хадис передал Муслим.", en: "Related by Muslim." },
      source: { ru: "Муслим 38", en: "Muslim 38" },
      sync: [
        { text: "قُلْ", trans: { ru: "скажи", en: "say" }, start: 0, end: 0 },
        { text: "آمَنْتُ", trans: { ru: "я уверовал", en: "I believe" }, start: 0, end: 0 },
        { text: "بِاللهِ", trans: { ru: "в Аллаха", en: "in Allah" }, start: 0, end: 0 },
        { text: "ثُمَّ", trans: { ru: "затем", en: "then" }, start: 0, end: 0 },
        { text: "اسْتَقِمْ", trans: { ru: "будь стоек", en: "be steadfast" }, start: 0, end: 0 },
      ],
    },
  ],
};
