// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/21.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3021: ChapterData = {
  id: 3021,
  collection: 'nawawi',
  title: { ru: "Скажи: «Я уверовал в Аллаха» — и будь стоек", en: "Say “I believe in Allah”, then be steadfast" },
  duas: [
    {
      id: "3021-1",
      narration: { ru: "Со слов Абу Амра — а по другой версии Абу Амры — Суфьяна ибн Абдуллаха, да будет доволен им Аллах, передаётся, что он сказал: «Я попросил: „О посланник Аллаха, скажи мне об исламе такие слова, о которых мне не пришлось бы спрашивать никого, кроме тебя“. Он сказал…»", en: "On the authority of Abu Amr — and it is also said Abu Amra — Sufyan ibn Abdullah, may Allah be pleased with him, who said: “I said: O Messenger of Allah, tell me something about Islam which I need ask of no one but you. He said…”" },
      fullTranslation: { ru: "Скажи: «Я уверовал в Аллаха» — а затем будь стоек.", en: "Say: “I believe in Allah” — then be steadfast." },
      source: { ru: "Муслим 38", en: "Muslim 38" },
      sync: [
        { text: "قُلْ", trans: { ru: "скажи", en: "say" }, start: 0, end: 0 },
        { text: "آمَنْتُ", trans: { ru: "я уверовал", en: "I believe" }, start: 0, end: 0 },
        { text: "بِاللهِ", trans: { ru: "в Аллаха", en: "in Allah" }, start: 0, end: 0 },
        { text: "ثُمَّ", trans: { ru: "затем", en: "then" }, start: 0, end: 0 },
        { text: "اسْتَقِمْ", trans: { ru: "будь стоек", en: "be steadfast" }, start: 0, end: 0 },
      ],
    },
  ],
};
