// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/22.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3022: ChapterData = {
  id: 3022,
  collection: 'nawawi',
  title: { ru: "Обязательного достаточно для Рая", en: "The obligatory suffices for Paradise" },
  duas: [
    {
      id: "3022-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/22.mp3?v=049c5272",
      narration: { ru: "От Абу Абдуллаха Джабира ибн Абдуллаха (да будет доволен Аллах им и его отцом) передаётся, что некий человек спросил Посланника Аллаха (да благословит его Аллах и приветствует):", en: "On the authority of Abu Abdillah Jabir ibn Abdillah (may Allah be pleased with him and with his father), that a man asked the Messenger of Allah (may Allah bless him and grant him peace):" },
      fullTranslation: { ru: "Если я буду совершать обязательные намазы, поститься в Рамадан, буду считать дозволенное дозволенным, а запретное запретным, и ничего больше не добавлю к этому, то войду ли я в Рай?» И он (да благословит его Аллах и приветствует) ответил: «Да.", en: "If I pray the obligatory prayers, fast Ramadan, treat as lawful what is lawful and as forbidden what is forbidden, and add nothing to that — shall I enter Paradise?” He (may Allah bless him and grant him peace) said: “Yes." },
      takhrijArabic: "رَوَاهُ مُسْلِمٌ.",
      note: { ru: "Хадис передал Муслим. Смысл слов «считать запретное запретным» — сторониться его, а «считать дозволенное дозволенным» — совершать его, убеждённо признавая дозволенным.", en: "Related by Muslim. To “treat as forbidden what is forbidden” means to avoid it; to “treat as lawful what is lawful” means to do it while holding the conviction that it is lawful." },
      source: { ru: "Муслим 15", en: "Muslim 15" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.73, end: 1.12 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 1.25, end: 1.47 },
        { text: "عَبْدِ", trans: { ru: "Абд", en: "Abd" }, start: 1.47, end: 1.95 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 1.95, end: 2.29 },
        { text: "جَابِرِ", trans: { ru: "Джабира", en: "Jabir" }, start: 2.29, end: 3.33 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 3.33, end: 3.49 },
        { text: "عَبْدِ", trans: { ru: "Абд", en: "Abd" }, start: 3.49, end: 3.97 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 3.97, end: 4.68 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 5.14, end: 5.4 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 5.4, end: 5.66 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 5.66, end: 6.91 },
        { text: "أَرَأَيْتَ", trans: { ru: "скажи мне", en: "tell me" }, start: 8.66, end: 9.38 },
        { text: "إِذَا", trans: { ru: "если", en: "if" }, start: 9.46, end: 9.65 },
        { text: "صَلَّيْتُ", trans: { ru: "я совершу", en: "I pray" }, start: 9.65, end: 10.45 },
        { text: "الْمَكْتُوبَاتِ", trans: { ru: "предписанные молитвы", en: "the obligatory prayers" }, start: 10.45, end: 11.94 },
        { text: "وَصُمْتُ", trans: { ru: "и буду поститься", en: "and fast" }, start: 12.42, end: 12.97 },
        { text: "رَمَضَانَ", trans: { ru: "в рамадан", en: "Ramadan" }, start: 13.06, end: 14.06 },
        { text: "وَأَحْلَلْتُ", trans: { ru: "и сочту дозволенным", en: "and treat as lawful" }, start: 14.79, end: 15.6 },
        { text: "الْحَلَالَ", trans: { ru: "дозволенное", en: "the lawful" }, start: 15.6, end: 16.72 },
        { text: "وَحَرَّمْتُ", trans: { ru: "и сочту запретным", en: "and treat as unlawful" }, start: 17.07, end: 17.9 },
        { text: "الْحَرَامَ", trans: { ru: "запретное", en: "the unlawful" }, start: 18, end: 18.79 },
        { text: "وَلَمْ", trans: { ru: "и не", en: "and do not" }, start: 18.79, end: 20.06 },
        { text: "أَزِدْ", trans: { ru: "прибавлю", en: "add" }, start: 20.19, end: 20.43 },
        { text: "عَلَى", trans: { ru: "к", en: "to" }, start: 20.43, end: 20.71 },
        { text: "ذَلِكَ", trans: { ru: "этому", en: "that" }, start: 20.71, end: 21.53 },
        { text: "شَيْئًا", trans: { ru: "ничего", en: "anything" }, start: 21.53, end: 22.41 },
        { text: "أَأَدْخُلُ", trans: { ru: "войду ли я", en: "shall I enter" }, start: 23.18, end: 23.81 },
        { text: "الْجَنَّةَ", trans: { ru: "в Рай", en: "Paradise" }, start: 23.81, end: 24.55 },
        { text: "قَالَ", trans: { ru: "он сказал", en: "he said" }, start: 25.66, end: 26.26 },
        { text: "نَعَمْ", trans: { ru: "да", en: "yes" }, start: 26.95, end: 27.53 },
      ],
    },
  ],
};
