// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/22.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3022: ChapterData = {
  id: 3022,
  collection: 'nawawi',
  title: { ru: "Обязательного достаточно для Рая", en: "The obligatory suffices for Paradise" },
  duas: [
    {
      id: "3022-1",
      narration: { ru: "Со слов Абу Абдиллях Джабира ибн Абдиллях аль-Ансари, да будет доволен Аллах ими обоими, передаётся, что один человек спросил посланника Аллаха ﷺ:", en: "On the authority of Abu Abdillah Jabir ibn Abdillah al-Ansari, may Allah be pleased with them both, that a man questioned the Messenger of Allah ﷺ, saying:" },
      fullTranslation: { ru: "«Скажи мне, если я стану совершать обязательные молитвы, поститься в рамадан, считать дозволенным дозволенное и запретным запретное и ничего к этому не прибавлю — войду ли я в Рай?» Он ответил: «Да».", en: "“Tell me: if I pray the obligatory prayers, fast Ramadan, treat the lawful as lawful and the unlawful as unlawful, and add nothing to that — shall I enter Paradise?” He said: “Yes.”" },
      source: { ru: "Муслим 15", en: "Muslim 15" },
      sync: [
        { text: "أَرَأَيْتَ", trans: { ru: "скажи мне", en: "tell me" }, start: 0, end: 0 },
        { text: "إِذَا", trans: { ru: "если", en: "if" }, start: 0, end: 0 },
        { text: "صَلَّيْتُ", trans: { ru: "я совершу", en: "I pray" }, start: 0, end: 0 },
        { text: "الْمَكْتُوبَاتِ", trans: { ru: "предписанные молитвы", en: "the obligatory prayers" }, start: 0, end: 0 },
        { text: "وَصُمْتُ", trans: { ru: "и буду поститься", en: "and fast" }, start: 0, end: 0 },
        { text: "رَمَضَانَ", trans: { ru: "в рамадан", en: "Ramadan" }, start: 0, end: 0 },
        { text: "وَأَحْلَلْتُ", trans: { ru: "и сочту дозволенным", en: "and treat as lawful" }, start: 0, end: 0 },
        { text: "الْحَلَالَ", trans: { ru: "дозволенное", en: "the lawful" }, start: 0, end: 0 },
        { text: "وَحَرَّمْتُ", trans: { ru: "и сочту запретным", en: "and treat as unlawful" }, start: 0, end: 0 },
        { text: "الْحَرَامَ", trans: { ru: "запретное", en: "the unlawful" }, start: 0, end: 0 },
        { text: "وَلَمْ", trans: { ru: "и не", en: "and do not" }, start: 0, end: 0 },
        { text: "أَزِدْ", trans: { ru: "прибавлю", en: "add" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "к", en: "to" }, start: 0, end: 0 },
        { text: "ذَلِكَ", trans: { ru: "этому", en: "that" }, start: 0, end: 0 },
        { text: "شَيْئًا", trans: { ru: "ничего", en: "anything" }, start: 0, end: 0 },
        { text: "أَأَدْخُلُ", trans: { ru: "войду ли я", en: "shall I enter" }, start: 0, end: 0 },
        { text: "الْجَنَّةَ", trans: { ru: "в Рай", en: "Paradise" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "он сказал", en: "he said" }, start: 0, end: 0 },
        { text: "نَعَمْ", trans: { ru: "да", en: "yes" }, start: 0, end: 0 },
      ],
    },
  ],
};
