// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/22.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3022: ChapterData = {
  id: 3022,
  collection: 'nawawi',
  title: { ru: "Обязательного достаточно для Рая", en: "The obligatory suffices for Paradise" },
  duas: [
    {
      id: "3022-1",
      narration: { ru: "От Абу Абдуллаха Джабира ибн Абдуллаха (да будет доволен Аллах им и его отцом) передаётся, что некий человек спросил Посланника Аллаха (да благословит его Аллах и приветствует):", en: "On the authority of Abu Abdillah Jabir ibn Abdillah (may Allah be pleased with him and with his father), that a man asked the Messenger of Allah (may Allah bless him and grant him peace):" },
      fullTranslation: { ru: "Если я буду совершать обязательные намазы, поститься в Рамадан, буду считать дозволенное дозволенным, а запретное запретным, и ничего больше не добавлю к этому, то войду ли я в Рай?» И он (да благословит его Аллах и приветствует) ответил: «Да.", en: "If I pray the obligatory prayers, fast Ramadan, treat as lawful what is lawful and as forbidden what is forbidden, and add nothing to that — shall I enter Paradise?” He (may Allah bless him and grant him peace) said: “Yes." },
      takhrijArabic: "رَوَاهُ مُسْلِمٌ.",
      note: { ru: "Хадис передал Муслим. Смысл слов «считать запретное запретным» — сторониться его, а «считать дозволенное дозволенным» — совершать его, убеждённо признавая дозволенным.", en: "Related by Muslim. To “treat as forbidden what is forbidden” means to avoid it; to “treat as lawful what is lawful” means to do it while holding the conviction that it is lawful." },
      source: { ru: "Муслим 15", en: "Muslim 15" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0, end: 0 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0, end: 0 },
        { text: "عَبْدِ", trans: { ru: "Абд", en: "Abd" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 0, end: 0 },
        { text: "جَابِرِ", trans: { ru: "Джабира", en: "Jabir" }, start: 0, end: 0 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 0, end: 0 },
        { text: "عَبْدِ", trans: { ru: "Абд", en: "Abd" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 0, end: 0 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 0, end: 0 },
        { text: "أَرَأَيْتَ", trans: { ru: "скажи мне", en: "tell me" }, start: 0, end: 0 },
        { text: "إِذَا", trans: { ru: "если", en: "if" }, start: 0, end: 0 },
        { text: "صَلَّيْتُ", trans: { ru: "я совершу", en: "I pray" }, start: 0, end: 0 },
        { text: "الْمَكْتُوبَاتِ", trans: { ru: "предписанные молитвы", en: "the obligatory prayers" }, start: 0, end: 0 },
        { text: "وَصُمْتُ", trans: { ru: "и буду поститься", en: "and fast" }, start: 0, end: 0 },
        { text: "رَمَضَانَ", trans: { ru: "в рамадан", en: "Ramadan" }, start: 0, end: 0 },
        { text: "وَأَحْلَلْتُ", trans: { ru: "и сочту дозволенным", en: "and treat as lawful" }, start: 0, end: 0 },
        { text: "الْحَلَالَ", trans: { ru: "дозволенное", en: "the lawful" }, start: 0, end: 0 },
        { text: "وَحَرَّمْتُ", trans: { ru: "и сочту запретным", en: "and treat as unlawful" }, start: 0, end: 0 },
        { text: "الْحَرَامَ", trans: { ru: "запретное", en: "the unlawful" }, start: 0, end: 0 },
        { text: "وَلَمْ", trans: { ru: "и не", en: "and do not" }, start: 0, end: 0 },
        { text: "أَزِدْ", trans: { ru: "прибавлю", en: "add" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "к", en: "to" }, start: 0, end: 0 },
        { text: "ذَلِكَ", trans: { ru: "этому", en: "that" }, start: 0, end: 0 },
        { text: "شَيْئًا", trans: { ru: "ничего", en: "anything" }, start: 0, end: 0 },
        { text: "أَأَدْخُلُ", trans: { ru: "войду ли я", en: "shall I enter" }, start: 0, end: 0 },
        { text: "الْجَنَّةَ", trans: { ru: "в Рай", en: "Paradise" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "он сказал", en: "he said" }, start: 0, end: 0 },
        { text: "نَعَمْ", trans: { ru: "да", en: "yes" }, start: 0, end: 0 },
      ],
    },
  ],
};
