// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/27.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3027: ChapterData = {
  id: 3027,
  collection: 'nawawi',
  title: { ru: "Благочестие — это благонравие", en: "Righteousness is good character" },
  duas: [
    {
      id: "3027-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/27.mp3",
      narration: { ru: "От ан-Навваса ибн Сам‘ана (да будет доволен им Аллах) передаётся, что Пророк (да благословит его Аллах и приветствует) сказал:", en: "On the authority of an-Nawwas ibn Sam'an (may Allah be pleased with him), that the Prophet (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Набожность — это благой нрав, а грех — это то, что тревожит твою душу и тебе ненавистно, чтобы об этом узнали другие.", en: "Righteousness is good character, and sin is what wavers in your soul and which you would hate for people to find out about." },
      takhrijArabic: "رَوَاهُ مُسْلِمٌ.",
      note: { ru: "Хадис передал Муслим. От Вабиса ибн Ма‘бада (да будет доволен им Аллах) передаётся: «Я пришёл к Посланнику Аллаха (да благословит его Аллах и приветствует), и он сказал: “Ты пришёл, чтобы спросить о грехе и набожности?” И я ответил: “Да”. И он сказал: “Спроси своё сердце. Набожность — это то, в чём ты уверен и в чём твоё сердце спокойно, а грех — это то, что тебя терзает и о чём ты сомневаешься, даже если тебе дали ответ”». Хадис хороший, его передали имамы Ахмад и ад-Дарими в своих «Муснадах» с хорошим иснадом.", en: "Related by Muslim. On the authority of Wabisa ibn Ma'bad (may Allah be pleased with him): “I came to the Messenger of Allah (may Allah bless him and grant him peace) and he said: ‘You have come to ask about righteousness and sin?’ I said: ‘Yes.’ He said: ‘Consult your heart. Righteousness is that about which the soul feels at ease and the heart feels tranquil, and sin is what wavers in the soul and moves to and fro in the breast, even though people give you their opinion again and again.’” A hasan hadith, related by the imams Ahmad and ad-Darimi in their Musnads with a good chain." },
      source: { ru: "Муслим 2553", en: "Muslim 2553" },
      sync: [
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 0.18, end: 0.4 },
        { text: "النَّوَّاسِ", trans: { ru: "ан-Навваса", en: "an-Nawwas" }, start: 0.4, end: 1.64 },
        { text: "بنِ", trans: { ru: "ибн", en: "son of" }, start: 1.64, end: 1.8 },
        { text: "سَمْعَانَ", trans: { ru: "Сам‘ана", en: "Sam'an" }, start: 1.8, end: 2.78 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 2.78, end: 3.34 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 3.34, end: 3.58 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 3.58, end: 4.46 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 4.46, end: 4.8 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 6.45, end: 6.61 },
        { text: "رَسُولُ", trans: { ru: "Посланник", en: "the Messenger of" }, start: 6.61, end: 7.43 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 7.43, end: 7.81 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 7.81, end: 8.49 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 8.49, end: 8.93 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 8.93, end: 9.59 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 9.59, end: 10.49 },
        { text: "الْبِرُّ", trans: { ru: "благочестие", en: "righteousness" }, start: 12.54, end: 13.16 },
        { text: "حُسْنُ", trans: { ru: "благо", en: "is the goodness of" }, start: 13.16, end: 14 },
        { text: "الْخُلُقِ", trans: { ru: "нрава", en: "character" }, start: 14, end: 14.72 },
        { text: "وَالْإِثْمُ", trans: { ru: "а грех", en: "and sin" }, start: 16.68, end: 17.56 },
        { text: "مَا", trans: { ru: "то, что", en: "is what" }, start: 17.56, end: 17.88 },
        { text: "حَاكَ", trans: { ru: "колеблется", en: "wavers" }, start: 17.88, end: 18.54 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 18.54, end: 18.78 },
        { text: "نَفْسِكَ", trans: { ru: "твоей душе", en: "your soul" }, start: 18.78, end: 19.6 },
        { text: "وَكَرِهْتَ", trans: { ru: "и ты не желаешь", en: "and you dislike" }, start: 20.88, end: 21.8 },
        { text: "أَنْ", trans: { ru: "чтобы", en: "that" }, start: 21.8, end: 22 },
        { text: "يَطَّلِعَ", trans: { ru: "узнали", en: "should learn" }, start: 22, end: 23.04 },
        { text: "عَلَيْهِ", trans: { ru: "о нём", en: "of it" }, start: 23.04, end: 23.44 },
        { text: "النَّاسُ", trans: { ru: "люди", en: "the people" }, start: 23.44, end: 24.42 },
      ],
    },
  ],
};
