// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/27.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3027: ChapterData = {
  id: 3027,
  collection: 'nawawi',
  title: { ru: "Благочестие — это благонравие", en: "Righteousness is good character" },
  duas: [
    {
      id: "3027-1",
      narration: { ru: "Со слов ан-Наваса ибн Сам‘ана, да будет доволен им Аллах, передаётся, что Пророк ﷺ сказал:", en: "On the authority of an-Nawwas ibn Sam‘an, may Allah be pleased with him, that the Prophet ﷺ said:" },
      fullTranslation: { ru: "Благочестие — это благонравие, а грех — то, что колеблется в твоей душе и что тебе не хочется открыть людям.", en: "Righteousness is good character, and sin is what wavers in your soul and what you would dislike people to find out about." },
      note: { ru: "К этому хадису ан-Навави присоединил хадис Вабисы ибн Ма‘бада: «Спроси своё сердце: благочестие — то, на чём душа успокаивается и на чём успокаивается сердце, а грех — то, что колеблется в душе и мечется в груди, даже если люди станут выносить тебе решение за решением» (Ахмад, ад-Дарими).", en: "An-Nawawi joined to this the hadith of Wabisa ibn Ma‘bad: “Consult your heart. Righteousness is that with which the soul is at rest and the heart is at rest, and sin is what wavers in the soul and moves to and fro in the breast, even if people give you their verdict again and again” (Ahmad, ad-Darimi)." },
      source: { ru: "Муслим 2553", en: "Muslim 2553" },
      sync: [
        { text: "الْبِرُّ", trans: { ru: "благочестие", en: "righteousness" }, start: 0, end: 0 },
        { text: "حُسْنُ", trans: { ru: "благо", en: "is the goodness of" }, start: 0, end: 0 },
        { text: "الْخُلُقِ", trans: { ru: "нрава", en: "character" }, start: 0, end: 0 },
        { text: "وَالْإِثْمُ", trans: { ru: "а грех", en: "and sin" }, start: 0, end: 0 },
        { text: "مَا", trans: { ru: "то, что", en: "is what" }, start: 0, end: 0 },
        { text: "حَاكَ", trans: { ru: "колеблется", en: "wavers" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 0, end: 0 },
        { text: "نَفْسِكَ", trans: { ru: "твоей душе", en: "your soul" }, start: 0, end: 0 },
        { text: "وَكَرِهْتَ", trans: { ru: "и ты не желаешь", en: "and you dislike" }, start: 0, end: 0 },
        { text: "أَنْ", trans: { ru: "чтобы", en: "that" }, start: 0, end: 0 },
        { text: "يَطَّلِعَ", trans: { ru: "узнали", en: "should learn" }, start: 0, end: 0 },
        { text: "عَلَيْهِ", trans: { ru: "о нём", en: "of it" }, start: 0, end: 0 },
        { text: "النَّاسُ", trans: { ru: "люди", en: "the people" }, start: 0, end: 0 },
      ],
    },
  ],
};
