// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/28.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3028: ChapterData = {
  id: 3028,
  collection: 'nawawi',
  title: { ru: "Держитесь моей сунны", en: "Hold fast to my sunnah" },
  duas: [
    {
      id: "3028-1",
      narration: { ru: "Со слов Абу Наджиха аль-Ирбада ибн Сарии, да будет доволен им Аллах, передаётся, что он сказал: «Посланник Аллаха ﷺ обратился к нам с проповедью, от которой затрепетали сердца и пролились слёзы. Мы сказали: „О посланник Аллаха, будто это прощальная проповедь; дай же нам наставление“. Он сказал…»", en: "On the authority of Abu Najih al-Irbad ibn Sariya, may Allah be pleased with him, who said: “The Messenger of Allah ﷺ gave us an admonition that made our hearts tremble and our eyes shed tears. We said: O Messenger of Allah, it is as if this were a farewell sermon, so counsel us. He said…”" },
      fullTranslation: { ru: "Заповедую вам страх перед Аллахом, а также слушаться и повиноваться, даже если станет править вами раб. Ибо тот из вас, кто проживёт долго, увидит много разногласий. Так держитесь же моей сунны и сунны праведных халифов, ведомых прямым путём, — вцепитесь в неё коренными зубами. И остерегайтесь новшеств в делах, ибо всякое новшество — заблуждение.", en: "I counsel you to fear Allah, and to hear and obey even if a slave is set over you. Whoever among you lives long will see much disagreement. So hold fast to my sunnah and the sunnah of the rightly guided caliphs — bite onto it with your molars. And beware of newly invented matters, for every innovation is misguidance." },
      source: { ru: "Абу Дауд 4607; ат-Тирмизи 2676", en: "Abu Dawud 4607; at-Tirmidhi 2676" },
      sync: [
        { text: "أُوصِيكُمْ", trans: { ru: "заповедую вам", en: "I counsel you" }, start: 0, end: 0 },
        { text: "بِتَقْوَى", trans: { ru: "страх перед", en: "to fear" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллахом", en: "Allah" }, start: 0, end: 0 },
        { text: "وَالسَّمْعِ", trans: { ru: "и слушаться", en: "and to hear" }, start: 0, end: 0 },
        { text: "وَالطَّاعَةِ", trans: { ru: "и повиноваться", en: "and to obey" }, start: 0, end: 0 },
        { text: "وَإِنْ", trans: { ru: "даже если", en: "even if" }, start: 0, end: 0 },
        { text: "تَأَمَّرَ", trans: { ru: "станет править", en: "is set as ruler" }, start: 0, end: 0 },
        { text: "عَلَيْكُمْ", trans: { ru: "вами", en: "over you" }, start: 0, end: 0 },
        { text: "عَبْدٌ", trans: { ru: "раб", en: "a slave" }, start: 0, end: 0 },
        { text: "فَإِنَّهُ", trans: { ru: "ибо поистине", en: "for indeed" }, start: 0, end: 0 },
        { text: "مَنْ", trans: { ru: "кто", en: "whoever" }, start: 0, end: 0 },
        { text: "يَعِشْ", trans: { ru: "проживёт", en: "lives" }, start: 0, end: 0 },
        { text: "مِنْكُمْ", trans: { ru: "из вас", en: "of you" }, start: 0, end: 0 },
        { text: "فَسَيَرَى", trans: { ru: "тот увидит", en: "will see" }, start: 0, end: 0 },
        { text: "اخْتِلَافًا", trans: { ru: "разногласий", en: "disagreement" }, start: 0, end: 0 },
        { text: "كَثِيرًا", trans: { ru: "много", en: "much" }, start: 0, end: 0 },
        { text: "فَعَلَيْكُمْ", trans: { ru: "так держитесь же", en: "so hold fast" }, start: 0, end: 0 },
        { text: "بِسُنَّتِي", trans: { ru: "моей сунны", en: "to my sunnah" }, start: 0, end: 0 },
        { text: "وَسُنَّةِ", trans: { ru: "и сунны", en: "and the sunnah of" }, start: 0, end: 0 },
        { text: "الْخُلَفَاءِ", trans: { ru: "халифов", en: "the caliphs" }, start: 0, end: 0 },
        { text: "الرَّاشِدِينَ", trans: { ru: "праведных", en: "the rightly guided" }, start: 0, end: 0 },
        { text: "الْمَهْدِيِّينَ", trans: { ru: "ведомых прямым путём", en: "the guided" }, start: 0, end: 0 },
        { text: "عَضُّوا", trans: { ru: "вцепитесь", en: "bite" }, start: 0, end: 0 },
        { text: "عَلَيْهَا", trans: { ru: "в неё", en: "onto it" }, start: 0, end: 0 },
        { text: "بِالنَّوَاجِذِ", trans: { ru: "коренными зубами", en: "with the molars" }, start: 0, end: 0 },
        { text: "وَإِيَّاكُمْ", trans: { ru: "и остерегайтесь", en: "and beware" }, start: 0, end: 0 },
        { text: "وَمُحْدَثَاتِ", trans: { ru: "новшеств", en: "of the newly invented" }, start: 0, end: 0 },
        { text: "الْأُمُورِ", trans: { ru: "в делах", en: "matters" }, start: 0, end: 0 },
        { text: "فَإِنَّ", trans: { ru: "ибо поистине", en: "for indeed" }, start: 0, end: 0 },
        { text: "كُلَّ", trans: { ru: "всякое", en: "every" }, start: 0, end: 0 },
        { text: "بِدْعَةٍ", trans: { ru: "новшество", en: "innovation" }, start: 0, end: 0 },
        { text: "ضَلَالَةٌ", trans: { ru: "заблуждение", en: "is misguidance" }, start: 0, end: 0 },
      ],
    },
  ],
};
