// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/30.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3030: ChapterData = {
  id: 3030,
  collection: 'nawawi',
  title: { ru: "Границы, установленные Аллахом", en: "The limits Allah has set" },
  duas: [
    {
      id: "3030-1",
      narration: { ru: "Со слов Абу Са‘лябы аль-Хушани Джурсума ибн Насира, да будет доволен им Аллах, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Abu Tha‘laba al-Khushani Jurthum ibn Nashir, may Allah be pleased with him, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Поистине, Аллах Всевышний вменил в обязанность предписания — не теряйте же их; установил границы — не преступайте же их; запретил вещи — не нарушайте же их; и умолчал о вещах по милости к вам, а не по забывчивости — не доискивайтесь же их.", en: "Allah the Exalted has laid down obligations, so do not neglect them; He has set limits, so do not transgress them; He has forbidden things, so do not violate them; and He has been silent about things out of mercy to you, not out of forgetfulness, so do not go searching after them." },
      source: { ru: "ад-Даракутни 4/184", en: "ad-Daraqutni 4/184" },
      sync: [
        { text: "إِنَّ", trans: { ru: "поистине", en: "indeed" }, start: 0, end: 0 },
        { text: "اللهَ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "تَعَالَى", trans: { ru: "Всевышний", en: "the Exalted" }, start: 0, end: 0 },
        { text: "فَرَضَ", trans: { ru: "вменил в обязанность", en: "has laid down" }, start: 0, end: 0 },
        { text: "فَرَائِضَ", trans: { ru: "предписания", en: "obligations" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تُضَيِّعُوهَا", trans: { ru: "теряйте их", en: "neglect them" }, start: 0, end: 0 },
        { text: "وَحَدَّ", trans: { ru: "и установил", en: "and He has set" }, start: 0, end: 0 },
        { text: "حُدُودًا", trans: { ru: "границы", en: "limits" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تَعْتَدُوهَا", trans: { ru: "преступайте их", en: "transgress them" }, start: 0, end: 0 },
        { text: "وَحَرَّمَ", trans: { ru: "и запретил", en: "and He has forbidden" }, start: 0, end: 0 },
        { text: "أَشْيَاءَ", trans: { ru: "вещи", en: "things" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تَنْتَهِكُوهَا", trans: { ru: "нарушайте их", en: "violate them" }, start: 0, end: 0 },
        { text: "وَسَكَتَ", trans: { ru: "и умолчал", en: "and He was silent" }, start: 0, end: 0 },
        { text: "عَنْ", trans: { ru: "о", en: "about" }, start: 0, end: 0 },
        { text: "أَشْيَاءَ", trans: { ru: "вещах", en: "things" }, start: 0, end: 0 },
        { text: "رَحْمَةً", trans: { ru: "по милости", en: "as a mercy" }, start: 0, end: 0 },
        { text: "لَكُمْ", trans: { ru: "к вам", en: "to you" }, start: 0, end: 0 },
        { text: "غَيْرَ", trans: { ru: "не по", en: "not out of" }, start: 0, end: 0 },
        { text: "نِسْيَانٍ", trans: { ru: "забывчивости", en: "forgetfulness" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تَبْحَثُوا", trans: { ru: "доискивайтесь", en: "search" }, start: 0, end: 0 },
        { text: "عَنْهَا", trans: { ru: "их", en: "after them" }, start: 0, end: 0 },
      ],
    },
  ],
};
