// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/30.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3030: ChapterData = {
  id: 3030,
  collection: 'nawawi',
  title: { ru: "Границы, установленные Аллахом", en: "The limits Allah has set" },
  duas: [
    {
      id: "3030-1",
      narration: { ru: "От Абу Са‘ляба аль-Хушани Джурсума ибн Нашира (да будет доволен им Аллах) передаётся, что Пророк (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Tha'laba al-Khushani Jurthum ibn Nashir (may Allah be pleased with him), that the Prophet (may Allah bless him and grant him peace) said:" },
      isnadArabic: "عَنْ أَبِي ثَعْلَبَةَ الْخُشَنِيِّ جُرْثُومِ بنِ نَاشِرٍ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ:",
      fullTranslation: { ru: "Всевышний Аллах вменил обязательные действия: не пренебрегайте ими. Всевышний Аллах установил границы: не переходите их. И также Он запретил некоторые вещи: не нарушайте их. А о некоторых вещах Он умолчал в виде милости для вас, а не по забывчивости. Не надо доискиваться их!", en: "Allah has laid down obligations, so do not neglect them. He has set limits, so do not transgress them. He has forbidden certain things, so do not violate them. And He has been silent about certain things, as a mercy to you and not out of forgetfulness — so do not go searching after them." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ، رَوَاهُ الدَّارَقُطْنِيُّ وَغَيْرُهُ.",
      note: { ru: "Хадис хороший, передал его ад-Даракутни и другие.", en: "A hasan hadith, related by ad-Daraqutni and others." },
      source: { ru: "ад-Даракутни 4/184", en: "ad-Daraqutni 4/184" },
      sync: [
        { text: "إِنَّ", trans: { ru: "поистине", en: "indeed" }, start: 0, end: 0 },
        { text: "اللهَ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "تَعَالَى", trans: { ru: "Всевышний", en: "the Exalted" }, start: 0, end: 0 },
        { text: "فَرَضَ", trans: { ru: "вменил в обязанность", en: "has laid down" }, start: 0, end: 0 },
        { text: "فَرَائِضَ", trans: { ru: "предписания", en: "obligations" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تُضَيِّعُوهَا", trans: { ru: "теряйте их", en: "neglect them" }, start: 0, end: 0 },
        { text: "وَحَدَّ", trans: { ru: "и установил", en: "and He has set" }, start: 0, end: 0 },
        { text: "حُدُودًا", trans: { ru: "границы", en: "limits" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تَعْتَدُوهَا", trans: { ru: "преступайте их", en: "transgress them" }, start: 0, end: 0 },
        { text: "وَحَرَّمَ", trans: { ru: "и запретил", en: "and He has forbidden" }, start: 0, end: 0 },
        { text: "أَشْيَاءَ", trans: { ru: "вещи", en: "things" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تَنْتَهِكُوهَا", trans: { ru: "нарушайте их", en: "violate them" }, start: 0, end: 0 },
        { text: "وَسَكَتَ", trans: { ru: "и умолчал", en: "and He was silent" }, start: 0, end: 0 },
        { text: "عَنْ", trans: { ru: "о", en: "about" }, start: 0, end: 0 },
        { text: "أَشْيَاءَ", trans: { ru: "вещах", en: "things" }, start: 0, end: 0 },
        { text: "رَحْمَةً", trans: { ru: "по милости", en: "as a mercy" }, start: 0, end: 0 },
        { text: "لَكُمْ", trans: { ru: "к вам", en: "to you" }, start: 0, end: 0 },
        { text: "غَيْرَ", trans: { ru: "не по", en: "not out of" }, start: 0, end: 0 },
        { text: "نِسْيَانٍ", trans: { ru: "забывчивости", en: "forgetfulness" }, start: 0, end: 0 },
        { text: "فَلَا", trans: { ru: "так не", en: "so do not" }, start: 0, end: 0 },
        { text: "تَبْحَثُوا", trans: { ru: "доискивайтесь", en: "search" }, start: 0, end: 0 },
        { text: "عَنْهَا", trans: { ru: "их", en: "after them" }, start: 0, end: 0 },
      ],
    },
  ],
};
