// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/31.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3031: ChapterData = {
  id: 3031,
  collection: 'nawawi',
  title: { ru: "Отрешись от мирского — и тебя полюбит Аллах", en: "Renounce the world and Allah will love you" },
  duas: [
    {
      id: "3031-1",
      narration: { ru: "Со слов Абу-ль-Аббаса Сахля ибн Са‘да ас-Са‘иди, да будет доволен им Аллах, передаётся, что один человек пришёл к Пророку ﷺ и сказал: «О посланник Аллаха, укажи мне на дело, за которое меня полюбит Аллах и полюбят люди». Он сказал:", en: "On the authority of Abu al-Abbas Sahl ibn Sa‘d as-Sa‘idi, may Allah be pleased with him, that a man came to the Prophet ﷺ and said: “O Messenger of Allah, direct me to a deed for which Allah will love me and people will love me.” He said:" },
      fullTranslation: { ru: "Отрешись от мирского — и тебя полюбит Аллах; отрешись от того, что в руках людей, — и тебя полюбят люди.", en: "Renounce the world and Allah will love you; renounce what is in the hands of people and people will love you." },
      source: { ru: "Ибн Маджа 4102", en: "Ibn Majah 4102" },
      sync: [
        { text: "ازْهَدْ", trans: { ru: "отрешись", en: "renounce" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "от", en: "the" }, start: 0, end: 0 },
        { text: "الدُّنْيَا", trans: { ru: "мирского", en: "world" }, start: 0, end: 0 },
        { text: "يُحِبَّكَ", trans: { ru: "полюбит тебя", en: "and will love you" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "وَازْهَدْ", trans: { ru: "и отрешись", en: "and renounce" }, start: 0, end: 0 },
        { text: "فِيمَا", trans: { ru: "от того, что", en: "what" }, start: 0, end: 0 },
        { text: "عِنْدَ", trans: { ru: "у", en: "is with" }, start: 0, end: 0 },
        { text: "النَّاسِ", trans: { ru: "людей", en: "the people" }, start: 0, end: 0 },
        { text: "يُحِبَّكَ", trans: { ru: "полюбят тебя", en: "and will love you" }, start: 0, end: 0 },
        { text: "النَّاسُ", trans: { ru: "люди", en: "the people" }, start: 0, end: 0 },
      ],
    },
  ],
};
