// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/32.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3032: ChapterData = {
  id: 3032,
  collection: 'nawawi',
  title: { ru: "Не причинять вреда и не отвечать вредом", en: "There is no harm and no reciprocating harm" },
  duas: [
    {
      id: "3032-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/32.mp3?v=a8780726",
      narration: { ru: "От Абу Саида Са‘да ибн Малика ибн Синана аль-Худри (да будет доволен им Аллах) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Sa'id Sa'd ibn Malik ibn Sinan al-Khudri (may Allah be pleased with him), that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Нет причинению вреда ни себе, ни другим.", en: "There should be neither harming nor reciprocating harm." },
      takhrijArabic: "حديث حسن رواه ابن ماجه، والدارقطني مسندا، ورواه مالك في الموطأ مرسلا، عن عمرو بن يحيى، عن أبيه، عن النبي صلى الله عليه وسلم، فأسقط أبا سعيد، وله طرق يقوي بعضها بعضا.",
      note: { ru: "Хадис хороший, его передали Ибн Маджа и ад-Даракутни в «Муснаде», а также Малик в «Муватта» в виде мурсаль, от Амра ибн Яхьи от его отца от Пророка (да благословит его Аллах и приветствует). В его иснаде отсутствует Абу Саид. У него существуют пути, которые укрепляют друг друга.", en: "A hasan hadith, related by Ibn Maja and by ad-Daraqutni with a connected chain, and by Malik in the Muwatta in mursal form from Amr ibn Yahya from his father from the Prophet (may Allah bless him and grant him peace), omitting Abu Sa'id. It has several routes that strengthen one another." },
      source: { ru: "Ибн Маджа 2341; ад-Даракутни 4/228", en: "Ibn Majah 2341; ad-Daraqutni 4/228" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.35, end: 0.67 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0.73, end: 1.21 },
        { text: "سَعِيدٍ", trans: { ru: "Саида", en: "Sa'id" }, start: 1.21, end: 1.9 },
        { text: "سَعْدِ", trans: { ru: "Са‘да", en: "Sa'd" }, start: 2.28, end: 2.78 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 2.78, end: 2.97 },
        { text: "مَالِكِ", trans: { ru: "Малика", en: "Malik" }, start: 2.97, end: 3.43 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 3.5, end: 3.84 },
        { text: "سِنَانٍ", trans: { ru: "Синана", en: "Sinan" }, start: 3.84, end: 4.51 },
        { text: "الْخُدْرِيِّ", trans: { ru: "аль-Худри", en: "al-Khudri" }, start: 4.51, end: 5.24 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 5.77, end: 6.1 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 6.1, end: 6.36 },
        { text: "عَنْهُ", trans: { ru: "им", en: "with him" }, start: 6.36, end: 7.1 },
        { text: "أَنَّ", trans: { ru: "что", en: "that" }, start: 8.03, end: 8.21 },
        { text: "رَسُولَ", trans: { ru: "посланника", en: "the Messenger of" }, start: 8.21, end: 8.82 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 8.82, end: 9.11 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 9.11, end: 9.85 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 9.85, end: 10.19 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 10.19, end: 10.75 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 10.75, end: 11.54 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 11.54, end: 11.9 },
        { text: "لَا", trans: { ru: "нет", en: "there is no" }, start: 12.86, end: 13.1 },
        { text: "ضَرَرَ", trans: { ru: "вреда", en: "harm" }, start: 13.1, end: 13.7 },
        { text: "وَلَا", trans: { ru: "и нет", en: "and no" }, start: 14.34, end: 14.62 },
        { text: "ضِرَارَ", trans: { ru: "ответного вреда", en: "reciprocating harm" }, start: 14.62, end: 15.51 },
      ],
    },
  ],
};
