// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/32.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3032: ChapterData = {
  id: 3032,
  collection: 'nawawi',
  title: { ru: "Не причинять вреда и не отвечать вредом", en: "There is no harm and no reciprocating harm" },
  duas: [
    {
      id: "3032-1",
      narration: { ru: "Со слов Абу Са‘ида Са‘да ибн Малика ибн Синана аль-Худри, да будет доволен им Аллах, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Abu Sa‘id Sa‘d ibn Malik ibn Sinan al-Khudri, may Allah be pleased with him, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Не причинять вреда и не отвечать вредом на вред.", en: "There is to be no harm, and no reciprocating harm." },
      source: { ru: "Ибн Маджа 2341; ад-Даракутни 4/228", en: "Ibn Majah 2341; ad-Daraqutni 4/228" },
      sync: [
        { text: "لَا", trans: { ru: "нет", en: "there is no" }, start: 0, end: 0 },
        { text: "ضَرَرَ", trans: { ru: "вреда", en: "harm" }, start: 0, end: 0 },
        { text: "وَلَا", trans: { ru: "и нет", en: "and no" }, start: 0, end: 0 },
        { text: "ضِرَارَ", trans: { ru: "ответного вреда", en: "reciprocating harm" }, start: 0, end: 0 },
      ],
    },
  ],
};
