// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/33.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3033: ChapterData = {
  id: 3033,
  collection: 'nawawi',
  title: { ru: "Доказательство — на истце, клятва — на ответчике", en: "The proof is upon the claimant, the oath upon the denier" },
  duas: [
    {
      id: "3033-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/33.mp3?v=014a4702",
      narration: { ru: "От Ибн Аббаса (да будет доволен Аллах им и его отцом) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Ibn Abbas (may Allah be pleased with him and with his father), that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Если бы человек получал всё лишь на основе заявлений, то люди стали бы заявлять свои права на чужое имущество и чужую жизнь, но доказательство должен привести тот, кто утверждает, а клятвы достаточно тому, кто отрицает.", en: "Were people given whatever they claimed, men would claim the wealth and the lives of others. But the burden of proof is upon the claimant, and the oath is upon the one who denies." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ، رَوَاهُ الْبَيْهَقِيُّ وَغَيْرُهُ هَكَذَا، وَبَعْضُهُ فِي «الصَّحِيحَيْنِ».",
      note: { ru: "Хадис хороший, передал его аль-Байхаки и другие в таком виде, а часть его — в двух «Сахихах».", en: "A hasan hadith, related in this form by al-Bayhaqi and others; part of it is in the two Sahihs." },
      source: { ru: "аль-Байхаки 10/252; аль-Бухари 4552 и Муслим 1711 в близких формулировках", en: "al-Bayhaqi 10/252; al-Bukhari 4552 and Muslim 1711 in close wordings" },
      sync: [
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 0.33, end: 0.53 },
        { text: "ابنِ", trans: { ru: "Ибн", en: "Ibn" }, start: 0.53, end: 0.86 },
        { text: "عَبَّاسٍ", trans: { ru: "Аббаса", en: "Abbas" }, start: 0.86, end: 1.3 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 1.35, end: 1.99 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 2.13, end: 2.44 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 2.44, end: 3.93 },
        { text: "أَنَّ", trans: { ru: "что", en: "that" }, start: 4.86, end: 5.47 },
        { text: "رَسُولَ", trans: { ru: "посланника", en: "the Messenger of" }, start: 5.47, end: 6 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 6, end: 6.24 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 6.24, end: 6.88 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 6.88, end: 7.2 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 7.2, end: 7.73 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 7.73, end: 8.43 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 8.54, end: 8.88 },
        { text: "لَوْ", trans: { ru: "если бы", en: "if" }, start: 10.03, end: 10.35 },
        { text: "يُعْطَى", trans: { ru: "давали", en: "were given" }, start: 10.35, end: 10.68 },
        { text: "النَّاسُ", trans: { ru: "людям", en: "the people" }, start: 10.78, end: 11.47 },
        { text: "بِدَعْوَاهُمْ", trans: { ru: "по их притязаниям", en: "by their claims" }, start: 11.47, end: 12.62 },
        { text: "لَادَّعَى", trans: { ru: "стали бы притязать", en: "men would claim" }, start: 13.27, end: 14.34 },
        { text: "رِجَالٌ", trans: { ru: "люди", en: "men" }, start: 14.34, end: 14.92 },
        { text: "أَمْوَالَ", trans: { ru: "на имущество", en: "the wealth of" }, start: 15.04, end: 15.74 },
        { text: "قَوْمٍ", trans: { ru: "других", en: "a people" }, start: 15.86, end: 16.34 },
        { text: "وَدِمَاءَهُمْ", trans: { ru: "и их кровь", en: "and their blood" }, start: 16.34, end: 17.47 },
        { text: "لَكِنِ", trans: { ru: "однако", en: "but" }, start: 18.49, end: 18.71 },
        { text: "الْبَيِّنَةُ", trans: { ru: "доказательство", en: "the proof is" }, start: 18.8, end: 19.88 },
        { text: "عَلَى", trans: { ru: "на", en: "upon" }, start: 19.95, end: 20.29 },
        { text: "الْمُدَّعِي", trans: { ru: "притязающем", en: "the claimant" }, start: 20.29, end: 21.19 },
        { text: "وَالْيَمِينُ", trans: { ru: "а клятва", en: "and the oath is" }, start: 21.74, end: 22.63 },
        { text: "عَلَى", trans: { ru: "на", en: "upon" }, start: 22.63, end: 22.94 },
        { text: "مَنْ", trans: { ru: "том, кто", en: "the one who" }, start: 22.94, end: 23.46 },
        { text: "أَنْكَرَ", trans: { ru: "отрицает", en: "denies" }, start: 23.58, end: 23.75 },
      ],
    },
  ],
};
