// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/33.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3033: ChapterData = {
  id: 3033,
  collection: 'nawawi',
  title: { ru: "Доказательство — на истце, клятва — на ответчике", en: "The proof is upon the claimant, the oath upon the denier" },
  duas: [
    {
      id: "3033-1",
      narration: { ru: "Со слов Ибн Аббаса, да будет доволен Аллах ими обоими, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Ibn Abbas, may Allah be pleased with them both, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Если бы людям давали по их притязаниям, то одни стали бы притязать на имущество и кровь других. Однако доказательство — на том, кто предъявляет притязание, а клятва — на том, кто отрицает.", en: "Were people given merely by their claims, men would claim the wealth and the blood of others. But the proof is upon the one who makes the claim, and the oath is upon the one who denies." },
      source: { ru: "аль-Байхаки 10/252; аль-Бухари 4552 и Муслим 1711 в близких формулировках", en: "al-Bayhaqi 10/252; al-Bukhari 4552 and Muslim 1711 in close wordings" },
      sync: [
        { text: "لَوْ", trans: { ru: "если бы", en: "if" }, start: 0, end: 0 },
        { text: "يُعْطَى", trans: { ru: "давали", en: "were given" }, start: 0, end: 0 },
        { text: "النَّاسُ", trans: { ru: "людям", en: "the people" }, start: 0, end: 0 },
        { text: "بِدَعْوَاهُمْ", trans: { ru: "по их притязаниям", en: "by their claims" }, start: 0, end: 0 },
        { text: "لَادَّعَى", trans: { ru: "стали бы притязать", en: "men would claim" }, start: 0, end: 0 },
        { text: "رِجَالٌ", trans: { ru: "люди", en: "men" }, start: 0, end: 0 },
        { text: "أَمْوَالَ", trans: { ru: "на имущество", en: "the wealth of" }, start: 0, end: 0 },
        { text: "قَوْمٍ", trans: { ru: "других", en: "a people" }, start: 0, end: 0 },
        { text: "وَدِمَاءَهُمْ", trans: { ru: "и их кровь", en: "and their blood" }, start: 0, end: 0 },
        { text: "لَكِنِ", trans: { ru: "однако", en: "but" }, start: 0, end: 0 },
        { text: "الْبَيِّنَةُ", trans: { ru: "доказательство", en: "the proof is" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "на", en: "upon" }, start: 0, end: 0 },
        { text: "الْمُدَّعِي", trans: { ru: "притязающем", en: "the claimant" }, start: 0, end: 0 },
        { text: "وَالْيَمِينُ", trans: { ru: "а клятва", en: "and the oath is" }, start: 0, end: 0 },
        { text: "عَلَى", trans: { ru: "на", en: "upon" }, start: 0, end: 0 },
        { text: "مَنْ", trans: { ru: "том, кто", en: "the one who" }, start: 0, end: 0 },
        { text: "أَنْكَرَ", trans: { ru: "отрицает", en: "denies" }, start: 0, end: 0 },
      ],
    },
  ],
};
