// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/34.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3034: ChapterData = {
  id: 3034,
  collection: 'nawawi',
  title: { ru: "Изменение порицаемого", en: "Changing what is wrong" },
  duas: [
    {
      id: "3034-1",
      narration: { ru: "Со слов Абу Са‘ида аль-Худри, да будет доволен им Аллах, передаётся, что он сказал: «Я слышал, как посланник Аллаха ﷺ сказал…»", en: "On the authority of Abu Sa‘id al-Khudri, may Allah be pleased with him, who said: “I heard the Messenger of Allah ﷺ say…”" },
      fullTranslation: { ru: "Пусть тот из вас, кто увидит порицаемое, изменит это своей рукой; если не сможет — то своим языком; а если не сможет — то своим сердцем, и это будет слабейшим проявлением веры.", en: "Whoever of you sees something wrong, let him change it with his hand; if he cannot, then with his tongue; and if he cannot, then with his heart — and that is the weakest of faith." },
      source: { ru: "Муслим 49", en: "Muslim 49" },
      sync: [
        { text: "مَنْ", trans: { ru: "кто", en: "whoever" }, start: 0, end: 0 },
        { text: "رَأَى", trans: { ru: "увидит", en: "sees" }, start: 0, end: 0 },
        { text: "مِنْكُمْ", trans: { ru: "из вас", en: "of you" }, start: 0, end: 0 },
        { text: "مُنْكَرًا", trans: { ru: "порицаемое", en: "something wrong" }, start: 0, end: 0 },
        { text: "فَلْيُغَيِّرْهُ", trans: { ru: "пусть изменит это", en: "let him change it" }, start: 0, end: 0 },
        { text: "بِيَدِهِ", trans: { ru: "своей рукой", en: "with his hand" }, start: 0, end: 0 },
        { text: "فَإِنْ", trans: { ru: "а если", en: "and if" }, start: 0, end: 0 },
        { text: "لَمْ", trans: { ru: "не", en: "he is not" }, start: 0, end: 0 },
        { text: "يَسْتَطِعْ", trans: { ru: "сможет", en: "able" }, start: 0, end: 0 },
        { text: "فَبِلِسَانِهِ", trans: { ru: "то своим языком", en: "then with his tongue" }, start: 0, end: 0 },
        { text: "فَإِنْ", trans: { ru: "а если", en: "and if" }, start: 0, end: 0 },
        { text: "لَمْ", trans: { ru: "не", en: "he is not" }, start: 0, end: 0 },
        { text: "يَسْتَطِعْ", trans: { ru: "сможет", en: "able" }, start: 0, end: 0 },
        { text: "فَبِقَلْبِهِ", trans: { ru: "то своим сердцем", en: "then with his heart" }, start: 0, end: 0 },
        { text: "وَذَلِكَ", trans: { ru: "и это", en: "and that is" }, start: 0, end: 0 },
        { text: "أَضْعَفُ", trans: { ru: "слабейшее", en: "the weakest of" }, start: 0, end: 0 },
        { text: "الْإِيمَانِ", trans: { ru: "веры", en: "faith" }, start: 0, end: 0 },
      ],
    },
  ],
};
