// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/39.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3039: ChapterData = {
  id: 3039,
  collection: 'nawawi',
  title: { ru: "Прощены ошибка, забывчивость и принуждение", en: "Mistake, forgetfulness and coercion are pardoned" },
  duas: [
    {
      id: "3039-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/39.mp3?v=64adfec9",
      narration: { ru: "От Ибн Аббаса (да будет доволен Аллах им и его отцом) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Ibn Abbas (may Allah be pleased with him and with his father), that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Аллах простил моей общине ошибку, забывчивость и то, в чём их принудили.", en: "Allah has pardoned my community for mistakes, forgetfulness, and what they are compelled to do." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ، رَوَاهُ ابنُ مَاجَهْ وَالْبَيْهَقِيُّ.",
      note: { ru: "Хадис хороший. Его передали Ибн Маджа и аль-Байхаки.", en: "A hasan hadith, related by Ibn Maja and al-Bayhaqi." },
      source: { ru: "Ибн Маджа 2045; аль-Байхаки 7/356", en: "Ibn Majah 2045; al-Bayhaqi 7/356" },
      sync: [
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 0.37, end: 0.59 },
        { text: "ابنِ", trans: { ru: "Ибн", en: "Ibn" }, start: 0.59, end: 1.02 },
        { text: "عَبَّاسٍ", trans: { ru: "Аббаса", en: "Abbas" }, start: 1.02, end: 1.78 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 1.78, end: 2.21 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 2.21, end: 2.75 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 2.75, end: 3.4 },
        { text: "أَنَّ", trans: { ru: "что", en: "that" }, start: 4.36, end: 4.76 },
        { text: "رَسُولَ", trans: { ru: "посланника", en: "the Messenger of" }, start: 4.76, end: 5.26 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 5.26, end: 5.76 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 5.76, end: 6.26 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 6.26, end: 6.76 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 6.76, end: 7.26 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 7.26, end: 7.96 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 7.96, end: 8.36 },
        { text: "إِنَّ", trans: { ru: "поистине", en: "indeed" }, start: 9.21, end: 9.61 },
        { text: "اللهَ", trans: { ru: "Аллах", en: "Allah" }, start: 9.61, end: 10.12 },
        { text: "تَجَاوَزَ", trans: { ru: "простил", en: "has pardoned" }, start: 10.12, end: 10.82 },
        { text: "لِي", trans: { ru: "ради меня", en: "for me" }, start: 10.82, end: 11.12 },
        { text: "عَنْ", trans: { ru: "для", en: "on behalf of" }, start: 11.12, end: 11.32 },
        { text: "أُمَّتِي", trans: { ru: "моей общины", en: "my community" }, start: 11.32, end: 12.03 },
        { text: "الْخَطَأَ", trans: { ru: "ошибку", en: "the mistake" }, start: 12.03, end: 12.63 },
        { text: "وَالنِّسْيَانَ", trans: { ru: "и забывчивость", en: "and the forgetfulness" }, start: 12.63, end: 14.04 },
        { text: "وَمَا", trans: { ru: "и то, к чему", en: "and what" }, start: 14.56, end: 14.77 },
        { text: "اسْتُكْرِهُوا", trans: { ru: "их принудили", en: "they are coerced" }, start: 14.77, end: 15.24 },
        { text: "عَلَيْهِ", trans: { ru: "к этому", en: "into" }, start: 15.35, end: 16.35 },
      ],
    },
  ],
};
