// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/39.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3039: ChapterData = {
  id: 3039,
  collection: 'nawawi',
  title: { ru: "Прощены ошибка, забывчивость и принуждение", en: "Mistake, forgetfulness and coercion are pardoned" },
  duas: [
    {
      id: "3039-1",
      narration: { ru: "От Ибн Аббаса (да будет доволен Аллах им и его отцом) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Ibn Abbas (may Allah be pleased with him and with his father), that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Аллах простил моей общине ошибку, забывчивость и то, в чём их принудили.", en: "Allah has pardoned my community for mistakes, forgetfulness, and what they are compelled to do." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ، رَوَاهُ ابنُ مَاجَهْ وَالْبَيْهَقِيُّ.",
      note: { ru: "Хадис хороший. Его передали Ибн Маджа и аль-Байхаки.", en: "A hasan hadith, related by Ibn Maja and al-Bayhaqi." },
      source: { ru: "Ибн Маджа 2045; аль-Байхаки 7/356", en: "Ibn Majah 2045; al-Bayhaqi 7/356" },
      sync: [
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 0, end: 0 },
        { text: "ابنِ", trans: { ru: "Ибн", en: "Ibn" }, start: 0, end: 0 },
        { text: "عَبَّاسٍ", trans: { ru: "Аббаса", en: "Abbas" }, start: 0, end: 0 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 0, end: 0 },
        { text: "أَنَّ", trans: { ru: "что", en: "that" }, start: 0, end: 0 },
        { text: "رَسُولَ", trans: { ru: "посланника", en: "the Messenger of" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 0, end: 0 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 0, end: 0 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 0, end: 0 },
        { text: "إِنَّ", trans: { ru: "поистине", en: "indeed" }, start: 0, end: 0 },
        { text: "اللهَ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "تَجَاوَزَ", trans: { ru: "простил", en: "has pardoned" }, start: 0, end: 0 },
        { text: "لِي", trans: { ru: "ради меня", en: "for me" }, start: 0, end: 0 },
        { text: "عَنْ", trans: { ru: "для", en: "on behalf of" }, start: 0, end: 0 },
        { text: "أُمَّتِي", trans: { ru: "моей общины", en: "my community" }, start: 0, end: 0 },
        { text: "الْخَطَأَ", trans: { ru: "ошибку", en: "the mistake" }, start: 0, end: 0 },
        { text: "وَالنِّسْيَانَ", trans: { ru: "и забывчивость", en: "and the forgetfulness" }, start: 0, end: 0 },
        { text: "وَمَا", trans: { ru: "и то, к чему", en: "and what" }, start: 0, end: 0 },
        { text: "اسْتُكْرِهُوا", trans: { ru: "их принудили", en: "they are coerced" }, start: 0, end: 0 },
        { text: "عَلَيْهِ", trans: { ru: "к этому", en: "into" }, start: 0, end: 0 },
      ],
    },
  ],
};
