// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/40.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3040: ChapterData = {
  id: 3040,
  collection: 'nawawi',
  title: { ru: "Будь в этом мире как чужеземец", en: "Be in this world as a stranger" },
  duas: [
    {
      id: "3040-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/40.mp3?v=dd31534f",
      narration: { ru: "От Ибн Умара (да будет доволен Аллах им и его отцом) передаётся, что он сказал: «Посланник Аллаха (да благословит его Аллах и приветствует) взял меня за плечо и сказал:", en: "On the authority of Ibn Umar (may Allah be pleased with him and with his father), who said: “The Messenger of Allah (may Allah bless him and grant him peace) took me by the shoulder and said:" },
      fullTranslation: { ru: "Будь в этом мире как чужак либо как путник.", en: "Be in this world as though you were a stranger or a traveller on the road." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ.",
      note: { ru: "Хадис передал аль-Бухари. Ибн Умар (да будет доволен Аллах им и его отцом) говорил: «Если уже стемнело, то не жди утра, а если проснулся, то не надейся дожить до вечера. Возьми из своего здоровья для времени, когда будешь болеть, а из своей жизни то, что будет полезно, когда умрёшь».", en: "Related by al-Bukhari. Ibn Umar (may Allah be pleased with him and with his father) used to say: “When evening comes, do not await the morning; and when morning comes, do not await the evening. Take from your health for your illness, and from your life for your death.”" },
      source: { ru: "аль-Бухари 6416", en: "al-Bukhari 6416" },
      sync: [
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 0.28, end: 0.49 },
        { text: "ابنِ", trans: { ru: "Ибн", en: "Ibn" }, start: 0.49, end: 0.87 },
        { text: "عُمَرَ", trans: { ru: "Умара", en: "Umar" }, start: 0.87, end: 1.44 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 1.91, end: 2.32 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 2.32, end: 2.6 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 2.6, end: 3.76 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 4.47, end: 4.92 },
        { text: "أَخَذَ", trans: { ru: "взял", en: "took" }, start: 5.85, end: 6.63 },
        { text: "رَسُولُ", trans: { ru: "Посланник", en: "the Messenger of" }, start: 6.63, end: 7.22 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 7.22, end: 7.54 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 7.54, end: 8.19 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 8.19, end: 8.39 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 8.43, end: 9.16 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 9.16, end: 10.01 },
        { text: "بِمَنْكِبِي", trans: { ru: "меня за плечо", en: "me by the shoulder" }, start: 10.01, end: 11 },
        { text: "وَقَالَ", trans: { ru: "и сказал", en: "and he said" }, start: 12.01, end: 12.47 },
        { text: "كُنْ", trans: { ru: "будь", en: "be" }, start: 13.44, end: 13.97 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 13.97, end: 14.11 },
        { text: "الدُّنْيَا", trans: { ru: "этом мире", en: "this world" }, start: 14.15, end: 14.79 },
        { text: "كَأَنَّكَ", trans: { ru: "словно ты", en: "as though you were" }, start: 15.11, end: 16.24 },
        { text: "غَرِيبٌ", trans: { ru: "чужеземец", en: "a stranger" }, start: 16.24, end: 16.99 },
        { text: "أَوْ", trans: { ru: "или", en: "or" }, start: 17.36, end: 17.56 },
        { text: "عَابِرُ", trans: { ru: "проходящий", en: "one crossing" }, start: 17.56, end: 18.52 },
        { text: "سَبِيلٍ", trans: { ru: "путник", en: "the road" }, start: 18.52, end: 19.23 },
      ],
    },
  ],
};
