// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/40.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3040: ChapterData = {
  id: 3040,
  collection: 'nawawi',
  title: { ru: "Будь в этом мире как чужеземец", en: "Be in this world as a stranger" },
  duas: [
    {
      id: "3040-1",
      narration: { ru: "От Ибн Умара (да будет доволен Аллах им и его отцом) передаётся, что он сказал: «Посланник Аллаха (да благословит его Аллах и приветствует) взял меня за плечо и сказал:", en: "On the authority of Ibn Umar (may Allah be pleased with him and with his father), who said: “The Messenger of Allah (may Allah bless him and grant him peace) took me by the shoulder and said:" },
      fullTranslation: { ru: "Будь в этом мире как чужак либо как путник.", en: "Be in this world as though you were a stranger or a traveller on the road." },
      takhrijArabic: "رَوَاهُ الْبُخَارِيُّ.",
      note: { ru: "Хадис передал аль-Бухари. Ибн Умар (да будет доволен Аллах им и его отцом) говорил: «Если уже стемнело, то не жди утра, а если проснулся, то не надейся дожить до вечера. Возьми из своего здоровья для времени, когда будешь болеть, а из своей жизни то, что будет полезно, когда умрёшь».", en: "Related by al-Bukhari. Ibn Umar (may Allah be pleased with him and with his father) used to say: “When evening comes, do not await the morning; and when morning comes, do not await the evening. Take from your health for your illness, and from your life for your death.”" },
      source: { ru: "аль-Бухари 6416", en: "al-Bukhari 6416" },
      sync: [
        { text: "عَنِ", trans: { ru: "от", en: "on the authority of" }, start: 0, end: 0 },
        { text: "ابنِ", trans: { ru: "Ибн", en: "Ibn" }, start: 0, end: 0 },
        { text: "عُمَرَ", trans: { ru: "Умара", en: "Umar" }, start: 0, end: 0 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 0, end: 0 },
        { text: "أَخَذَ", trans: { ru: "взял", en: "took" }, start: 0, end: 0 },
        { text: "رَسُولُ", trans: { ru: "Посланник", en: "the Messenger of" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 0, end: 0 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 0, end: 0 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 0, end: 0 },
        { text: "بِمَنْكِبِي", trans: { ru: "меня за плечо", en: "me by the shoulder" }, start: 0, end: 0 },
        { text: "وَقَالَ", trans: { ru: "и сказал", en: "and he said" }, start: 0, end: 0 },
        { text: "كُنْ", trans: { ru: "будь", en: "be" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 0, end: 0 },
        { text: "الدُّنْيَا", trans: { ru: "этом мире", en: "this world" }, start: 0, end: 0 },
        { text: "كَأَنَّكَ", trans: { ru: "словно ты", en: "as though you were" }, start: 0, end: 0 },
        { text: "غَرِيبٌ", trans: { ru: "чужеземец", en: "a stranger" }, start: 0, end: 0 },
        { text: "أَوْ", trans: { ru: "или", en: "or" }, start: 0, end: 0 },
        { text: "عَابِرُ", trans: { ru: "проходящий", en: "one crossing" }, start: 0, end: 0 },
        { text: "سَبِيلٍ", trans: { ru: "путник", en: "the road" }, start: 0, end: 0 },
      ],
    },
  ],
};
