// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/40.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3040: ChapterData = {
  id: 3040,
  collection: 'nawawi',
  title: { ru: "Будь в этом мире как чужеземец", en: "Be in this world as a stranger" },
  duas: [
    {
      id: "3040-1",
      narration: { ru: "Со слов Ибн Умара, да будет доволен Аллах ими обоими, передаётся, что он сказал: «Посланник Аллаха ﷺ взял меня за плечи и сказал…»", en: "On the authority of Ibn Umar, may Allah be pleased with them both, who said: “The Messenger of Allah ﷺ took hold of my shoulders and said…”" },
      fullTranslation: { ru: "Будь в этом мире, словно ты чужеземец или путник.", en: "Be in this world as though you were a stranger or a traveller passing through." },
      note: { ru: "Ибн Умар говорил: «Когда наступит вечер, не жди утра, а когда наступит утро, не жди вечера. Бери из своего здоровья для своей болезни и из своей жизни для своей смерти».", en: "Ibn Umar used to say: “When evening comes, do not expect the morning; and when morning comes, do not expect the evening. Take from your health for your illness, and from your life for your death.”" },
      source: { ru: "аль-Бухари 6416", en: "al-Bukhari 6416" },
      sync: [
        { text: "كُنْ", trans: { ru: "будь", en: "be" }, start: 0, end: 0 },
        { text: "فِي", trans: { ru: "в", en: "in" }, start: 0, end: 0 },
        { text: "الدُّنْيَا", trans: { ru: "этом мире", en: "this world" }, start: 0, end: 0 },
        { text: "كَأَنَّكَ", trans: { ru: "словно ты", en: "as though you were" }, start: 0, end: 0 },
        { text: "غَرِيبٌ", trans: { ru: "чужеземец", en: "a stranger" }, start: 0, end: 0 },
        { text: "أَوْ", trans: { ru: "или", en: "or" }, start: 0, end: 0 },
        { text: "عَابِرُ", trans: { ru: "проходящий", en: "one crossing" }, start: 0, end: 0 },
        { text: "سَبِيلٍ", trans: { ru: "путник", en: "the road" }, start: 0, end: 0 },
      ],
    },
  ],
};
