// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/41.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3041: ChapterData = {
  id: 3041,
  collection: 'nawawi',
  title: { ru: "Пока желание не последует за принесённым мной", en: "Until his desire follows what I have brought" },
  duas: [
    {
      id: "3041-1",
      narration: { ru: "Со слов Абу Мухаммада Абдуллаха ибн Амра ибн аль-Аса, да будет доволен Аллах ими обоими, передаётся, что посланник Аллаха ﷺ сказал:", en: "On the authority of Abu Muhammad Abdullah ibn Amr ibn al-As, may Allah be pleased with them both, that the Messenger of Allah ﷺ said:" },
      fullTranslation: { ru: "Не уверует никто из вас, пока его желание не последует за тем, с чем я пришёл.", en: "None of you truly believes until his desire follows what I have brought." },
      source: { ru: "приводится в «Китаб аль-худжжа» с достоверным иснадом", en: "reported in Kitab al-Hujjah with a sound chain" },
      sync: [
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 0, end: 0 },
        { text: "يُؤْمِنُ", trans: { ru: "уверует", en: "believe" }, start: 0, end: 0 },
        { text: "أَحَدُكُمْ", trans: { ru: "никто из вас", en: "any of you" }, start: 0, end: 0 },
        { text: "حَتَّى", trans: { ru: "пока", en: "until" }, start: 0, end: 0 },
        { text: "يَكُونَ", trans: { ru: "не станет", en: "becomes" }, start: 0, end: 0 },
        { text: "هَوَاهُ", trans: { ru: "его желание", en: "his desire" }, start: 0, end: 0 },
        { text: "تَبَعًا", trans: { ru: "следующим", en: "following" }, start: 0, end: 0 },
        { text: "لِمَا", trans: { ru: "за тем, с чем", en: "what" }, start: 0, end: 0 },
        { text: "جِئْتُ", trans: { ru: "я пришёл", en: "I have brought" }, start: 0, end: 0 },
        { text: "بِهِ", trans: { ru: "с этим", en: "with" }, start: 0, end: 0 },
      ],
    },
  ],
};
