// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/41.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3041: ChapterData = {
  id: 3041,
  collection: 'nawawi',
  title: { ru: "Пока желание не последует за принесённым мной", en: "Until his desire follows what I have brought" },
  duas: [
    {
      id: "3041-1",
      narration: { ru: "От Абу Мухаммада Абдуллаха ибн Амра ибн аль-Аса (да будет доволен Аллах им и его отцом) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Muhammad Abdullah ibn Amr ibn al-As (may Allah be pleased with him and with his father), who said that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Никто из вас не уверует, пока ваши желания не будут следовать тому, с чем я пришёл.", en: "None of you truly believes until his desire follows what I have brought." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ صَحِيحٌ، رَوَيْنَاهُ فِي كِتَابِ «الْحُجَّةِ» بِإِسْنَادٍ صَحِيحٍ.",
      note: { ru: "Это достоверный хадис, который мы привели с достоверным иснадом в книге «Аль-Худжжа».", en: "A sound hadith, which we related with a sound chain in the book al-Hujja." },
      source: { ru: "приводится в «Китаб аль-худжжа» с достоверным иснадом", en: "reported in Kitab al-Hujjah with a sound chain" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0, end: 0 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0, end: 0 },
        { text: "مُحَمَّدٍ", trans: { ru: "Мухаммада", en: "Muhammad" }, start: 0, end: 0 },
        { text: "عَبْدِ", trans: { ru: "Абд", en: "Abd" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 0, end: 0 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 0, end: 0 },
        { text: "عَمْرِو", trans: { ru: "Амра", en: "Amr" }, start: 0, end: 0 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 0, end: 0 },
        { text: "الْعَاصِ", trans: { ru: "аль-Аса", en: "al-As" }, start: 0, end: 0 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 0, end: 0 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 0, end: 0 },
        { text: "رَسُولُ", trans: { ru: "Посланник", en: "the Messenger of" }, start: 0, end: 0 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 0, end: 0 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 0, end: 0 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 0, end: 0 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 0, end: 0 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 0, end: 0 },
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 0, end: 0 },
        { text: "يُؤْمِنُ", trans: { ru: "уверует", en: "believe" }, start: 0, end: 0 },
        { text: "أَحَدُكُمْ", trans: { ru: "никто из вас", en: "any of you" }, start: 0, end: 0 },
        { text: "حَتَّى", trans: { ru: "пока", en: "until" }, start: 0, end: 0 },
        { text: "يَكُونَ", trans: { ru: "не станет", en: "becomes" }, start: 0, end: 0 },
        { text: "هَوَاهُ", trans: { ru: "его желание", en: "his desire" }, start: 0, end: 0 },
        { text: "تَبَعًا", trans: { ru: "следующим", en: "following" }, start: 0, end: 0 },
        { text: "لِمَا", trans: { ru: "за тем, с чем", en: "what" }, start: 0, end: 0 },
        { text: "جِئْتُ", trans: { ru: "я пришёл", en: "I have brought" }, start: 0, end: 0 },
        { text: "بِهِ", trans: { ru: "с этим", en: "with" }, start: 0, end: 0 },
      ],
    },
  ],
};
