// Generated by scripts/build-nawawi-chapters.mjs from data/nawawi/source/41.json.
// Edit that source file and re-run the script; do not edit this one.

import { ChapterData } from '../../types';

export const NAWAWI_CHAPTER_3041: ChapterData = {
  id: 3041,
  collection: 'nawawi',
  title: { ru: "Пока желание не последует за принесённым мной", en: "Until his desire follows what I have brought" },
  duas: [
    {
      id: "3041-1",
      audioUrl: "https://s3.twcstorage.ru/44a93b74-shakhbanov/dua.shakhbanov.org/40hadis/41.mp3",
      narration: { ru: "От Абу Мухаммада Абдуллаха ибн Амра ибн аль-Аса (да будет доволен Аллах им и его отцом) передаётся, что Посланник Аллаха (да благословит его Аллах и приветствует) сказал:", en: "On the authority of Abu Muhammad Abdullah ibn Amr ibn al-As (may Allah be pleased with him and with his father), who said that the Messenger of Allah (may Allah bless him and grant him peace) said:" },
      fullTranslation: { ru: "Никто из вас не уверует, пока ваши желания не будут следовать тому, с чем я пришёл.", en: "None of you truly believes until his desire follows what I have brought." },
      takhrijArabic: "حَدِيثٌ حَسَنٌ صَحِيحٌ، رَوَيْنَاهُ فِي كِتَابِ «الْحُجَّةِ» بِإِسْنَادٍ صَحِيحٍ.",
      note: { ru: "Это достоверный хадис, который мы привели с достоверным иснадом в книге «Аль-Худжжа».", en: "A sound hadith, which we related with a sound chain in the book al-Hujja." },
      source: { ru: "приводится в «Китаб аль-худжжа» с достоверным иснадом", en: "reported in Kitab al-Hujjah with a sound chain" },
      sync: [
        { text: "عَنْ", trans: { ru: "от", en: "on the authority of" }, start: 0.18, end: 0.42 },
        { text: "أَبِي", trans: { ru: "Абу", en: "Abu" }, start: 0.42, end: 1 },
        { text: "مُحَمَّدٍ", trans: { ru: "Мухаммада", en: "Muhammad" }, start: 1, end: 2 },
        { text: "عَبْدِ", trans: { ru: "Абд", en: "Abd" }, start: 2.58, end: 2.98 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 2.98, end: 3.28 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 3.28, end: 3.7 },
        { text: "عَمْرِو", trans: { ru: "Амра", en: "Amr" }, start: 3.7, end: 4.22 },
        { text: "بْنِ", trans: { ru: "ибн", en: "son of" }, start: 4.22, end: 4.4 },
        { text: "الْعَاصِ", trans: { ru: "аль-Аса", en: "al-As" }, start: 4.4, end: 5.12 },
        { text: "رَضِيَ", trans: { ru: "да будет доволен", en: "may be pleased" }, start: 5.64, end: 5.98 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 5.98, end: 6.24 },
        { text: "عَنْهُمَا", trans: { ru: "ими обоими", en: "with them both" }, start: 6.24, end: 7.3 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 8.28, end: 8.54 },
        { text: "قَالَ", trans: { ru: "сказал", en: "said" }, start: 9.84, end: 9.98 },
        { text: "رَسُولُ", trans: { ru: "Посланник", en: "the Messenger of" }, start: 9.98, end: 10.58 },
        { text: "اللهِ", trans: { ru: "Аллаха", en: "of Allah" }, start: 10.58, end: 10.86 },
        { text: "صَلَّى", trans: { ru: "да благословит", en: "may bless" }, start: 10.86, end: 11.46 },
        { text: "اللهُ", trans: { ru: "Аллах", en: "Allah" }, start: 11.46, end: 11.8 },
        { text: "عَلَيْهِ", trans: { ru: "его", en: "him" }, start: 11.8, end: 12.34 },
        { text: "وَسَلَّمَ", trans: { ru: "и приветствует", en: "and grant him peace" }, start: 12.34, end: 13.12 },
        { text: "لَا", trans: { ru: "не", en: "does not" }, start: 14.34, end: 14.56 },
        { text: "يُؤْمِنُ", trans: { ru: "уверует", en: "believe" }, start: 14.56, end: 15.22 },
        { text: "أَحَدُكُمْ", trans: { ru: "никто из вас", en: "any of you" }, start: 15.22, end: 15.98 },
        { text: "حَتَّى", trans: { ru: "пока", en: "until" }, start: 16.77, end: 17.29 },
        { text: "يَكُونَ", trans: { ru: "не станет", en: "becomes" }, start: 17.29, end: 17.91 },
        { text: "هَوَاهُ", trans: { ru: "его желание", en: "his desire" }, start: 17.91, end: 18.59 },
        { text: "تَبَعًا", trans: { ru: "следующим", en: "following" }, start: 18.59, end: 19.31 },
        { text: "لِمَا", trans: { ru: "за тем, с чем", en: "what" }, start: 19.31, end: 19.81 },
        { text: "جِئْتُ", trans: { ru: "я пришёл", en: "I have brought" }, start: 19.81, end: 20.35 },
        { text: "بِهِ", trans: { ru: "с этим", en: "with" }, start: 20.35, end: 20.65 },
      ],
    },
  ],
};
