// Generated by scripts/build-nawawi-chapters.mjs. Do not edit by hand.
//
// The Forty Hadith of Imam an-Nawawi — one chapter per hadith, in the
// order of the collection. Chapter ids are 3000 + the hadith number, so
// they never collide with the Sunnah (1..134) or Quranic (2001+) chapters.

import type { ChapterData } from '../../types';
import { NAWAWI_CHAPTER_3001 } from './3001-hadith-01-actions-are-judged-by-intentions';
import { NAWAWI_CHAPTER_3002 } from './3002-hadith-02-islam-iman-and-ihsan';
import { NAWAWI_CHAPTER_3003 } from './3003-hadith-03-islam-is-built-upon-five';
import { NAWAWI_CHAPTER_3004 } from './3004-hadith-04-the-creation-of-man-and-the-decree';
import { NAWAWI_CHAPTER_3005 } from './3005-hadith-05-an-innovation-in-the-religion-is-rejected';
import { NAWAWI_CHAPTER_3006 } from './3006-hadith-06-the-lawful-is-clear-and-the-unlawful-is-clear';
import { NAWAWI_CHAPTER_3007 } from './3007-hadith-07-the-religion-is-sincere-counsel';
import { NAWAWI_CHAPTER_3008 } from './3008-hadith-08-the-inviolability-of-the-muslim';
import { NAWAWI_CHAPTER_3009 } from './3009-hadith-09-do-what-you-are-able-to-do';
import { NAWAWI_CHAPTER_3010 } from './3010-hadith-10-allah-accepts-only-what-is-pure';
import { NAWAWI_CHAPTER_3011 } from './3011-hadith-11-leave-what-makes-you-doubt';
import { NAWAWI_CHAPTER_3012 } from './3012-hadith-12-leaving-what-does-not-concern-you';
import { NAWAWI_CHAPTER_3013 } from './3013-hadith-13-loving-for-your-brother-what-you-love-for-yourself';
import { NAWAWI_CHAPTER_3014 } from './3014-hadith-14-the-blood-of-a-muslim-is-lawful-only-in-three-cases';
import { NAWAWI_CHAPTER_3015 } from './3015-hadith-15-let-him-speak-good-or-keep-silent';
import { NAWAWI_CHAPTER_3016 } from './3016-hadith-16-do-not-become-angry';
import { NAWAWI_CHAPTER_3017 } from './3017-hadith-17-allah-has-prescribed-excellence-in-everything';
import { NAWAWI_CHAPTER_3018 } from './3018-hadith-18-fear-allah-wherever-you-are';
import { NAWAWI_CHAPTER_3019 } from './3019-hadith-19-be-mindful-of-allah-and-he-will-protect-you';
import { NAWAWI_CHAPTER_3020 } from './3020-hadith-20-if-you-feel-no-shame-do-as-you-wish';
import { NAWAWI_CHAPTER_3021 } from './3021-hadith-21-say-i-believe-in-allah-then-be-steadfast';
import { NAWAWI_CHAPTER_3022 } from './3022-hadith-22-the-obligatory-suffices-for-paradise';
import { NAWAWI_CHAPTER_3023 } from './3023-hadith-23-purity-is-half-of-faith';
import { NAWAWI_CHAPTER_3024 } from './3024-hadith-24-o-my-servants-i-have-forbidden-injustice';
import { NAWAWI_CHAPTER_3025 } from './3025-hadith-25-every-remembrance-of-allah-is-charity';
import { NAWAWI_CHAPTER_3026 } from './3026-hadith-26-every-joint-of-a-person-owes-charity';
import { NAWAWI_CHAPTER_3027 } from './3027-hadith-27-righteousness-is-good-character';
import { NAWAWI_CHAPTER_3028 } from './3028-hadith-28-hold-fast-to-my-sunnah';
import { NAWAWI_CHAPTER_3029 } from './3029-hadith-29-the-deed-that-admits-to-paradise';
import { NAWAWI_CHAPTER_3030 } from './3030-hadith-30-the-limits-allah-has-set';
import { NAWAWI_CHAPTER_3031 } from './3031-hadith-31-renounce-the-world-and-allah-will-love-you';
import { NAWAWI_CHAPTER_3032 } from './3032-hadith-32-there-is-no-harm-and-no-reciprocating-harm';
import { NAWAWI_CHAPTER_3033 } from './3033-hadith-33-the-proof-is-upon-the-claimant';
import { NAWAWI_CHAPTER_3034 } from './3034-hadith-34-changing-what-is-wrong';
import { NAWAWI_CHAPTER_3035 } from './3035-hadith-35-the-muslim-is-the-brother-of-the-muslim';
import { NAWAWI_CHAPTER_3036 } from './3036-hadith-36-whoever-relieves-a-believer-of-distress';
import { NAWAWI_CHAPTER_3037 } from './3037-hadith-37-how-good-and-bad-deeds-are-recorded';
import { NAWAWI_CHAPTER_3038 } from './3038-hadith-38-drawing-near-to-allah-by-the-obligatory-and-the-voluntary';
import { NAWAWI_CHAPTER_3039 } from './3039-hadith-39-mistake-forgetfulness-and-coercion-are-pardoned';
import { NAWAWI_CHAPTER_3040 } from './3040-hadith-40-be-in-this-world-as-a-stranger';
import { NAWAWI_CHAPTER_3041 } from './3041-hadith-41-until-his-desire-follows-what-i-have-brought';
import { NAWAWI_CHAPTER_3042 } from './3042-hadith-42-o-son-of-adam-so-long-as-you-call-upon-me';

export const NAWAWI_DATABASE: ChapterData[] = [
  NAWAWI_CHAPTER_3001,
  NAWAWI_CHAPTER_3002,
  NAWAWI_CHAPTER_3003,
  NAWAWI_CHAPTER_3004,
  NAWAWI_CHAPTER_3005,
  NAWAWI_CHAPTER_3006,
  NAWAWI_CHAPTER_3007,
  NAWAWI_CHAPTER_3008,
  NAWAWI_CHAPTER_3009,
  NAWAWI_CHAPTER_3010,
  NAWAWI_CHAPTER_3011,
  NAWAWI_CHAPTER_3012,
  NAWAWI_CHAPTER_3013,
  NAWAWI_CHAPTER_3014,
  NAWAWI_CHAPTER_3015,
  NAWAWI_CHAPTER_3016,
  NAWAWI_CHAPTER_3017,
  NAWAWI_CHAPTER_3018,
  NAWAWI_CHAPTER_3019,
  NAWAWI_CHAPTER_3020,
  NAWAWI_CHAPTER_3021,
  NAWAWI_CHAPTER_3022,
  NAWAWI_CHAPTER_3023,
  NAWAWI_CHAPTER_3024,
  NAWAWI_CHAPTER_3025,
  NAWAWI_CHAPTER_3026,
  NAWAWI_CHAPTER_3027,
  NAWAWI_CHAPTER_3028,
  NAWAWI_CHAPTER_3029,
  NAWAWI_CHAPTER_3030,
  NAWAWI_CHAPTER_3031,
  NAWAWI_CHAPTER_3032,
  NAWAWI_CHAPTER_3033,
  NAWAWI_CHAPTER_3034,
  NAWAWI_CHAPTER_3035,
  NAWAWI_CHAPTER_3036,
  NAWAWI_CHAPTER_3037,
  NAWAWI_CHAPTER_3038,
  NAWAWI_CHAPTER_3039,
  NAWAWI_CHAPTER_3040,
  NAWAWI_CHAPTER_3041,
  NAWAWI_CHAPTER_3042,
];
