// Generated by scripts/build-nawawi-chapters.mjs. Do not edit by hand.
//
// Slugs for the Forty Hadith collection — one page per hadith.

export interface ChapterSlugs {
  ru: string;
  en: string;
}

export const NAWAWI_CHAPTER_SLUGS: Record<number, ChapterSlugs> = {
  3001: { ru: "hadis-1-dela-ocenivayutsya-po-namereniyam", en: "hadith-1-actions-are-judged-by-intentions" }, // Дела оцениваются по намерениям
  3002: { ru: "hadis-2-islam-iman-i-ihsan", en: "hadith-2-islam-iman-and-ihsan" }, // Хадис Джибриля: ислам, иман и ихсан
  3003: { ru: "hadis-3-islam-postroen-na-pyati-stolpah", en: "hadith-3-islam-is-built-upon-five" }, // Ислам построен на пяти столпах
  3004: { ru: "hadis-4-sotvorenie-cheloveka-i-predopredelenie", en: "hadith-4-the-creation-of-man-and-the-decree" }, // Сотворение человека и предопределение
  3005: { ru: "hadis-5-novshestvo-v-religii-otvergaetsya", en: "hadith-5-an-innovation-in-the-religion-is-rejected" }, // Новшество в религии отвергается
  3006: { ru: "hadis-6-dozvolennoe-yasno-i-zapretnoe-yasno", en: "hadith-6-the-lawful-is-clear-and-the-unlawful-is-clear" }, // Дозволенное ясно и запретное ясно
  3007: { ru: "hadis-7-religiya-eto-iskrennost", en: "hadith-7-the-religion-is-sincere-counsel" }, // Религия — это искренность
  3008: { ru: "hadis-8-neprikosnovennost-musulmanina", en: "hadith-8-the-inviolability-of-the-muslim" }, // Неприкосновенность мусульманина
  3009: { ru: "hadis-9-delayte-to-chto-vam-po-silam", en: "hadith-9-do-what-you-are-able-to-do" }, // Делайте то, что вам по силам
  3010: { ru: "hadis-10-allah-prinimaet-tolko-chistoe", en: "hadith-10-allah-accepts-only-what-is-pure" }, // Аллах пречист и принимает только чистое
  3011: { ru: "hadis-11-ostav-to-chto-vyzyvaet-somnenie", en: "hadith-11-leave-what-makes-you-doubt" }, // Оставь то, что вызывает у тебя сомнение
  3012: { ru: "hadis-12-ostavit-to-chto-tebya-ne-kasaetsya", en: "hadith-12-leaving-what-does-not-concern-you" }, // Оставить то, что тебя не касается
  3013: { ru: "hadis-13-zhelat-bratu-togo-zhe-chego-sebe", en: "hadith-13-loving-for-your-brother-what-you-love-for-yourself" }, // Желать брату того же, чего себе
  3014: { ru: "hadis-14-krov-musulmanina-dozvolena-lish-v-treh-sluchayah", en: "hadith-14-the-blood-of-a-muslim-is-lawful-only-in-three-cases" }, // Кровь мусульманина дозволена лишь в трёх случаях
  3015: { ru: "hadis-15-pust-govorit-blagoe-ili-molchit", en: "hadith-15-let-him-speak-good-or-keep-silent" }, // Пусть говорит благое или молчит
  3016: { ru: "hadis-16-ne-gnevaysya", en: "hadith-16-do-not-become-angry" }, // Не гневайся
  3017: { ru: "hadis-17-allah-predpisal-sovershenstvo-vo-vsem", en: "hadith-17-allah-has-prescribed-excellence-in-everything" }, // Аллах предписал совершенство во всём
  3018: { ru: "hadis-18-boysya-allaha-gde-by-ty-ni-byl", en: "hadith-18-fear-allah-wherever-you-are" }, // Бойся Аллаха, где бы ты ни был
  3019: { ru: "hadis-19-pomni-ob-allahe-i-on-sohranit-tebya", en: "hadith-19-be-mindful-of-allah-and-he-will-protect-you" }, // Помни об Аллахе, и Он сохранит тебя
  3020: { ru: "hadis-20-esli-ne-stydishsya-delay-chto-hochesh", en: "hadith-20-if-you-feel-no-shame-do-as-you-wish" }, // Если не стыдишься — делай что хочешь
  3021: { ru: "hadis-21-skazhi-ya-uveroval-v-allaha-i-bud-stoek", en: "hadith-21-say-i-believe-in-allah-then-be-steadfast" }, // Скажи: «Я уверовал в Аллаха» — и будь стоек
  3022: { ru: "hadis-22-obyazatelnogo-dostatochno-dlya-raya", en: "hadith-22-the-obligatory-suffices-for-paradise" }, // Обязательного достаточно для Рая
  3023: { ru: "hadis-23-ochishchenie-polovina-very", en: "hadith-23-purity-is-half-of-faith" }, // Очищение — половина веры
  3024: { ru: "hadis-24-o-raby-moi-ya-zapretil-nespravedlivost", en: "hadith-24-o-my-servants-i-have-forbidden-injustice" }, // О рабы Мои, Я запретил несправедливость
  3025: { ru: "hadis-25-kazhdoe-pominanie-allaha-milostynya", en: "hadith-25-every-remembrance-of-allah-is-charity" }, // Каждое поминание Аллаха — милостыня
  3026: { ru: "hadis-26-kazhdyy-sustav-cheloveka-obyazan-milostyney", en: "hadith-26-every-joint-of-a-person-owes-charity" }, // Каждый сустав человека обязан милостыней
  3027: { ru: "hadis-27-blagochestie-eto-blagonravie", en: "hadith-27-righteousness-is-good-character" }, // Благочестие — это благонравие
  3028: { ru: "hadis-28-derzhites-moey-sunny", en: "hadith-28-hold-fast-to-my-sunnah" }, // Держитесь моей сунны
  3029: { ru: "hadis-29-delo-vvodyashchee-v-ray", en: "hadith-29-the-deed-that-admits-to-paradise" }, // Дело, вводящее в Рай
  3030: { ru: "hadis-30-granicy-ustanovlennye-allahom", en: "hadith-30-the-limits-allah-has-set" }, // Границы, установленные Аллахом
  3031: { ru: "hadis-31-otreshis-ot-mirskogo-i-tebya-polyubit-allah", en: "hadith-31-renounce-the-world-and-allah-will-love-you" }, // Отрешись от мирского — и тебя полюбит Аллах
  3032: { ru: "hadis-32-ne-prichinyat-vreda-i-ne-otvechat-vredom", en: "hadith-32-there-is-no-harm-and-no-reciprocating-harm" }, // Не причинять вреда и не отвечать вредом
  3033: { ru: "hadis-33-dokazatelstvo-na-istce-klyatva-na-otvetchike", en: "hadith-33-the-proof-is-upon-the-claimant" }, // Доказательство — на истце, клятва — на ответчике
  3034: { ru: "hadis-34-izmenenie-poricaemogo", en: "hadith-34-changing-what-is-wrong" }, // Изменение порицаемого
  3035: { ru: "hadis-35-musulmanin-brat-musulmaninu", en: "hadith-35-the-muslim-is-the-brother-of-the-muslim" }, // Мусульманин — брат мусульманину
  3036: { ru: "hadis-36-kto-izbavit-veruyushchego-ot-pechali", en: "hadith-36-whoever-relieves-a-believer-of-distress" }, // Кто избавит верующего от печали
  3037: { ru: "hadis-37-kak-zapisyvayutsya-blagie-i-durnye-dela", en: "hadith-37-how-good-and-bad-deeds-are-recorded" }, // Как записываются благие и дурные дела
  3038: { ru: "hadis-38-priblizhenie-k-allahu-obyazatelnym-i-dobrovolnym", en: "hadith-38-drawing-near-to-allah-by-the-obligatory-and-the-voluntary" }, // Приближение к Аллаху обязательным и добровольным
  3039: { ru: "hadis-39-proshcheny-oshibka-zabyvchivost-i-prinuzhdenie", en: "hadith-39-mistake-forgetfulness-and-coercion-are-pardoned" }, // Прощены ошибка, забывчивость и принуждение
  3040: { ru: "hadis-40-bud-v-etom-mire-kak-chuzhezemec", en: "hadith-40-be-in-this-world-as-a-stranger" }, // Будь в этом мире как чужеземец
  3041: { ru: "hadis-41-poka-zhelanie-ne-posleduet-za-prinesennym-mnoy", en: "hadith-41-until-his-desire-follows-what-i-have-brought" }, // Пока желание не последует за принесённым мной
  3042: { ru: "hadis-42-o-syn-adama-poka-ty-vzyvaesh-ko-mne", en: "hadith-42-o-son-of-adam-so-long-as-you-call-upon-me" }, // О сын Адама, пока ты взываешь ко Мне
};
