// Generated by scripts/build-quran-chapters.mjs. Do not edit by hand.
//
// Slugs for the Quranic supplications collection — one landing page per sura.

export interface ChapterSlugs {
  ru: string;
  en: string;
}

export const QURAN_CHAPTER_SLUGS: Record<number, ChapterSlugs> = {
  2001: { ru: "dua-iz-sury-al-fatiha", en: "duas-from-surah-al-fatihah" }, // Дуа из суры «Аль-Фатиха»
  2002: { ru: "dua-iz-sury-al-bakara", en: "duas-from-surah-al-baqarah" }, // Дуа из суры «Аль-Бакара»
  2003: { ru: "dua-iz-sury-al-imran", en: "duas-from-surah-al-imran" }, // Дуа из суры «Аль Имран»
  2004: { ru: "dua-iz-sury-an-nisa", en: "duas-from-surah-an-nisa" }, // Дуа из суры «Ан-Ниса»
  2005: { ru: "dua-iz-sury-al-maida", en: "duas-from-surah-al-maidah" }, // Дуа из суры «Аль-Маида»
  2006: { ru: "dua-iz-sury-al-anam", en: "duas-from-surah-al-anam" }, // Дуа из суры «Аль-Ан‘ам»
  2007: { ru: "dua-iz-sury-al-araf", en: "duas-from-surah-al-araf" }, // Дуа из суры «Аль-А‘раф»
  2008: { ru: "dua-iz-sury-at-tauba", en: "duas-from-surah-at-tawbah" }, // Дуа из суры «Ат-Тауба»
  2009: { ru: "dua-iz-sury-yunus", en: "duas-from-surah-yunus" }, // Дуа из суры «Юнус»
  2010: { ru: "dua-iz-sury-hud", en: "duas-from-surah-hud" }, // Дуа из суры «Худ»
  2011: { ru: "dua-iz-sury-yusuf", en: "duas-from-surah-yusuf" }, // Дуа из суры «Юсуф»
  2012: { ru: "dua-iz-sury-ibrahim", en: "duas-from-surah-ibrahim" }, // Дуа из суры «Ибрахим»
  2013: { ru: "dua-iz-sury-al-isra", en: "duas-from-surah-al-isra" }, // Дуа из суры «Аль-Исра»
  2014: { ru: "dua-iz-sury-al-kahf", en: "duas-from-surah-al-kahf" }, // Дуа из суры «Аль-Кахф»
  2015: { ru: "dua-iz-sury-maryam", en: "duas-from-surah-maryam" }, // Дуа из суры «Марьям»
  2016: { ru: "dua-iz-sury-ta-ha", en: "duas-from-surah-ta-ha" }, // Дуа из суры «Та Ха»
  2017: { ru: "dua-iz-sury-al-anbiya", en: "duas-from-surah-al-anbiya" }, // Дуа из суры «Аль-Анбия»
  2018: { ru: "dua-iz-sury-al-muminun", en: "duas-from-surah-al-muminun" }, // Дуа из суры «Аль-Муминун»
  2019: { ru: "dua-iz-sury-al-furkan", en: "duas-from-surah-al-furqan" }, // Дуа из суры «Аль-Фуркан»
  2020: { ru: "dua-iz-sury-ash-shuara", en: "duas-from-surah-ash-shuara" }, // Дуа из суры «Аш-Шуара»
  2021: { ru: "dua-iz-sury-an-naml", en: "duas-from-surah-an-naml" }, // Дуа из суры «Ан-Намль»
  2022: { ru: "dua-iz-sury-al-kasas", en: "duas-from-surah-al-qasas" }, // Дуа из суры «Аль-Касас»
  2023: { ru: "dua-iz-sury-al-ankabut", en: "duas-from-surah-al-ankabut" }, // Дуа из суры «Аль-Анкабут»
  2024: { ru: "dua-iz-sury-as-saffat", en: "duas-from-surah-as-saffat" }, // Дуа из суры «Ас-Саффат»
  2025: { ru: "dua-iz-sury-sad", en: "duas-from-surah-sad" }, // Дуа из суры «Сад»
  2026: { ru: "dua-iz-sury-az-zumar", en: "duas-from-surah-az-zumar" }, // Дуа из суры «Аз-Зумар»
  2027: { ru: "dua-iz-sury-gafir", en: "duas-from-surah-ghafir" }, // Дуа из суры «Гафир»
  2028: { ru: "dua-iz-sury-az-zuhruf", en: "duas-from-surah-az-zukhruf" }, // Дуа из суры «Аз-Зухруф»
  2029: { ru: "dua-iz-sury-ad-duhan", en: "duas-from-surah-ad-dukhan" }, // Дуа из суры «Ад-Духан»
  2030: { ru: "dua-iz-sury-al-ahkaf", en: "duas-from-surah-al-ahqaf" }, // Дуа из суры «Аль-Ахкаф»
  2031: { ru: "dua-iz-sury-al-kamar", en: "duas-from-surah-al-qamar" }, // Дуа из суры «Аль-Камар»
  2032: { ru: "dua-iz-sury-al-hashr", en: "duas-from-surah-al-hashr" }, // Дуа из суры «Аль-Хашр»
  2033: { ru: "dua-iz-sury-al-mumtahana", en: "duas-from-surah-al-mumtahanah" }, // Дуа из суры «Аль-Мумтахана»
  2034: { ru: "dua-iz-sury-at-tahrim", en: "duas-from-surah-at-tahrim" }, // Дуа из суры «Ат-Тахрим»
  2035: { ru: "dua-iz-sury-nuh", en: "duas-from-surah-nuh" }, // Дуа из суры «Нух»
  2036: { ru: "dua-iz-sury-al-falyak-i-an-nas", en: "duas-from-surah-al-falaq-and-an-nas" }, // Дуа из сур «Аль-Фаляк» и «Ан-Нас»
};

export function getQuranChapterSlug(id: number, lang: "ru" | "en"): string {
  const s = QURAN_CHAPTER_SLUGS[id];
  if (!s) throw new Error(`No Quran slug for chapter ${id}`);
  return s[lang];
}
