import type { ChapterData, Language } from '../../types';
import { CHAPTER_SLUGS } from '../../data/slugs';
import { CATEGORIES } from '../../data/categories';
import {
  buildCategoriesIndexPath,
  buildCategoryPath,
  buildChapterPath,
  buildHomePath,
  buildPrayerTimesPath,
  matchRoute,
} from '../router/routes';

export interface MetaInput {
  title: string;
  description: string;
  lang: Language;
  path: string;
  chapterId?: number;
  chapterTitle?: string;
  chapterDescription?: string;
  chapter?: ChapterData;
}

export interface MetaOutput {
  title: string;
  lang: Language;
  description: string;
  canonical: string;
  hreflang: { ru: string; en: string; xDefault: string };
  og: { title: string; description: string; url: string; locale: string; image: string };
  twitter: { title: string; description: string; image: string };
  jsonLd: Array<{ id: string; data: object }>;
}

const SITE = 'https://dua.shakhbanov.org';

// --- Pure builder — safe to call on server during SSR ---

export function buildMetaTags(m: MetaInput): MetaOutput {
  const url = `${SITE}${m.path}`;
  const { ru: altRu, en: altEn } = buildHreflangAlternates(m);

  const jsonLd: Array<{ id: string; data: object }> = [];

  if (m.chapterId && m.chapter) {
    jsonLd.push({ id: 'ld-article', data: articleSchema(m, url) });
    jsonLd.push({ id: 'ld-breadcrumb', data: breadcrumbSchema(m, url) });

    const audioObjects = audioObjectsSchema(m.chapter, m.lang);
    if (audioObjects.length > 0) {
      jsonLd.push({ id: 'ld-audio', data: { '@context': 'https://schema.org', '@graph': audioObjects } });
    }

    const faq = faqPageSchema(m.chapter, m.lang);
    if (faq) jsonLd.push({ id: 'ld-faq', data: faq });
  }

  const ogImage = resolveOgImage(m);

  return {
    title: m.title,
    lang: m.lang,
    description: m.description,
    canonical: url,
    hreflang: { ru: altRu, en: altEn, xDefault: altRu },
    og: {
      title: m.title,
      description: m.description,
      url,
      locale: m.lang === 'ru' ? 'ru_RU' : 'en_US',
      image: ogImage,
    },
    twitter: { title: m.title, description: m.description, image: ogImage },
    jsonLd,
  };
}

// Pick the per-chapter OG image if available; otherwise fall back to page-type
// defaults (home.png / prayer-times.png) generated by scripts/generate-og-images.mjs.
function resolveOgImage(m: MetaInput): string {
  if (m.chapterId) {
    const slugs = CHAPTER_SLUGS[m.chapterId];
    if (slugs) {
      const slug = m.lang === 'ru' ? slugs.ru : slugs.en;
      return `${SITE}/og/${slug}.png`;
    }
  }
  const matched = matchRoute(m.path);
  if (matched?.view === 'prayer-times') return `${SITE}/og/prayer-times.png`;
  if (matched?.view === 'category' && matched.categoryId) {
    // No dedicated per-category OG (yet) — use a representative chapter from
    // the category if available; otherwise fall back to home.
    const cat = CATEGORIES.find((c) => c.id === matched.categoryId);
    const repId = cat?.chapterIds[0];
    if (repId) {
      const slugs = CHAPTER_SLUGS[repId];
      if (slugs) {
        const slug = m.lang === 'ru' ? slugs.ru : slugs.en;
        return `${SITE}/og/${slug}.png`;
      }
    }
  }
  return `${SITE}/og/home.png`;
}

// Resolves the RU and EN variants of a clean path by consulting the route table.
// Works for both languages: given /slova-.../, returns { ru: /slova-.../, en: /en/supplications-.../ }.
function buildHreflangAlternates(m: MetaInput): { ru: string; en: string } {
  const matched = matchRoute(m.path);
  if (matched) {
    const view = matched.view;
    if (view === 'chapter' && matched.chapterId) {
      return {
        ru: `${SITE}${buildChapterPath(matched.chapterId, 'ru')}`,
        en: `${SITE}${buildChapterPath(matched.chapterId, 'en')}`,
      };
    }
    if (view === 'prayer-times') {
      return {
        ru: `${SITE}${buildPrayerTimesPath('ru')}`,
        en: `${SITE}${buildPrayerTimesPath('en')}`,
      };
    }
    if (view === 'categories-index') {
      return {
        ru: `${SITE}${buildCategoriesIndexPath('ru')}`,
        en: `${SITE}${buildCategoriesIndexPath('en')}`,
      };
    }
    if (view === 'category' && matched.categoryId) {
      return {
        ru: `${SITE}${buildCategoryPath(matched.categoryId, 'ru')}`,
        en: `${SITE}${buildCategoryPath(matched.categoryId, 'en')}`,
      };
    }
    // Home
    return {
      ru: `${SITE}${buildHomePath('ru')}`,
      en: `${SITE}${buildHomePath('en')}`,
    };
  }

  // Fallback: derive from chapterId if we have one; otherwise home.
  if (m.chapterId) {
    return {
      ru: `${SITE}${buildChapterPath(m.chapterId, 'ru')}`,
      en: `${SITE}${buildChapterPath(m.chapterId, 'en')}`,
    };
  }
  return {
    ru: `${SITE}${buildHomePath('ru')}`,
    en: `${SITE}${buildHomePath('en')}`,
  };
}

// --- JSON-LD builders ---

function articleSchema(m: MetaInput, url: string): object {
  const ch = m.chapter!;
  const citations = dedupe(
    ch.duas
      .map((d) => d.source?.[m.lang]?.trim())
      .filter((s): s is string => !!s)
  );
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: m.chapterTitle ?? ch.title[m.lang],
    description: m.chapterDescription ?? m.description,
    inLanguage: m.lang,
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    author: { '@type': 'Organization', name: 'dua.shakhbanov.org' },
    publisher: {
      '@type': 'Organization',
      name: m.lang === 'ru' ? 'Дуа' : 'Dua',
      logo: { '@type': 'ImageObject', url: `${SITE}/icons/icon-512.png` },
    },
    isPartOf: {
      '@type': 'CreativeWork',
      name: m.lang === 'ru' ? 'Дуа и азкары из Сунны' : 'Duas and adhkar from the Sunnah',
      inLanguage: m.lang,
    },
    ...(citations.length > 0 && { citation: citations }),
  };
}

function breadcrumbSchema(m: MetaInput, url: string): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: m.lang === 'ru' ? 'Главная' : 'Home', item: SITE },
      { '@type': 'ListItem', position: 2, name: m.chapterTitle ?? m.chapter?.title[m.lang], item: url },
    ],
  };
}

function audioObjectsSchema(chapter: ChapterData, lang: Language): object[] {
  return chapter.duas
    .filter((d) => d.audioUrl)
    .map((d, i) => ({
      '@type': 'AudioObject',
      '@id': `${SITE}/?chapter=${chapter.id}#dua-${d.id}`,
      name: `${chapter.title[lang]} — ${lang === 'ru' ? 'дуа' : 'dua'} ${d.id}`,
      contentUrl: d.audioUrl,
      encodingFormat: 'audio/wav',
      inLanguage: 'ar',
      ...(d.fullTranslation?.[lang] && {
        transcript: oneLine(d.fullTranslation[lang]).slice(0, 1000),
      }),
      isPartOf: {
        '@type': 'CreativeWork',
        name: chapter.title[lang],
        inLanguage: lang,
      },
      position: i + 1,
    }));
}

// Chapters framed as "what to say when/for/upon X" are natural FAQPage candidates.
const FAQ_TITLE_PATTERNS: RegExp[] = [
  /^Что\s+(говорить|говорят|следует\s+сказать|делать|делают)/i,
  /^Слова\s+(поминания|мольбы|обращения)/i,
  /^Супплик/i,
  /^Мольб/i,
  /^Дуа\s+(для|при|перед|после|во|когда)/i,
  /^What\s+to\s+(say|do)/i,
  /^Supplication(?:s)?\s+(when|for|upon|against|before|after|while|to|at|of|on)/i,
  /^The\s+(groom|traveler|resident|talbiyah|takbir|tashahhud)/i,
  /^Prayer\s+(during|of|for|upon|on)/i,
  /^Remembrance\s+(after|in|while|immediately)/i,
  /^How\s+to/i,
  /^Asking\s+for/i,
  /^Upon\s+(sighting|seeing|encountering|breaking|hearing)/i,
  /^When\s+(visiting|entering|leaving|closing|mounting)/i,
  /^Placing\s+/i,
  /^Instruction\s+/i,
  /^Congratulations\s+/i,
  /^Condolence/i,
  /^Seeking\s+/i,
  /^Protection\s+/i,
  /^Praying\s+for/i,
  /^The\s+etiquette/i,
  /^Excellence\s+of/i,
  /^Virtues\s+of/i,
];

function matchesFaqPattern(chapter: ChapterData): boolean {
  const titles = [chapter.title.ru, chapter.title.en];
  return titles.some((t) => FAQ_TITLE_PATTERNS.some((re) => re.test(t)));
}

function faqPageSchema(chapter: ChapterData, lang: Language): object | null {
  if (!matchesFaqPattern(chapter)) return null;
  if (chapter.duas.length === 0) return null;

  const questionPrefix = lang === 'ru' ? 'Какое дуа/азкар: ' : 'What supplication: ';
  const sourcePrefix = lang === 'ru' ? 'Источник' : 'Source';

  const mainEntity = chapter.duas
    .filter((d) => d.fullTranslation?.[lang])
    .map((d) => {
      const translation = oneLine(d.fullTranslation[lang]);
      const source = d.source?.[lang] ? ` (${sourcePrefix}: ${oneLine(d.source[lang])})` : '';
      return {
        '@type': 'Question',
        name: `${questionPrefix}${chapter.title[lang]}${chapter.duas.length > 1 ? ` — ${d.id}` : ''}`,
        acceptedAnswer: {
          '@type': 'Answer',
          text: translation + source,
          inLanguage: lang,
        },
      };
    });

  if (mainEntity.length === 0) return null;

  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    inLanguage: lang,
    mainEntity,
  };
}

function dedupe(arr: string[]): string[] {
  return Array.from(new Set(arr));
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

// --- DOM-mutating wrapper — used on the client for in-SPA nav ---

function setAttr(selector: string, attr: string, value: string): void {
  let el = document.head.querySelector(selector) as HTMLElement | null;
  if (!el) {
    const tag = selector.startsWith('link') ? 'link' : 'meta';
    el = document.createElement(tag);
    const attrMatch = selector.match(/\[([^\]]+)\]/g);
    attrMatch?.forEach((a) => {
      const [k, v] = a.slice(1, -1).split('=');
      if (k && v) el!.setAttribute(k, v.replace(/^["']|["']$/g, ''));
    });
    document.head.appendChild(el);
  }
  el.setAttribute(attr, value);
}

function setJsonLd(id: string, data: object): void {
  let el = document.getElementById(id) as HTMLScriptElement | null;
  if (!el) {
    el = document.createElement('script');
    el.id = id;
    el.type = 'application/ld+json';
    document.head.appendChild(el);
  }
  el.textContent = JSON.stringify(data);
}

const MANAGED_JSONLD_IDS = ['ld-article', 'ld-breadcrumb', 'ld-audio', 'ld-faq'];

export function applyMetaTags(out: MetaOutput): void {
  document.title = out.title;
  document.documentElement.setAttribute('lang', out.lang);

  setAttr('meta[name="description"]', 'content', out.description);
  setAttr('link[rel="canonical"]', 'href', out.canonical);

  setAttr('link[rel="alternate"][hreflang="ru"]', 'href', out.hreflang.ru);
  setAttr('link[rel="alternate"][hreflang="en"]', 'href', out.hreflang.en);
  setAttr('link[rel="alternate"][hreflang="x-default"]', 'href', out.hreflang.xDefault);

  setAttr('meta[property="og:title"]', 'content', out.og.title);
  setAttr('meta[property="og:description"]', 'content', out.og.description);
  setAttr('meta[property="og:url"]', 'content', out.og.url);
  setAttr('meta[property="og:locale"]', 'content', out.og.locale);
  setAttr('meta[property="og:image"]', 'content', out.og.image);

  setAttr('meta[name="twitter:title"]', 'content', out.twitter.title);
  setAttr('meta[name="twitter:description"]', 'content', out.twitter.description);
  setAttr('meta[name="twitter:image"]', 'content', out.twitter.image);

  const presentIds = new Set(out.jsonLd.map((j) => j.id));
  for (const id of MANAGED_JSONLD_IDS) {
    if (!presentIds.has(id)) document.getElementById(id)?.remove();
  }
  for (const { id, data } of out.jsonLd) {
    setJsonLd(id, data);
  }
}

export function updateMetaTags(m: MetaInput): void {
  applyMetaTags(buildMetaTags(m));
}
