import type { ChapterData, Collection, Language } from '../../types';
import { CHAPTER_SLUGS } from '../../data/slugs';
import { CATEGORIES } from '../../data/categories';
import {
  chapterCollection,
  collectionOfChapterId,
  duaAudioSegments,
  getCollection,
  getSlug,
} from '../../data/collections';
import chapterDates from '../../data/chapterDates.generated.json';

const CHAPTER_DATES: Record<number, { published: string; modified: string }> = chapterDates;
import {
  buildAboutPath,
  buildCategoriesIndexPath,
  buildCategoryPath,
  buildChapterPath,
  buildCollectionIndexPath,
  buildHomePath,
  buildPrayerTimesPath,
  matchRoute,
} from '../router/routes';

export interface MetaInput {
  title: string;
  description: string;
  lang: Language;
  path: string;
  chapterId?: number;
  chapterTitle?: string;
  chapterDescription?: string;
  chapter?: ChapterData;
}

export interface MetaOutput {
  title: string;
  lang: Language;
  description: string;
  canonical: string;
  hreflang: { ru: string; en: string; xDefault: string };
  og: { type: 'website' | 'article'; siteName: string; title: string; description: string; url: string; locale: string; image: string };
  twitter: { title: string; description: string; image: string };
  jsonLd: Array<{ id: string; data: object }>;
}

const SITE = 'https://dua.shakhbanov.org';

const SITE_NAME: Record<Language, string> = { ru: 'Дуа', en: 'Dua' };

// The person who compiles and maintains the collection. Named with their own
// consent; the About page carries the same claim in visible text.
const COMPILER: Record<Language, string> = { ru: 'Зураб Шахбанов', en: 'Zurab Shakhbanov' };

// --- Pure builder — safe to call on server during SSR ---

export function buildMetaTags(m: MetaInput): MetaOutput {
  const url = `${SITE}${m.path}`;
  const { ru: altRu, en: altEn } = buildHreflangAlternates(m);

  const jsonLd: Array<{ id: string; data: object }> = [];

  if (m.chapterId && m.chapter) {
    jsonLd.push({ id: 'ld-article', data: articleSchema(m, url) });
    jsonLd.push({ id: 'ld-breadcrumb', data: breadcrumbSchema(m, url) });

    const audioObjects = audioObjectsSchema(m.chapter, m.lang);
    if (audioObjects.length > 0) {
      jsonLd.push({ id: 'ld-audio', data: { '@context': 'https://schema.org', '@graph': audioObjects } });
    }
  }

  // Site-level identity belongs on the home page only. It used to be a static
  // block in index.html, which copied it — and a Sunnah-specific description —
  // onto all 372 pages including the Quran collection.
  const matched = matchRoute(m.path);
  if (matched?.view === 'home') {
    jsonLd.push({ id: 'ld-website', data: webSiteSchema(m.lang) });
    jsonLd.push({ id: 'ld-organization', data: organizationSchema(m.lang) });
  }
  if (matched?.view === 'about') {
    jsonLd.push({ id: 'ld-person', data: personSchema(m.lang) });
  }
  if (matched?.view === 'collection-index') {
    jsonLd.push({ id: 'ld-collection', data: collectionSchema(matched.collection, m.lang) });
  }

  const ogImage = resolveOgImage(m);

  return {
    title: m.title,
    lang: m.lang,
    description: m.description,
    canonical: url,
    hreflang: { ru: altRu, en: altEn, xDefault: altRu },
    og: {
      type: m.chapterId && m.chapter ? 'article' : 'website',
      siteName: SITE_NAME[m.lang],
      title: m.title,
      description: m.description,
      url,
      locale: m.lang === 'ru' ? 'ru_RU' : 'en_US',
      image: ogImage,
    },
    twitter: { title: m.title, description: m.description, image: ogImage },
    jsonLd,
  };
}

// Pick the per-chapter OG image if available; otherwise fall back to page-type
// defaults (home.png / prayer-times.png) generated by scripts/generate-og-images.mjs.
function resolveOgImage(m: MetaInput): string {
  if (m.chapterId) {
    try {
      const slug = getSlug(collectionOfChapterId(m.chapterId), m.chapterId, m.lang);
      return `${SITE}/og/${slug}.png`;
    } catch {
      // Unknown chapter id — fall through to the page-type defaults.
    }
  }
  const matched = matchRoute(m.path);
  if (matched?.view === 'prayer-times') return `${SITE}/og/prayer-times.png`;
  if (matched?.view === 'collection-index') return `${SITE}/og/${matched.collection}-index.png`;
  if (matched?.view === 'category' && matched.categoryId) {
    // No dedicated per-category OG (yet) — use a representative chapter from
    // the category if available; otherwise fall back to home.
    const cat = CATEGORIES.find((c) => c.id === matched.categoryId);
    const repId = cat?.chapterIds[0];
    if (repId) {
      const slugs = CHAPTER_SLUGS[repId];
      if (slugs) {
        const slug = m.lang === 'ru' ? slugs.ru : slugs.en;
        return `${SITE}/og/${slug}.png`;
      }
    }
  }
  return `${SITE}/og/home.png`;
}

// Resolves the RU and EN variants of a clean path by consulting the route table.
// Works for both languages: given /slova-.../, returns { ru: /slova-.../, en: /en/supplications-.../ }.
function buildHreflangAlternates(m: MetaInput): { ru: string; en: string } {
  const matched = matchRoute(m.path);
  if (matched) {
    const view = matched.view;
    if (view === 'chapter' && matched.chapterId) {
      return {
        ru: `${SITE}${buildChapterPath(matched.chapterId, 'ru')}`,
        en: `${SITE}${buildChapterPath(matched.chapterId, 'en')}`,
      };
    }
    if (view === 'prayer-times') {
      return {
        ru: `${SITE}${buildPrayerTimesPath('ru')}`,
        en: `${SITE}${buildPrayerTimesPath('en')}`,
      };
    }
    if (view === 'collection-index') {
      return {
        ru: `${SITE}${buildCollectionIndexPath(matched.collection, 'ru')}`,
        en: `${SITE}${buildCollectionIndexPath(matched.collection, 'en')}`,
      };
    }
    if (view === 'about') {
      return { ru: `${SITE}${buildAboutPath('ru')}`, en: `${SITE}${buildAboutPath('en')}` };
    }
    if (view === 'categories-index') {
      return {
        ru: `${SITE}${buildCategoriesIndexPath('ru')}`,
        en: `${SITE}${buildCategoriesIndexPath('en')}`,
      };
    }
    if (view === 'category' && matched.categoryId) {
      return {
        ru: `${SITE}${buildCategoryPath(matched.categoryId, 'ru')}`,
        en: `${SITE}${buildCategoryPath(matched.categoryId, 'en')}`,
      };
    }
    // Home
    return {
      ru: `${SITE}${buildHomePath('ru')}`,
      en: `${SITE}${buildHomePath('en')}`,
    };
  }

  // Fallback: derive from chapterId if we have one; otherwise home.
  if (m.chapterId) {
    return {
      ru: `${SITE}${buildChapterPath(m.chapterId, 'ru')}`,
      en: `${SITE}${buildChapterPath(m.chapterId, 'en')}`,
    };
  }
  return {
    ru: `${SITE}${buildHomePath('ru')}`,
    en: `${SITE}${buildHomePath('en')}`,
  };
}

// --- JSON-LD builders ---

function webSiteSchema(lang: Language): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE}/#website`,
    name: SITE_NAME[lang],
    alternateName: lang === 'ru' ? ['Dua'] : ['Дуа'],
    url: `${SITE}/`,
    inLanguage: ['ru', 'en'],
    publisher: { '@id': `${SITE}/#organization` },
    // No SearchAction: there is no /?q= endpoint to advertise.
  };
}

// Only asserts what the About page states in visible text and what the
// repository can be checked against.
function personSchema(lang: Language): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': `${SITE}/#compiler`,
    name: COMPILER[lang],
    url: `${SITE}${buildAboutPath(lang)}`,
    sameAs: ['https://github.com/shakhbanov'],
    mainEntityOfPage: { '@id': `${SITE}${buildAboutPath(lang)}` },
  };
}

function organizationSchema(lang: Language): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': `${SITE}/#organization`,
    name: SITE_NAME[lang],
    url: `${SITE}/`,
    logo: { '@type': 'ImageObject', url: `${SITE}/icons/icon-512.png`, width: 512, height: 512 },
  };
}

// The collection landing pages are the only place a claim about *this*
// collection's sourcing is true, so that is the only place it is made.
function collectionSchema(collection: Collection, lang: Language): object {
  const coll = getCollection(collection);
  return {
    '@context': 'https://schema.org',
    '@type': 'Collection',
    '@id': `${SITE}${buildCollectionIndexPath(collection, lang)}#collection`,
    name: coll.title[lang],
    description: coll.summary[lang],
    inLanguage: lang,
    isPartOf: { '@id': `${SITE}/#website` },
    numberOfItems: coll.chapters.length,
  };
}

function articleSchema(m: MetaInput, url: string): object {
  const ch = m.chapter!;
  const citations = dedupe(
    ch.duas
      .map((d) => d.source?.[m.lang]?.trim())
      .filter((s): s is string => !!s)
  );
  const collection = chapterCollection(ch);
  // Absent from CHAPTER_DATES means git could not date the chapter's source
  // file. No date is emitted then — a missing date beats an invented one.
  const dates = CHAPTER_DATES[ch.id];
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    '@id': `${url}#article`,
    headline: m.chapterTitle ?? ch.title[m.lang],
    description: m.chapterDescription ?? m.description,
    inLanguage: m.lang,
    url,
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    image: resolveOgImage(m),
    ...(dates && { datePublished: dates.published, dateModified: dates.modified }),
    author: {
      '@type': 'Person',
      '@id': `${SITE}/#compiler`,
      name: COMPILER[m.lang],
      url: `${SITE}${buildAboutPath(m.lang)}`,
    },
    publisher: { '@id': `${SITE}/#organization` },
    isPartOf: {
      '@type': 'Collection',
      '@id': `${SITE}${buildCollectionIndexPath(collection, m.lang)}#collection`,
      name: getCollection(collection).title[m.lang],
      inLanguage: m.lang,
    },
    ...(citations.length > 0 && { citation: citations }),
  };
}

/** Mirrors the visible breadcrumb trail and the depth of the URL itself. */
export function breadcrumbTrail(
  m: { lang: Language; path: string; chapter?: ChapterData; chapterTitle?: string }
): Array<{ name: string; item: string }> {
  const trail = [
    { name: m.lang === 'ru' ? 'Главная' : 'Home', item: `${SITE}${buildHomePath(m.lang)}` },
  ];
  if (m.chapter) {
    const collection = chapterCollection(m.chapter);
    // The Sunnah collection's index *is* the home page — listing it twice
    // would claim a level the URL does not have.
    if (collection !== 'sunna') {
      trail.push({
        name: getCollection(collection).title[m.lang],
        item: `${SITE}${buildCollectionIndexPath(collection, m.lang)}`,
      });
    }
    trail.push({
      name: m.chapterTitle ?? m.chapter.title[m.lang],
      item: `${SITE}${m.path}`,
    });
  }
  return trail;
}

function breadcrumbSchema(m: MetaInput, _url: string): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: breadcrumbTrail(m).map((step, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: step.name,
      item: step.item,
    })),
  };
}

function audioObjectsSchema(chapter: ChapterData, lang: Language): object[] {
  // One pass: duas without audio are skipped as we go, so the list is walked
  // once instead of being mapped, filtered and mapped again.
  const objects: object[] = [];
  chapter.duas.forEach((d, i) => {
    const segments = duaAudioSegments(d);
    if (segments.length === 0) return;
    objects.push({
      '@type': 'AudioObject',
      '@id': `${SITE}${buildChapterPath(chapter.id, lang)}#dua-${d.id}`,
      name: `${chapter.title[lang]} — ${lang === 'ru' ? 'дуа' : 'dua'} ${d.id}`,
      // A Quranic dua spanning several ayahs has one file per ayah; the first
      // is the primary contentUrl and the rest are listed as associated media.
      contentUrl: segments[0],
      ...(segments.length > 1 && { associatedMedia: segments.slice(1).map((url) => ({ '@type': 'AudioObject', contentUrl: url })) }),
      encodingFormat: segments[0].endsWith('.mp3') ? 'audio/mpeg' : 'audio/wav',
      inLanguage: 'ar',
      ...(d.fullTranslation?.[lang] && {
        transcript: oneLine(d.fullTranslation[lang]).slice(0, 1000),
      }),
      isPartOf: { '@id': `${SITE}${buildChapterPath(chapter.id, lang)}#article` },
      position: i + 1,
    });
  });
  return objects;
}

function dedupe(arr: string[]): string[] {
  return Array.from(new Set(arr));
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

// --- DOM-mutating wrapper — used on the client for in-SPA nav ---

function setAttr(selector: string, attr: string, value: string): void {
  let el = document.head.querySelector(selector) as HTMLElement | null;
  if (!el) {
    const tag = selector.startsWith('link') ? 'link' : 'meta';
    el = document.createElement(tag);
    const attrMatch = selector.match(/\[([^\]]+)\]/g);
    attrMatch?.forEach((a) => {
      const [k, v] = a.slice(1, -1).split('=');
      if (k && v) el!.setAttribute(k, v.replace(/^["']|["']$/g, ''));
    });
    document.head.appendChild(el);
  }
  el.setAttribute(attr, value);
}

function setJsonLd(id: string, data: object): void {
  let el = document.getElementById(id) as HTMLScriptElement | null;
  if (!el) {
    el = document.createElement('script');
    el.id = id;
    el.type = 'application/ld+json';
    document.head.appendChild(el);
  }
  el.textContent = JSON.stringify(data);
}

const MANAGED_JSONLD_IDS = [
  'ld-article',
  'ld-breadcrumb',
  'ld-audio',
  'ld-website',
  'ld-organization',
  'ld-collection',
  'ld-person',
];

export function applyMetaTags(out: MetaOutput): void {
  document.title = out.title;
  document.documentElement.setAttribute('lang', out.lang);

  setAttr('meta[name="description"]', 'content', out.description);
  setAttr('link[rel="canonical"]', 'href', out.canonical);

  setAttr('link[rel="alternate"][hreflang="ru"]', 'href', out.hreflang.ru);
  setAttr('link[rel="alternate"][hreflang="en"]', 'href', out.hreflang.en);
  setAttr('link[rel="alternate"][hreflang="x-default"]', 'href', out.hreflang.xDefault);

  setAttr('meta[property="og:type"]', 'content', out.og.type);
  setAttr('meta[property="og:site_name"]', 'content', out.og.siteName);
  setAttr('meta[property="og:title"]', 'content', out.og.title);
  setAttr('meta[property="og:description"]', 'content', out.og.description);
  setAttr('meta[property="og:url"]', 'content', out.og.url);
  setAttr('meta[property="og:locale"]', 'content', out.og.locale);
  setAttr('meta[property="og:image"]', 'content', out.og.image);

  setAttr('meta[name="twitter:title"]', 'content', out.twitter.title);
  setAttr('meta[name="twitter:description"]', 'content', out.twitter.description);
  setAttr('meta[name="twitter:image"]', 'content', out.twitter.image);

  const presentIds = new Set(out.jsonLd.map((j) => j.id));
  for (const id of MANAGED_JSONLD_IDS) {
    if (!presentIds.has(id)) document.getElementById(id)?.remove();
  }
  for (const { id, data } of out.jsonLd) {
    setJsonLd(id, data);
  }
}

export function updateMetaTags(m: MetaInput): void {
  applyMetaTags(buildMetaTags(m));
}
