#!/usr/bin/env node
// One-off generator for data/slugs.ts.
// EN slug = derived from chapter filename (already in English).
// RU slug = transliteration of title.ru (BGN/PCGN), stopwords stripped, truncated.
//
// Re-run if chapter titles change. Hand-edit data/slugs.ts for SEO-tuning the
// top chapters ("probuzhdenie-oto-sna" > "slova-pominaniya-pri-probuzhdenii-oto-sna").

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const chaptersDir = path.join(root, 'data', 'chapters');

const RU_TO_LAT = {
  а:'a', б:'b', в:'v', г:'g', д:'d', е:'e', ё:'yo', ж:'zh', з:'z', и:'i',
  й:'y', к:'k', л:'l', м:'m', н:'n', о:'o', п:'p', р:'r', с:'s', т:'t',
  у:'u', ф:'f', х:'kh', ц:'ts', ч:'ch', ш:'sh', щ:'shch', ъ:'', ы:'y',
  ь:'', э:'e', ю:'yu', я:'ya',
  '‘':'', '’':'', '«':'', '»':'',
};

const RU_STOPWORDS = new Set([
  'и','или','в','во','на','по','за','от','до','с','со','у','к','о','об','из',
  'при','для','над','под','про','без','через','между','а','но','же','бы','ли',
  'то','ото','как','что','чтобы','если','когда','где','куда','чем','кем','кого',
  'кому','который','которая','которое','которые','быть','есть','это','этот','эта',
  'эти','тот','та','те','такой','такая','такое','такие','не','ни','да','ну','вот',
  'вам','вас','нам','нас','ему','ей','им','их','его','её','её','тем','тех','там',
  'здесь','тут','сюда','туда','раз','ещё','еще','уже','все','всё','весь','вся','всё',
  'мой','моя','моё','мои','твой','твоя','твоё','твои','наш','наша','наше','наши',
  'ваш','ваша','ваше','ваши','свой','своя','своё','свои','кто','чего','чему','чём',
]);

function translitRu(s) {
  return s
    .toLowerCase()
    .split('')
    .map((ch) => (ch in RU_TO_LAT ? RU_TO_LAT[ch] : ch))
    .join('');
}

function slugify(s, { stopwords = true, maxWords = 6 } = {}) {
  let out = translitRu(s)
    .replace(/[^a-z0-9\s-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  let words = out.split(' ').filter(Boolean);
  if (stopwords) words = words.filter((w) => !RU_STOPWORDS.has(w) && w.length > 1);
  words = words.slice(0, maxWords);
  return words.join('-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

function readChapterTitle(file) {
  const src = fs.readFileSync(path.join(chaptersDir, file), 'utf8');
  const m = src.match(/title\s*:\s*\{\s*ru\s*:\s*"((?:[^"\\]|\\.)*)"\s*,\s*en\s*:\s*"((?:[^"\\]|\\.)*)"\s*\}/);
  return m ? { ru: m[1], en: m[2] } : null;
}

const entries = fs
  .readdirSync(chaptersDir)
  .filter((f) => /^\d+-.+\.ts$/.test(f))
  .sort()
  .map((f) => {
    const id = parseInt(f.split('-')[0], 10);
    // EN slug = filename minus "NNN-" prefix and ".ts" suffix
    const enSlug = f.replace(/^\d+-/, '').replace(/\.ts$/, '');
    const title = readChapterTitle(f);
    if (!title) throw new Error(`No title in ${f}`);
    const ruSlug = slugify(title.ru);
    return { id, enSlug, ruSlug, title };
  });

// Check for duplicate RU slugs — append a short suffix from title if any collide
const ruCounts = new Map();
for (const e of entries) ruCounts.set(e.ruSlug, (ruCounts.get(e.ruSlug) || 0) + 1);
const seenRu = new Map();
for (const e of entries) {
  if ((ruCounts.get(e.ruSlug) || 0) > 1) {
    const idx = (seenRu.get(e.ruSlug) || 0) + 1;
    seenRu.set(e.ruSlug, idx);
    e.ruSlug = `${e.ruSlug}-${idx}`;
  }
}

// Emit TS file
const lines = [];
lines.push('// Auto-generated by scripts/generate-slugs.mjs.');
lines.push('// Safe to hand-edit: EN slug defaults to filename; RU slug is transliterated.');
lines.push('// Tune the top 30 chapters here for SEO (shorter, keyword-rich slugs rank better).');
lines.push('');
lines.push('export interface ChapterSlugs {');
lines.push('  ru: string;');
lines.push('  en: string;');
lines.push('}');
lines.push('');
lines.push('export const CHAPTER_SLUGS: Record<number, ChapterSlugs> = {');
for (const e of entries) {
  lines.push(`  ${e.id}: { ru: "${e.ruSlug}", en: "${e.enSlug}" }, // ${e.title.ru} / ${e.title.en}`);
}
lines.push('};');
lines.push('');
lines.push('export function getChapterSlug(id: number, lang: "ru" | "en"): string {');
lines.push('  const s = CHAPTER_SLUGS[id];');
lines.push('  if (!s) throw new Error(`No slug for chapter ${id}`);');
lines.push('  return s[lang];');
lines.push('}');
lines.push('');

const outFile = path.join(root, 'data', 'slugs.ts');
fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(`✓ data/slugs.ts — ${entries.length} chapters`);

// Print a sample
console.log('\nFirst 10 samples:');
for (const e of entries.slice(0, 10)) {
  console.log(`  ${e.id}: /${e.ruSlug}/ | /en/${e.enSlug}/`);
}
